// Code generated by goplus from calls.gp. DO NOT EDIT.
//goplus:v v0.16.1

package typescript

import (
	"strings"

	"goforge.dev/assayxport/internal/schema"
	"goforge.dev/assayxport/internal/ts"
)

// Call resolution ladder (mirrors the Go/Java/Python extractors):
//
//	identifier callee   f()      -> internal if f is a top-level func/class here
//	                                 (Ref unitID#f); external if f is imported
//	                                 (Target = module specifier); builtin if a
//	                                 JS/TS global; else unresolved.
//	member callee       ns.f()   -> external when ns is an import namespace;
//	                                 builtin when ns is a global (Math, console…);
//	                                 this.m() -> internal; else unresolved.
//	non-name callee      f()()    -> dynamic.
//
// Only top-level imports/declarations are recorded; imports inside functions are
// ignored, matching the other extractors.
type tsFileCtx struct {
	unitID  string
	funcs   map[string]bool   // top-level function / arrow-const names
	classes map[string]bool   // top-level class names
	imports map[string]string // local name -> module specifier
}

// buildFileCtx does one pass over the top level to record local declarations and
// imports for call classification.
func buildFileCtx(root ts.Node, src []byte, unitID string) *tsFileCtx {
	ctx := &tsFileCtx{unitID: unitID, funcs: map[string]bool{}, classes: map[string]bool{}, imports: map[string]string{}}
	for _, n := range root.NamedChildren() {
		if n.Type() == "import_statement" {
			addImport(n, src, ctx)
			continue
		}
		d, _ := unwrapExport(n)
		if d.IsNull() {
			continue
		}
		switch d.Type() {
		case "function_declaration", "generator_function_declaration":
			ctx.funcs[fieldText(d, "name", src)] = true
		case "class_declaration", "abstract_class_declaration":
			ctx.classes[fieldText(d, "name", src)] = true
		case "lexical_declaration", "variable_declaration":
			for _, dr := range d.NamedChildren() {
				if dr.Type() != "variable_declarator" {
					continue
				}
				if v, ok := dr.ChildByFieldName("value"); ok && (v.Type() == "arrow_function" || v.Type() == "function_expression") {
					ctx.funcs[fieldText(dr, "name", src)] = true
				}
			}
		}
	}
	return ctx
}

// addImport maps each name introduced by an import statement to its module
// specifier: named ({a, b as c}), namespace (* as ns), and default imports.
func addImport(n ts.Node, src []byte, ctx *tsFileCtx) {
	spec := importSource(n, src)
	if spec == "" {
		return
	}
	clause := childOfType(n, "import_clause")
	if clause.IsNull() {
		return
	}
	for _, c := range clause.NamedChildren() {
		switch c.Type() {
		case "identifier": // default import
			ctx.imports[c.Content(src)] = spec
		case "namespace_import": // * as ns
			if id := childOfType(c, "identifier"); !id.IsNull() {
				ctx.imports[id.Content(src)] = spec
			}
		case "named_imports":
			for _, isp := range c.NamedChildren() {
				if isp.Type() != "import_specifier" {
					continue
				}
				local := fieldText(isp, "alias", src)
				if local == "" {
					local = fieldText(isp, "name", src)
				}
				if local != "" {
					ctx.imports[local] = spec
				}
			}
		}
	}
}

func importSource(n ts.Node, src []byte) string {
	s, ok := n.ChildByFieldName("source")
	if !ok {
		s = childOfType(n, "string")
	}
	if s.IsNull() {
		return ""
	}
	return strings.Trim(collapseWS(s.Content(src)), "\"'`")
}

// tsCalls collects and de-duplicates the outbound calls in a callable's body.
// Nested arrow/function bodies are walked and attributed to the enclosing symbol.
func tsCalls(n ts.Node, unitID string, src []byte, ctx *tsFileCtx) []schema.Call {
	body, ok := n.ChildByFieldName("body")
	if !ok {
		return nil
	}
	var raw []schema.Call
	var walk func(ts.Node)
	walk = func(x ts.Node) {
		if x.IsNull() {
			return
		}
		if x.Type() == "call_expression" || x.Type() == "new_expression" {
			if e, ok := callEdge(x, unitID, src, ctx); ok {
				raw = append(raw, e)
			}
		}
		for _, c := range x.NamedChildren() {
			walk(c)
		}
	}
	walk(body)
	return schema.DedupeCalls(raw)
}

func callEdge(call ts.Node, unitID string, src []byte, ctx *tsFileCtx) (schema.Call, bool) {
	fn, ok := call.ChildByFieldName("function")
	if !ok {
		fn = childOfType(call, "identifier") // new_expression uses "constructor"
		if fn.IsNull() {
			if c, ok := call.ChildByFieldName("constructor"); ok {
				fn = c
			}
		}
	}
	if fn.IsNull() {
		return schema.Call{}, false
	}
	switch fn.Type() {
	case "identifier":
		name := fn.Content(src)
		switch {
		case ctx.funcs[name] || ctx.classes[name]:
			return schema.Call{Target: name, Kind: "internal", Ref: unitID + "#" + name}, true
		case ctx.imports[name] != "":
			return schema.Call{Target: ctx.imports[name] + ":" + name, Kind: "external"}, true
		case tsBuiltins[name]:
			return schema.Call{Target: name, Kind: "builtin"}, true
		default:
			return schema.Call{Target: name, Kind: "unresolved"}, true
		}
	case "member_expression":
		obj := fieldText(fn, "object", src)
		prop := fieldText(fn, "property", src)
		switch {
		case ctx.imports[obj] != "":
			return schema.Call{Target: ctx.imports[obj] + ":" + prop, Kind: "external"}, true
		case tsBuiltins[obj]:
			return schema.Call{Target: obj + "." + prop, Kind: "builtin"}, true
		case obj == "this" || obj == "super":
			return schema.Call{Target: obj + "." + prop, Kind: "internal", Ref: unitID + "#" + prop}, true
		default:
			return schema.Call{Target: collapseWS(fn.Content(src)), Kind: "unresolved"}, true
		}
	default:
		// callee is itself an expression (f()(), (a||b)()): dynamic dispatch.
		return schema.Call{Target: collapseWS(firstLine(fn.Content(src))), Kind: "dynamic"}, true
	}
}

// tsBuiltins are the JS/TS globals a call resolves to "builtin" (the standard
// library floor, not first-party and not an import).
var tsBuiltins = map[string]bool{
	"console": true, "Math": true, "JSON": true, "Object": true, "Array": true,
	"Promise": true, "Number": true, "String": true, "Boolean": true, "Symbol": true,
	"Map": true, "Set": true, "WeakMap": true, "WeakSet": true, "Date": true,
	"RegExp": true, "Error": true, "Reflect": true, "Proxy": true, "globalThis": true,
	"parseInt": true, "parseFloat": true, "isNaN": true, "isFinite": true,
	"encodeURIComponent": true, "decodeURIComponent": true, "structuredClone": true,
	"fetch": true, "setTimeout": true, "setInterval": true, "clearTimeout": true,
	"clearInterval": true, "queueMicrotask": true, "BigInt": true,
}
