// Code generated by goplus from typescript.gp. DO NOT EDIT.
//goplus:v v0.16.1

// Package typescript implements the assayxport Extractor for TypeScript and
// JavaScript source trees. It produces one schema.Package per source file (level
// "module"), keyed by the file's slash path without extension so ids never embed
// host paths above the scan root. Plain JavaScript files are extracted the same
// way but flagged as untyped: assayxport's TS support is oriented at the newest
// standards, so a symbol that "works" yet forfeits its type contract (an `any`,
// an `as any`, a non-null `!`, a `@ts-ignore`, an untyped parameter, loose
// equality) carries a Concern the explorer surfaces.
package typescript

import (
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"sync"

	"goforge.dev/assayxport/internal/schema"
	"goforge.dev/assayxport/internal/ts"
)

// grammar selects which tree-sitter grammar parses a file (see langFor).
const (
	grammarTS = iota
	grammarTSX
	grammarJS
)

func tsGrammar(g int) ts.Language {
	switch g {
	case grammarTSX:
		return ts.TSX
	case grammarJS:
		return ts.JavaScript
	default:
		return ts.TypeScript
	}
}

// Extractor implements extract.Extractor for TypeScript/JavaScript.
type Extractor struct{}

// New returns a new TypeScript/JavaScript Extractor.
func New() *Extractor { return &Extractor{} }

// Language returns "typescript". The extractor also handles JavaScript; each
// module records its own Language ("typescript" or "javascript").
func (*Extractor) Language() string { return "typescript" }

// moduleID is the file's slash path without its extension -- the manifest id and
// the target of internal call refs. e.g. "core/geometry.ts" -> "core/geometry".
func moduleID(rel string) string {
	rel = filepath.ToSlash(rel)
	for _, ext := range []string{".d.ts", ".tsx", ".ts", ".mts", ".cts", ".jsx", ".js", ".mjs", ".cjs"} {
		if strings.HasSuffix(rel, ext) {
			return strings.TrimSuffix(rel, ext)
		}
	}
	return rel
}

// baseStem is the file's name without directory or extension.
func baseStem(rel string) string {
	return moduleID(filepath.Base(rel))
}

// Skeleton enumerates one module package per discovered file WITHOUT parsing --
// id/path/name/language only, no symbols. It shares discover() with
// ExtractStream, so every skeleton id matches the id its real package will carry.
func (*Extractor) Skeleton(root string) ([]schema.Package, error) {
	files, err := discover(root)
	if err != nil {
		return nil, err
	}
	out := make([]schema.Package, 0, len(files))
	for _, f := range files {
		_, isTS, _ := langFor(filepath.Base(f.Rel))
		lang := "typescript"
		if !isTS {
			lang = "javascript"
		}
		out = append(out, schema.Package{
			ID:       moduleID(f.Rel),
			Language: lang,
			Path:     f.Rel,
			Name:     baseStem(f.Rel),
			Level:    "module",
		})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out, nil
}

// ExtractOne parses the single file behind a skeleton package (its Path is the
// slash-relative file path Skeleton produced), so `ax serve` can parse packages
// in a demand-driven order rather than a fixed walk. It reconstructs the same
// absolute path discover would have and reuses extractFile.
func (*Extractor) ExtractOne(root string, pkg schema.Package) (schema.Package, error) {
	absRoot, err := filepath.Abs(root)
	if err != nil {
		return schema.Package{}, err
	}
	abs := filepath.Join(absRoot, filepath.FromSlash(pkg.Path))
	return extractFile(tsFile{Abs: abs, Rel: pkg.Path})
}

// extractFile parses one discovered file into its module package. It holds no
// shared state, so it is safe to call from many workers at once (the tree-sitter
// backend is cgo-free with a fresh parser per call).
func extractFile(f tsFile) (schema.Package, error) {
	src, err := os.ReadFile(f.Abs)
	if err != nil {
		return schema.Package{}, err
	}
	g, isTS, _ := langFor(filepath.Base(f.Rel))
	id := moduleID(f.Rel)
	syms, moduleDoc, cerr := moduleSymbols(tsGrammar(g), f.Rel, id, src, isTS)
	if cerr != nil {
		return schema.Package{}, cerr
	}
	lang := "typescript"
	if !isTS {
		lang = "javascript"
	}
	return schema.Package{
		ID:       id,
		Language: lang,
		Path:     f.Rel,
		Name:     baseStem(f.Rel),
		Level:    "module",
		Doc:      moduleDoc,
		Symbols:  syms,
	}, nil
}

// ExtractStream discovers all TS/JS files under root and emits one module package
// per file as soon as it is parsed, from a worker pool. Emitting per file (rather
// than buffering the whole tree like Extract) keeps peak memory to a few in-flight
// packages and lets `ax serve` publish shards progressively instead of waiting for
// the entire repo. emit is called concurrently and must synchronize itself
// (emit.Writer.Add does). The first parse error aborts the pool.
func (*Extractor) ExtractStream(root string, emit func(schema.Package) error) error {
	files, err := discover(root)
	if err != nil {
		return err
	}

	workers := runtime.NumCPU() - 1
	if workers < 1 {
		workers = 1
	}
	var (
		wg       sync.WaitGroup
		mu       sync.Mutex
		first    error
		stopOnce sync.Once
	)
	done := make(chan struct{}) // closed once, on the first error, to abort the pool
	fail := func(e error) {
		mu.Lock()
		if first == nil {
			first = e
		}
		mu.Unlock()
		stopOnce.Do(func() { close(done) })
	}
	jobs := make(chan int)
	for w := 0; w < workers; w++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for i := range jobs {
				pkg, e := extractFile(files[i])
				if e != nil {
					fail(e)
					return
				}
				if e := emit(pkg); e != nil {
					fail(e)
					return
				}
			}
		}()
	}
	// Feed jobs, but bail the moment a worker signals an error so the send never
	// blocks on a drained pool.
feed:
	for i := range files {
		select {
		case jobs <- i:
		case <-done:
			break feed
		}
	}
	close(jobs)
	wg.Wait()
	return first
}

// Extract discovers all TS/JS files under root and returns one module package per
// file, sorted by id -- the buffered counterpart of ExtractStream for callers
// (--stdout, --no-wasm, tests) that need the whole manifest at once.
func (e *Extractor) Extract(root string) ([]schema.Package, error) {
	var (
		mu  sync.Mutex
		out []schema.Package
	)
	if err := e.ExtractStream(root, func(p schema.Package) error {
		mu.Lock()
		out = append(out, p)
		mu.Unlock()
		return nil
	}); err != nil {
		return nil, err
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out, nil
}
