// Code generated by goplus from explorer.gp. DO NOT EDIT.
//goplus:v v0.16.1

// Package explorer renders the interactive manifest explorer: a single
// self-contained HTML file with the combined manifest embedded, viewable
// offline in any browser with no server and no external assets.
//
// The manifest is embedded base64-encoded rather than as raw JSON. A
// multi-megabyte JSON blob inside a <script> tag passes through the
// browser's HTML tokenizer before JSON.parse ever sees it, and that path
// has edge cases (script-data states, transport quirks) that can corrupt
// the payload. Base64's alphabet contains nothing the tokenizer can
// misread, so the same bytes that were encoded are the bytes decoded.
package explorer

import (
	"bytes"
	_ "embed"
	"encoding/base64"
)

//go:embed explorer.html
var tmpl []byte

// seedSlot is replaced with the base64 of the combined manifest (embedded
// mode only). liveSlot is replaced with the live-reload script by `ax serve`
// (watch mode) and left inert by `ax assay`. modeSlot carries a one-line flag
// that flips the page into lazy mode, and bootSlot is where Shell injects the
// WASM bootstrap (wasm_exec.js + instantiate); both are empty in a static
// artifact.
var (
	seedSlot = []byte("/*SEED*/")
	liveSlot = []byte("/*LIVE*/")
	modeSlot = []byte("/*MODE*/")
	bootSlot = []byte("<!--BOOT-->")
)

// wasmBootstrap loads the toolchain glue and instantiates the WASM data
// engine, which fetches /api/index and then installs window.axapi and calls
// window.__axReady. Served only by `ax serve` in lazy mode; the .wasm arrives
// gzip-compressed (Content-Encoding: gzip) so instantiateStreaming streams it.
const wasmBootstrap = `<script src="/static/wasm_exec.js"></script>
<script>
(function(){
  if(!("instantiateStreaming" in WebAssembly)){
    // Very old engines: fall back to arrayBuffer instantiate.
    WebAssembly.instantiateStreaming=function(resp,imp){
      return resp.then(function(r){return r.arrayBuffer()}).then(function(b){return WebAssembly.instantiate(b,imp)})};
  }
  var go=new Go();
  WebAssembly.instantiateStreaming(fetch("/static/explorer.wasm"),go.importObject)
    .then(function(res){go.run(res.instance)})
    .catch(function(e){console.error("axwasm: instantiate failed",e)});
})();
</script>`

// liveJS reloads the page when the server signals that the manifest
// changed. It is injected only by `ax serve` in watch mode; the static
// artifact written by `ax assay` never carries it.
const liveJS = `(function(){try{var es=new EventSource("/__events");` +
	`es.addEventListener("reload",function(){location.reload()});}catch(e){}})();`

// Render returns the explorer HTML with the combined manifest (the exact
// bytes emit.Combined produces) embedded. When live is true the page also
// subscribes to /__events and reloads itself when the server emits a
// "reload" event.
//
// Output is deterministic for equal inputs when live is fixed: the
// template is embedded at compile time and base64 is a pure function.
func Render(combinedManifest []byte, live bool) []byte {
	b64 := base64.StdEncoding.EncodeToString(combinedManifest)
	out := bytes.Replace(tmpl, seedSlot, []byte(b64), 1)
	out = bytes.Replace(out, modeSlot, nil, 1)
	out = bytes.Replace(out, bootSlot, nil, 1)
	js := ""
	if live {
		js = liveJS
	}
	return bytes.Replace(out, liveSlot, []byte(js), 1)
}

// Shell returns the explorer HTML for lazy (WASM) mode: no manifest is
// embedded (the seed stays empty), the page is flipped into lazy mode, and the
// WASM bootstrap is injected. The page then fetches /api/index and hydrates
// each package's shard on demand -- the mode `ax serve` uses so a large tree
// is explorable without ever building a single multi-hundred-MB page. When
// live is true it also carries the /__events live-reload subscription.
func Shell(live bool) []byte {
	out := bytes.Replace(tmpl, seedSlot, nil, 1)
	out = bytes.Replace(out, modeSlot, []byte("window.__LAZY=true;"), 1)
	out = bytes.Replace(out, bootSlot, []byte(wasmBootstrap), 1)
	js := ""
	if live {
		js = liveJS
	}
	return bytes.Replace(out, liveSlot, []byte(js), 1)
}
