// Code generated by goplus from verify.gp. DO NOT EDIT.
//goplus:v v0.28.0

package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strings"

	"goforge.dev/assayxport/internal/schema"
	"goforge.dev/goplus/std/result"
)

//goplus:enum TraceCommandResult
type TraceCommandResult interface{ isTraceCommandResult() }

//goplus:variant (TraceCommandResult) TraceCommandCompleted()
type TraceCommandCompleted struct{}

func (TraceCommandCompleted) isTraceCommandResult() {}

// TraceCommandResultCases selects one handler per TraceCommandResult variant for TraceCommandResultFold.
type TraceCommandResultCases[R any] struct {
	TraceCommandCompleted func() R
}

// TraceCommandResultFold reduces TraceCommandResult by one-level case analysis.
func TraceCommandResultFold[R any](t TraceCommandResult, cs TraceCommandResultCases[R]) R {
	switch any(t).(type) {
	case TraceCommandCompleted:
		return cs.TraceCommandCompleted()
	default:
		panic("goplus: impossible enum value in TraceCommandResultFold")
	}
}

// TraceCommandResultEqOverrides carries optional per-variant hooks for TraceCommandResultEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type TraceCommandResultEqOverrides struct {
	TraceCommandCompleted func(x, y TraceCommandCompleted) (eq, handled bool)
}

// TraceCommandResultEqualWith reports structural equality of a and b under ov.
func TraceCommandResultEqualWith(a, b TraceCommandResult, ov TraceCommandResultEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case TraceCommandCompleted:
		y, ok := any(b).(TraceCommandCompleted)
		if !ok {
			return false
		}
		if ov.TraceCommandCompleted != nil {
			if eq, handled := ov.TraceCommandCompleted(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// TraceCommandResultEqual reports structural equality of a and b.
func TraceCommandResultEqual(a, b TraceCommandResult) bool {
	return TraceCommandResultEqualWith(a, b, TraceCommandResultEqOverrides{})
}

//goplus:enum TraceCommandFailure
type TraceCommandFailure interface{ isTraceCommandFailure() }

//goplus:variant (TraceCommandFailure) TraceFlagFailure(Cause error)
type TraceFlagFailure struct {
	Cause error
}

func (TraceFlagFailure) isTraceCommandFailure() {}

//goplus:variant (TraceCommandFailure) TraceReadFailure(Path string, Cause error)
type TraceReadFailure struct {
	Path  string
	Cause error
}

func (TraceReadFailure) isTraceCommandFailure() {}

//goplus:variant (TraceCommandFailure) TraceDecodeFailure(Path string, Cause error)
type TraceDecodeFailure struct {
	Path  string
	Cause error
}

func (TraceDecodeFailure) isTraceCommandFailure() {}

//goplus:variant (TraceCommandFailure) TraceRejected(Causes []schema.TraceFailure)
type TraceRejected struct {
	Causes []schema.TraceFailure
}

func (TraceRejected) isTraceCommandFailure() {}

//goplus:variant (TraceCommandFailure) TraceWriteFailure(Cause error)
type TraceWriteFailure struct {
	Cause error
}

func (TraceWriteFailure) isTraceCommandFailure() {}

//goplus:variant (TraceCommandFailure) TraceUsageFailure(Detail string)
type TraceUsageFailure struct {
	Detail string
}

func (TraceUsageFailure) isTraceCommandFailure() {}

// TraceCommandFailureCases selects one handler per TraceCommandFailure variant for TraceCommandFailureFold.
type TraceCommandFailureCases[R any] struct {
	TraceFlagFailure   func(Cause error) R
	TraceReadFailure   func(Path string, Cause error) R
	TraceDecodeFailure func(Path string, Cause error) R
	TraceRejected      func(Causes []schema.TraceFailure) R
	TraceWriteFailure  func(Cause error) R
	TraceUsageFailure  func(Detail string) R
}

// TraceCommandFailureFold reduces TraceCommandFailure by one-level case analysis.
func TraceCommandFailureFold[R any](t TraceCommandFailure, cs TraceCommandFailureCases[R]) R {
	switch m := any(t).(type) {
	case TraceFlagFailure:
		return cs.TraceFlagFailure(m.Cause)
	case TraceReadFailure:
		return cs.TraceReadFailure(m.Path, m.Cause)
	case TraceDecodeFailure:
		return cs.TraceDecodeFailure(m.Path, m.Cause)
	case TraceRejected:
		return cs.TraceRejected(m.Causes)
	case TraceWriteFailure:
		return cs.TraceWriteFailure(m.Cause)
	case TraceUsageFailure:
		return cs.TraceUsageFailure(m.Detail)
	default:
		panic("goplus: impossible enum value in TraceCommandFailureFold")
	}
}

// TraceCommandFailureEqOverrides carries optional per-variant hooks for TraceCommandFailureEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type TraceCommandFailureEqOverrides struct {
	TraceFlagFailure   func(x, y TraceFlagFailure) (eq, handled bool)
	TraceReadFailure   func(x, y TraceReadFailure) (eq, handled bool)
	TraceDecodeFailure func(x, y TraceDecodeFailure) (eq, handled bool)
	TraceRejected      func(x, y TraceRejected) (eq, handled bool)
	TraceWriteFailure  func(x, y TraceWriteFailure) (eq, handled bool)
	TraceUsageFailure  func(x, y TraceUsageFailure) (eq, handled bool)
}

// TraceCommandFailureEqualWith reports structural equality of a and b under ov.
func TraceCommandFailureEqualWith(a, b TraceCommandFailure, ov TraceCommandFailureEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case TraceFlagFailure:
		y, ok := any(b).(TraceFlagFailure)
		if !ok {
			return false
		}
		if ov.TraceFlagFailure != nil {
			if eq, handled := ov.TraceFlagFailure(x, y); handled {
				return eq
			}
		}
		if (x.Cause == nil) != (y.Cause == nil) {
			return false
		}
		if x.Cause != nil && x.Cause.Error() != y.Cause.Error() {
			return false
		}
		return true
	case TraceReadFailure:
		y, ok := any(b).(TraceReadFailure)
		if !ok {
			return false
		}
		if ov.TraceReadFailure != nil {
			if eq, handled := ov.TraceReadFailure(x, y); handled {
				return eq
			}
		}
		if x.Path != y.Path {
			return false
		}
		if (x.Cause == nil) != (y.Cause == nil) {
			return false
		}
		if x.Cause != nil && x.Cause.Error() != y.Cause.Error() {
			return false
		}
		return true
	case TraceDecodeFailure:
		y, ok := any(b).(TraceDecodeFailure)
		if !ok {
			return false
		}
		if ov.TraceDecodeFailure != nil {
			if eq, handled := ov.TraceDecodeFailure(x, y); handled {
				return eq
			}
		}
		if x.Path != y.Path {
			return false
		}
		if (x.Cause == nil) != (y.Cause == nil) {
			return false
		}
		if x.Cause != nil && x.Cause.Error() != y.Cause.Error() {
			return false
		}
		return true
	case TraceRejected:
		y, ok := any(b).(TraceRejected)
		if !ok {
			return false
		}
		if ov.TraceRejected != nil {
			if eq, handled := ov.TraceRejected(x, y); handled {
				return eq
			}
		}
		if len(x.Causes) != len(y.Causes) {
			return false
		}
		for i0 := range x.Causes {
			if x.Causes[i0] != y.Causes[i0] {
				return false
			}
		}
		return true
	case TraceWriteFailure:
		y, ok := any(b).(TraceWriteFailure)
		if !ok {
			return false
		}
		if ov.TraceWriteFailure != nil {
			if eq, handled := ov.TraceWriteFailure(x, y); handled {
				return eq
			}
		}
		if (x.Cause == nil) != (y.Cause == nil) {
			return false
		}
		if x.Cause != nil && x.Cause.Error() != y.Cause.Error() {
			return false
		}
		return true
	case TraceUsageFailure:
		y, ok := any(b).(TraceUsageFailure)
		if !ok {
			return false
		}
		if ov.TraceUsageFailure != nil {
			if eq, handled := ov.TraceUsageFailure(x, y); handled {
				return eq
			}
		}
		if x.Detail != y.Detail {
			return false
		}
		return true
	}
	return false
}

// TraceCommandFailureEqual reports structural equality of a and b.
func TraceCommandFailureEqual(a, b TraceCommandFailure) bool {
	return TraceCommandFailureEqualWith(a, b, TraceCommandFailureEqOverrides{})
}

//goplus:method (TraceCommandFailure) Error
func Error(failure TraceCommandFailure) string {
	switch __gp_m0 := any(failure).(type) {
	case TraceFlagFailure:
		cause := __gp_m0.Cause
		return cause.Error()
	case TraceReadFailure:
		path := __gp_m0.Path
		cause := __gp_m0.Cause
		return fmt.Sprintf("read %s: %v", path, cause)
	case TraceDecodeFailure:
		path := __gp_m0.Path
		cause := __gp_m0.Cause
		return fmt.Sprintf("decode %s: %v", path, cause)
	case TraceRejected:
		causes := __gp_m0.Causes

		lines := make([]string, len(causes))
		for index, cause := range causes {
			lines[index] = schema.Error(cause)
		}
		return strings.Join(lines, "\n")
	case TraceWriteFailure:
		cause := __gp_m0.Cause
		return fmt.Sprintf("write report: %v", cause)
	case TraceUsageFailure:
		detail := __gp_m0.Detail
		return detail
	default:
		panic("goplus: impossible enum value in match")
	}
}

func runVerifyCmd(arguments []string) error {
	switch __gp_m1 := any(verifyTraceCommand(arguments)).(type) {
	case result.Ok[TraceCommandResult, TraceCommandFailure]:
		return nil
	case result.Err[TraceCommandResult, TraceCommandFailure]:
		failure := __gp_m1.Err
		return fmt.Errorf("%s", Error(failure))
	default:
		panic("goplus: impossible enum value in match")
	}
}

func verifyTraceCommand(arguments []string) result.Result[TraceCommandResult, TraceCommandFailure] {
	flags := flag.NewFlagSet("ax verify", flag.ContinueOnError)
	baselinePath := flags.String("baseline", "", "previous release trace bundle")
	releaseID := flags.String("release", "", "release-note artifact id")
	flags.Usage = func() {
		fmt.Fprintln(os.Stderr, "usage: ax verify [trace.json] [-baseline previous.json -release release.id]")
		flags.PrintDefaults()
	}
	path, rest := splitPath(arguments)
	if path == "." {
		path = "assayxport.trace.json"
	}
	switch __gp_m2 := any(result.Of(true, flags.Parse(rest))).(type) {
	case result.Err[bool, error]:
		cause := __gp_m2.Err

		return result.Err[TraceCommandResult, TraceCommandFailure]{Err: TraceFlagFailure{Cause: cause}}
	case result.Ok[bool, error]:

	default:
		panic("goplus: impossible enum value in match")
	}
	if flags.NArg() > 0 {
		path = flags.Arg(0)
	}
	switch __gp_m3 := any(readTraceBundle(path)).(type) {
	case result.Err[schema.TraceBundle, TraceCommandFailure]:
		failure := __gp_m3.Err

		return result.Err[TraceCommandResult, TraceCommandFailure]{Err: failure}
	case result.Ok[schema.TraceBundle, TraceCommandFailure]:
		current := __gp_m3.Value

		if *baselinePath == "" {
			switch __gp_m4 := any(schema.ValidateTrace(current)).(type) {
			case result.Err[schema.TraceValidation, []schema.TraceFailure]:
				causes := __gp_m4.Err

				return result.Err[TraceCommandResult, TraceCommandFailure]{Err: TraceRejected{Causes: causes}}
			case result.Ok[schema.TraceValidation, []schema.TraceFailure]:

				return writeTraceReport(schema.TraceReport{Changed: []string{}, Missing: []string{}})
			default:
				panic("goplus: impossible enum value in match")
			}
		}
		if *releaseID == "" {
			return result.Err[TraceCommandResult, TraceCommandFailure]{Err: TraceUsageFailure{Detail: "-release is required with -baseline"}}
		}
		switch __gp_m5 := any(readTraceBundle(*baselinePath)).(type) {
		case result.Err[schema.TraceBundle, TraceCommandFailure]:
			failure := __gp_m5.Err

			return result.Err[TraceCommandResult, TraceCommandFailure]{Err: failure}
		case result.Ok[schema.TraceBundle, TraceCommandFailure]:
			baseline := __gp_m5.Value

			switch __gp_m6 := any(schema.VerifyRelease(baseline, current, *releaseID)).(type) {
			case result.Err[schema.TraceReport, []schema.TraceFailure]:
				causes := __gp_m6.Err

				return result.Err[TraceCommandResult, TraceCommandFailure]{Err: TraceRejected{Causes: causes}}
			case result.Ok[schema.TraceReport, []schema.TraceFailure]:
				report := __gp_m6.Value

				return writeTraceReport(report)
			default:
				panic("goplus: impossible enum value in match")
			}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func readTraceBundle(path string) result.Result[schema.TraceBundle, TraceCommandFailure] {
	content, readError := os.ReadFile(path)
	switch __gp_m7 := any(result.Of(content, readError)).(type) {
	case result.Err[[]byte, error]:
		cause := __gp_m7.Err

		return result.Err[schema.TraceBundle, TraceCommandFailure]{Err: TraceReadFailure{Path: path, Cause: cause}}
	case result.Ok[[]byte, error]:
		raw := __gp_m7.Value

		var bundle schema.TraceBundle
		decoder := json.NewDecoder(strings.NewReader(string(raw)))
		decoder.DisallowUnknownFields()
		switch __gp_m8 := any(result.Of(true, decoder.Decode(&bundle))).(type) {
		case result.Err[bool, error]:
			cause := __gp_m8.Err

			return result.Err[schema.TraceBundle, TraceCommandFailure]{Err: TraceDecodeFailure{Path: path, Cause: cause}}
		case result.Ok[bool, error]:

			return result.Ok[schema.TraceBundle, TraceCommandFailure]{Value: bundle}
		default:
			panic("goplus: impossible enum value in match")
		}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func writeTraceReport(report schema.TraceReport) result.Result[TraceCommandResult, TraceCommandFailure] {
	encoder := json.NewEncoder(os.Stdout)
	encoder.SetIndent("", "  ")
	switch __gp_m9 := any(result.Of(true, encoder.Encode(report))).(type) {
	case result.Err[bool, error]:
		cause := __gp_m9.Err

		return result.Err[TraceCommandResult, TraceCommandFailure]{Err: TraceWriteFailure{Cause: cause}}
	case result.Ok[bool, error]:

		return result.Ok[TraceCommandResult, TraceCommandFailure]{Value: TraceCommandCompleted{}}
	default:
		panic("goplus: impossible enum value in match")
	}
}
