// Code generated by goplus from hierarchy.gp. DO NOT EDIT.
//goplus:v v0.16.1

package hierarchy

import (
	"testing"

	"pgregory.net/rapid"
)

func TestSummaryMonoidLaws(t *testing.T) {
	t.Run("Semigroup.Assoc", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[Summary]().Draw(rt, "a")
			b := rapid.Make[Summary]().Draw(rt, "b")
			c := rapid.Make[Summary]().Draw(rt, "c")
			if !SummaryMonoid.AsSemigroup().LawAssoc(a, b, c) {
				rt.Fatalf("law Assoc violated: a=%v b=%v c=%v", a, b, c)
			}
		})
	})
	t.Run("UnitalMagma.LeftId", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[Summary]().Draw(rt, "a")
			if !SummaryMonoid.AsUnitalMagma().LawLeftId(a) {
				rt.Fatalf("law LeftId violated: a=%v", a)
			}
		})
	})
	t.Run("UnitalMagma.RightId", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[Summary]().Draw(rt, "a")
			if !SummaryMonoid.AsUnitalMagma().LawRightId(a) {
				rt.Fatalf("law RightId violated: a=%v", a)
			}
		})
	})
}
