// Code generated by goplus from symbols.gp. DO NOT EDIT.
//goplus:v v0.15.0

package python

import (
	"strings"

	"goforge.dev/assayxport/internal/complexity"
	"goforge.dev/assayxport/internal/schema"
	"goforge.dev/assayxport/internal/ts"
)

// moduleSymbols parses one module's source and returns its top-level symbols
// (with nested methods/attrs owned), the module docstring (used by Task 4 for
// the module unit's Doc), the module's __all__ set (nil if none), and whether
// the module contains an `if __name__ == "__main__":` guard. unitID is the
// manifest id this module's symbols will live under; call edges use it to
// build internal refs.
//
// Node-name note: the backing runtime (gotreesitter) emits module- and
// block-level docstrings as bare `string` nodes rather than wrapping them in
// an `expression_statement`, and there is no `expression_statement` node in
// the tree at all. The walk below therefore treats a leading `string` as the
// docstring statement directly.
func moduleSymbols(relFile string, src []byte, unitID string) (syms []schema.Symbol, moduleDoc string, allSet map[string]bool, hasMain bool, err error) {
	tree, perr := ts.Parse(ts.Python, src)
	if perr != nil {
		return nil, "", nil, false, perr
	}
	root := tree.Root()
	ctx := buildModuleCtx(root, src, unitID)

	// A leading license/header comment pushes the module docstring off named
	// index 0; the docstring is the first non-comment statement.
	docIdx := firstNonCommentIndex(root)

	n := root.NamedChildCount()
	for i := 0; i < n; i++ {
		child := root.NamedChild(i)
		switch child.Type() {
		case "string":
			// Module docstring: the first (non-comment) statement, if a string.
			if i == docIdx && moduleDoc == "" {
				moduleDoc = stringText(child, src)
			}
		case "expression_statement":
			// Canonical grammar wraps a bare string here; support it too.
			if inner := firstNamedString(child); !inner.IsNull() {
				if i == docIdx && moduleDoc == "" {
					moduleDoc = stringText(inner, src)
				}
			}
		case "assignment":
			if set, ok := parseAll(child, src); ok {
				allSet = set
				continue
			}
			syms = append(syms, assignmentVariables(child, "", src, relFile)...)
		case "function_definition", "async_function_definition":
			syms = append(syms, funcSymbol(child, "", src, relFile, nil, isAsyncDef(child, src), ctx))
		case "class_definition":
			syms = append(syms, classSymbols(child, src, relFile, nil, "", ctx)...)
		case "decorated_definition":
			decorators, def := unwrapDecorated(child, src)
			if def.IsNull() {
				continue
			}
			switch {
			case isFuncDef(def.Type()):
				syms = append(syms, funcSymbol(def, "", src, relFile, decorators, isAsyncDef(def, src), ctx))
			case def.Type() == "class_definition":
				syms = append(syms, classSymbols(def, src, relFile, decorators, "", ctx)...)
			}
		case "if_statement":
			if isMainGuard(child, src) {
				hasMain = true
			}
		}
	}

	// Stamp InAll on module-level symbols (owner == "") once __all__ is known.
	if allSet != nil {
		for i := range syms {
			if syms[i].Owner != "" {
				continue
			}
			v := allSet[syms[i].Name]
			b := v
			syms[i].InAll = &b
		}
	}

	return syms, moduleDoc, allSet, hasMain, nil
}

// funcSymbol builds a Symbol for a function_definition. owner is the enclosing
// class name (empty for module-level functions).
func funcSymbol(node ts.Node, owner string, src []byte, relFile string, decorators []string, isAsync bool, ctx *pyModuleCtx) schema.Symbol {
	name := fieldText(node, "name", src)

	kind := "function"
	if owner != "" {
		kind = "method"
	}
	if hasDecorator(decorators, "property") {
		kind = "property"
	}

	id := name
	if owner != "" {
		id = owner + "." + name
	}

	sig := &schema.Signature{
		Params:  params(node, src),
		Returns: returns(node, src),
	}
	if isAsync {
		sig.Modifiers = append(sig.Modifiers, "async")
	}

	// Recursion detection needs to know whether a same-named call is a self-call.
	// For a free function, that is a bare-name call `name(...)`. For a method, a
	// bare-name call resolves to an imported or module-level function, NOT the
	// method itself (a real self-call is `self.name(...)`), so pass the receiver
	// (first parameter) and require the qualified form. A staticmethod has no
	// receiver, so no recursion form is recognized (conservative).
	recv := ""
	if owner != "" && !hasDecorator(decorators, "staticmethod") {
		recv = firstParamName(node, src)
	}
	sym := schema.Symbol{
		ID:              id,
		Name:            name,
		Kind:            kind,
		Visibility:      pyVisibility(name),
		VisibilityIdiom: "underscore",
		Location:        locationOf(node, relFile),
		Owner:           owner,
		Doc:             bodyDoc(node, src),
		Complexity:      complexity.Estimate(pySummary(node, src, name, recv, owner != "")),
		Calls:           pyCalls(node, src, ctx, owner, recv),
		Signature:       sig,
		Decorators:      decorators,
	}
	return sym
}

// classSymbols builds the class Symbol plus symbols for its members (methods,
// properties, class-attribute variables, and nested classes), all owned by the
// class. ownerPrefix is the enclosing class's fully-qualified id ("" at module
// level); it makes nested classes and their members carry dotted ids/owners,
// e.g. Outer.Inner and Outer.Inner.method.
func classSymbols(node ts.Node, src []byte, relFile string, decorators []string, ownerPrefix string, ctx *pyModuleCtx) []schema.Symbol {
	name := fieldText(node, "name", src)
	id := name
	if ownerPrefix != "" {
		id = ownerPrefix + "." + name
	}
	class := schema.Symbol{
		ID:              id,
		Name:            name,
		Kind:            "class",
		Visibility:      pyVisibility(name),
		VisibilityIdiom: "underscore",
		Location:        locationOf(node, relFile),
		Owner:           ownerPrefix,
		Doc:             bodyDoc(node, src),
		Complexity:      schema.DeferredComplexity(),
		Decorators:      decorators,
	}
	out := []schema.Symbol{class}

	body, ok := node.ChildByFieldName("body")
	if !ok {
		return out
	}
	// Members are owned by this class's fully-qualified id.
	memberOwner := id
	for i := 0; i < body.NamedChildCount(); i++ {
		member := body.NamedChild(i)
		switch member.Type() {
		case "function_definition", "async_function_definition":
			out = append(out, funcSymbol(member, memberOwner, src, relFile, nil, isAsyncDef(member, src), ctx))
		case "class_definition":
			out = append(out, classSymbols(member, src, relFile, nil, memberOwner, ctx)...)
		case "decorated_definition":
			decos, def := unwrapDecorated(member, src)
			if def.IsNull() {
				continue
			}
			switch {
			case isFuncDef(def.Type()):
				out = append(out, funcSymbol(def, memberOwner, src, relFile, decos, isAsyncDef(def, src), ctx))
			case def.Type() == "class_definition":
				out = append(out, classSymbols(def, src, relFile, decos, memberOwner, ctx)...)
			}
		case "assignment":
			out = append(out, assignmentVariables(member, memberOwner, src, relFile)...)
		}
	}
	return out
}

// assignmentVariables builds variable Symbols for an assignment whose left side
// is a plain identifier. A chained assignment (`a = b = c = value`) nests on the
// right in the grammar, so every target identifier down the chain is emitted,
// not just the leftmost. owner is the enclosing class (empty at module level).
func assignmentVariables(node ts.Node, owner string, src []byte, relFile string) []schema.Symbol {
	var out []schema.Symbol
	cur := node
	for cur.Type() == "assignment" {
		left, ok := cur.ChildByFieldName("left")
		if ok && left.Type() == "identifier" {
			name := left.Content(src)
			id := name
			if owner != "" {
				id = owner + "." + name
			}
			typ := ""
			if t, ok := cur.ChildByFieldName("type"); ok {
				typ = t.Content(src)
			}
			out = append(out, schema.Symbol{
				ID:              id,
				Name:            name,
				Kind:            "variable",
				Visibility:      pyVisibility(name),
				VisibilityIdiom: "underscore",
				Location:        locationOf(node, relFile),
				Owner:           owner,
				Doc:             schema.Doc{},
				Complexity:      schema.DeferredComplexity(),
				Type:            typ,
			})
		}
		// Descend into a chained assignment: the right operand is itself an
		// assignment whose left is the next target. A non-assignment right is
		// the assigned value, which terminates the chain.
		right, ok := cur.ChildByFieldName("right")
		if !ok || right.Type() != "assignment" {
			break
		}
		cur = right
	}
	return out
}

// parseAll returns the set of string values when the assignment defines
// __all__ = [...] / (...).
func parseAll(node ts.Node, src []byte) (map[string]bool, bool) {
	left, ok := node.ChildByFieldName("left")
	if !ok || left.Type() != "identifier" || left.Content(src) != "__all__" {
		return nil, false
	}
	right, ok := node.ChildByFieldName("right")
	if !ok {
		return nil, false
	}
	if right.Type() != "list" && right.Type() != "tuple" && right.Type() != "set" {
		return nil, false
	}
	set := map[string]bool{}
	for i := 0; i < right.NamedChildCount(); i++ {
		elem := right.NamedChild(i)
		if elem.Type() == "string" {
			set[stringText(elem, src)] = true
		}
	}
	return set, true
}

// unwrapDecorated returns the decorator names and inner definition of a
// decorated_definition node.
func unwrapDecorated(node ts.Node, src []byte) (decorators []string, def ts.Node) {
	for i := 0; i < node.NamedChildCount(); i++ {
		c := node.NamedChild(i)
		if c.Type() == "decorator" {
			decorators = append(decorators, decoratorName(c, src))
		}
	}
	def, _ = node.ChildByFieldName("definition")
	return decorators, def
}

// decoratorName returns a decorator's dotted/called name without the leading @.
// It reads the decorator's expression node (its first named child) rather than
// the raw text, so a trailing inline comment such as
// `@property  # type: ignore[override]` does not become part of the name (that
// would break the @property-to-property-kind promotion in funcSymbol).
func decoratorName(node ts.Node, src []byte) string {
	if node.NamedChildCount() > 0 {
		expr := node.NamedChild(0)
		if !expr.IsNull() && expr.Type() != "comment" {
			return strings.TrimSpace(expr.Content(src))
		}
	}
	txt := strings.TrimSpace(node.Content(src))
	txt = strings.TrimPrefix(txt, "@")
	if i := strings.IndexByte(txt, '#'); i >= 0 {
		txt = txt[:i]
	}
	return strings.TrimSpace(txt)
}

func hasDecorator(decorators []string, name string) bool {
	for _, d := range decorators {
		if d == name {
			return true
		}
	}
	return false
}

// isFuncDef reports whether a node is a function definition. The pinned
// gotreesitter grammar emits "function_definition" for both sync and async
// defs, but the canonical tree-sitter-python grammar uses a dedicated
// "async_function_definition" type in some versions; accept both so a future
// grammar bump cannot silently drop async functions.
func isFuncDef(t string) bool {
	return t == "function_definition" || t == "async_function_definition"
}

// isAsyncDef reports whether a function definition is declared async.
func isAsyncDef(node ts.Node, src []byte) bool {
	if node.Type() == "async_function_definition" {
		return true
	}
	return strings.HasPrefix(strings.TrimSpace(node.Content(src)), "async")
}

// isMainGuard reports whether an if_statement is `if __name__ == "__main__":`.
func isMainGuard(node ts.Node, src []byte) bool {
	cond, ok := node.ChildByFieldName("condition")
	if !ok {
		return false
	}
	norm := strings.Join(strings.Fields(cond.Content(src)), "")
	// Normalize the quote character so single- and double-quoted guards
	// (`'__main__'` and `"__main__"`) both match.
	norm = strings.ReplaceAll(norm, "'", `"`)
	return norm == `__name__=="__main__"` || norm == `"__main__"==__name__`
}

// firstParamName returns the name of a function's first parameter (e.g. the
// "self"/"cls" receiver of a method), or "" if it has none.
func firstParamName(node ts.Node, src []byte) string {
	pnode, ok := node.ChildByFieldName("parameters")
	if !ok || pnode.NamedChildCount() == 0 {
		return ""
	}
	return paramFrom(pnode.NamedChild(0), src).Name
}

// params extracts the parameter list from a function_definition.
func params(node ts.Node, src []byte) []schema.Param {
	pnode, ok := node.ChildByFieldName("parameters")
	if !ok {
		return nil
	}
	var out []schema.Param
	for i := 0; i < pnode.NamedChildCount(); i++ {
		c := pnode.NamedChild(i)
		out = append(out, paramFrom(c, src))
	}
	return out
}

// paramFrom parses a single parameter node's text into name/type as-written.
func paramFrom(node ts.Node, src []byte) schema.Param {
	if node.Type() == "identifier" {
		return schema.Param{Name: node.Content(src)}
	}
	txt := node.Content(src)
	// Drop any default value.
	if idx := strings.Index(txt, "="); idx >= 0 {
		txt = txt[:idx]
	}
	name, typ := txt, ""
	if idx := strings.Index(txt, ":"); idx >= 0 {
		name = txt[:idx]
		typ = strings.TrimSpace(txt[idx+1:])
	}
	return schema.Param{Name: strings.TrimSpace(name), Type: typ}
}

// returns extracts the return annotation as a single as-written result.
func returns(node ts.Node, src []byte) []schema.Param {
	rt, ok := node.ChildByFieldName("return_type")
	if !ok {
		return nil
	}
	return []schema.Param{{Type: rt.Content(src)}}
}

// bodyDoc returns the docstring (first string statement) of a definition body.
func bodyDoc(node ts.Node, src []byte) schema.Doc {
	body, ok := node.ChildByFieldName("body")
	if !ok || body.NamedChildCount() == 0 {
		return schema.Doc{}
	}
	// A leading comment inside the body pushes the docstring off index 0.
	idx := firstNonCommentIndex(body)
	if idx >= body.NamedChildCount() {
		return schema.Doc{}
	}
	first := body.NamedChild(idx)
	if first.Type() == "string" {
		return schema.Doc{Raw: stringText(first, src), Format: "docstring"}
	}
	if first.Type() == "expression_statement" {
		if s := firstNamedString(first); !s.IsNull() {
			return schema.Doc{Raw: stringText(s, src), Format: "docstring"}
		}
	}
	return schema.Doc{}
}

// firstNonCommentIndex returns the named-child index of the first statement
// that is not a `comment`. If every named child is a comment (or there are
// none) it returns NamedChildCount(). Leading license/header comments must not
// hide a following docstring.
func firstNonCommentIndex(node ts.Node) int {
	n := node.NamedChildCount()
	for i := 0; i < n; i++ {
		if node.NamedChild(i).Type() != "comment" {
			return i
		}
	}
	return n
}

// firstNamedString returns the first named child of type string, or a null node.
func firstNamedString(node ts.Node) ts.Node {
	for i := 0; i < node.NamedChildCount(); i++ {
		c := node.NamedChild(i)
		if c.Type() == "string" {
			return c
		}
	}
	return ts.Node{}
}

// stringText returns the textual content of a string node, preferring its
// string_content child and otherwise trimming surrounding quotes.
func stringText(node ts.Node, src []byte) string {
	var parts []string
	for i := 0; i < node.NamedChildCount(); i++ {
		c := node.NamedChild(i)
		if c.Type() == "string_content" {
			parts = append(parts, c.Content(src))
		}
	}
	if len(parts) > 0 {
		return strings.Join(parts, "")
	}
	return trimQuotes(node.Content(src))
}

func trimQuotes(s string) string {
	s = strings.TrimSpace(s)
	for _, q := range []string{`"""`, `'''`, `"`, `'`} {
		if strings.HasPrefix(s, q) && strings.HasSuffix(s, q) && len(s) >= 2*len(q) {
			return s[len(q) : len(s)-len(q)]
		}
	}
	return s
}

// pyVisibility applies the underscore rule: a leading underscore means
// unexported, except for dunder names (__x__) which are exported.
func pyVisibility(name string) string {
	if !strings.HasPrefix(name, "_") {
		return "exported"
	}
	if isDunder(name) {
		return "exported"
	}
	return "unexported"
}

func isDunder(name string) bool {
	return len(name) > 4 && strings.HasPrefix(name, "__") && strings.HasSuffix(name, "__")
}

// fieldText returns the text of a node's field child, or "" if absent.
func fieldText(node ts.Node, field string, src []byte) string {
	if c, ok := node.ChildByFieldName(field); ok {
		return c.Content(src)
	}
	return ""
}

func locationOf(node ts.Node, relFile string) schema.Location {
	return schema.Location{
		File:    relFile,
		Line:    node.StartLine(),
		Col:     node.StartCol(),
		EndLine: node.EndLine(),
	}
}
