// Code generated by goplus from diff.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package diff compares two assayxport manifests and models the
// assayxport-diff JSON document: exact identity-based drift for sources that
// share history, and ranked similarity candidates for unrelated codebases.
// Wire types keep the same discipline as the manifest schema: deterministic
// ordering, no timestamps, no filesystem locations -- sources appear only
// under their labels.
package diff

import "goforge.dev/assayxport/internal/schema"

// SchemaVersion is the schema_version value of every diff document.
const SchemaVersion = "assayxport-diff/1"

// Doc is the root of assayxport-diff.json. Exactly one of Drift and
// Correspond is set, matching Mode. A diff must be reproducible from its own
// header: Sources records what was compared (resolved commits, extraction
// depth per language) and Options records every flag that shaped the result.
type Doc struct {
	SchemaVersion  string   `json:"schema_version"`
	Tool           string   `json:"tool"`
	Mode           string   `json:"mode"`             // "drift" | "correspond"
	ModeSelectedBy string   `json:"mode_selected_by"` // "auto" | "flag"
	Sources        []Source `json:"sources"`          // exactly two, argument order
	Options        Options  `json:"options"`

	Drift      *Drift      `json:"drift,omitempty"`
	Correspond *Correspond `json:"correspond,omitempty"`
}

// Source is one compared source as it appears in the header. The resolved
// commit is the reproducible identity of a git source; the ref as typed is
// deliberately absent, so two specs naming the same commit produce
// byte-identical output.
type Source struct {
	Label     string   `json:"label"`
	Kind      string   `json:"kind"`             // "dir" | "local-git" | "remote-git"
	Commit    string   `json:"commit,omitempty"` // full SHA for git sources
	Languages []string `json:"languages"`
	// Extraction maps each contributing language to the depth of truth its
	// extractor provides: "semantic" (Go) or "syntactic" (tree-sitter).
	Extraction map[string]string `json:"extraction"`
}

// Options records the flags that affected the result. Only the fields
// relevant to the chosen mode are populated; pointers keep a deliberate
// false/zero distinguishable from "not applicable".
type Options struct {
	Lang             []string `json:"lang,omitempty"` // languages restricted via --lang
	IgnoreParamNames *bool    `json:"ignore_param_names,omitempty"`
	MinLines         *int     `json:"min_lines,omitempty"`
	MinScore         *int     `json:"min_score,omitempty"`
	Top              *int     `json:"top,omitempty"`
	Weights          *Weights `json:"weights,omitempty"`
	SameLanguageOnly *bool    `json:"same_language_only,omitempty"`
}

// Weights are the fixed combined-score weights of correspond mode.
type Weights struct {
	Signature int `json:"signature"`
	Name      int `json:"name"`
	Calls     int `json:"calls"`
}

// Drift is the exact, identity-matched comparison of two related sources.
type Drift struct {
	Packages DriftPackages `json:"packages"`
	Summary  DriftSummary  `json:"summary"`
}

// DriftPackages lists package-level fate. A package added or removed whole
// does not re-list its symbols; the manifests hold them.
type DriftPackages struct {
	Added   []PackageStub  `json:"added"`
	Removed []PackageStub  `json:"removed"`
	Changed []PackageDrift `json:"changed"`
}

// PackageStub identifies a whole added or removed package.
type PackageStub struct {
	ID          string `json:"id"`
	SymbolCount int    `json:"symbol_count"`
}

// PackageDrift is one surviving package with symbol-level differences.
// RenamedFromID is set when the match was by repo-relative path rather than
// id (e.g. a fork that renamed its module), which is a visibly weaker match.
type PackageDrift struct {
	ID            string       `json:"id"`
	RenamedFromID string       `json:"renamed_from_id,omitempty"`
	Symbols       SymbolDrifts `json:"symbols"`
}

// SymbolDrifts partitions a package's symbols by fate.
type SymbolDrifts struct {
	Added   []string      `json:"added"`
	Removed []string      `json:"removed"`
	Changed []SymbolDrift `json:"changed"`
}

// SymbolDrift is one symbol whose declaration changed. Changes lists the
// change kinds in canonical order (kind, signature, visibility, entrypoint,
// complexity, calls); the matching detail field is set for each listed kind.
type SymbolDrift struct {
	ID         string        `json:"id"`
	Changes    []string      `json:"changes"`
	Kind       *AB           `json:"kind,omitempty"`
	Signature  *AB           `json:"signature,omitempty"`
	Visibility *AB           `json:"visibility,omitempty"`
	Entrypoint *ABBool       `json:"entrypoint,omitempty"`
	Complexity *ABComplexity `json:"complexity,omitempty"`
	Calls      *CallsDrift   `json:"calls,omitempty"`
}

// AB is a before/after pair of rendered values.
type AB struct {
	A string `json:"a"`
	B string `json:"b"`
}

// ABBool is a before/after pair of booleans.
type ABBool struct {
	A bool `json:"a"`
	B bool `json:"b"`
}

// ABComplexity is a before/after pair of complexity estimates.
type ABComplexity struct {
	A schema.Complexity `json:"a"`
	B schema.Complexity `json:"b"`
}

// CallsDrift lists call edges present on one side only, keyed by resolved
// target and resolution kind.
type CallsDrift struct {
	Added   []CallStub `json:"added"`
	Removed []CallStub `json:"removed"`
}

// CallStub identifies one call edge.
type CallStub struct {
	Target string `json:"target"`
	Kind   string `json:"kind"`
}

// DriftSummary is the roll-up used by --exit-code and the text renderer.
type DriftSummary struct {
	PackagesAdded   int `json:"packages_added"`
	PackagesRemoved int `json:"packages_removed"`
	SymbolsAdded    int `json:"symbols_added"`
	SymbolsRemoved  int `json:"symbols_removed"`
	SymbolsChanged  int `json:"symbols_changed"`
}

// HasDifferences reports whether the drift found anything at all.
func (d *Drift) HasDifferences() bool {
	s := d.Summary
	return s.PackagesAdded > 0 || s.PackagesRemoved > 0 ||
		s.SymbolsAdded > 0 || s.SymbolsRemoved > 0 || s.SymbolsChanged > 0
}

// Correspond is the ranked-candidate comparison of two unrelated sources.
// Candidates are proposals for human review, never assertions of
// equivalence.
type Correspond struct {
	Eligible   EligibleCounts `json:"eligible"`
	Candidates []Candidate    `json:"candidates"`
}

// EligibleCounts reports how many symbols per side passed the triviality
// gate and so participated in matching.
type EligibleCounts struct {
	A int `json:"a"`
	B int `json:"b"`
}

// Candidate is one proposed pair, with its per-signal scores reported
// separately so a reviewer can see why it was proposed.
type Candidate struct {
	A            CandidateSide `json:"a"`
	B            CandidateSide `json:"b"`
	SameLanguage bool          `json:"same_language"`
	Scores       Scores        `json:"scores"`
}

// CandidateSide locates one symbol via the manifest's existing
// "<package-id>#<symbol-id>" link syntax.
type CandidateSide struct {
	Ref      string `json:"ref"`
	Language string `json:"language"`
	Name     string `json:"name"`
	Lines    int    `json:"lines"`
}

// Scores are integers on a fixed 0-1000 scale; floats never appear in the
// document. Calls is null when either side has no call data -- an absent
// signal, not zero overlap.
type Scores struct {
	Signature int  `json:"signature"`
	Name      int  `json:"name"`
	Calls     *int `json:"calls"`
	Combined  int  `json:"combined"`
}

// HasCandidates reports whether any pair met the reporting threshold.
func (c *Correspond) HasCandidates() bool { return len(c.Candidates) > 0 }
