// Code generated by goplus from extract.gp. DO NOT EDIT.
//goplus:v v0.16.1

// Package extract defines the language-agnostic extractor contract.
package extract

import "goforge.dev/assayxport/internal/schema"

// Extractor turns a source tree into a stable list of packages.
type Extractor interface {
	// Language reports the language id this extractor handles, e.g. "go".
	Language() string
	// Extract loads every package under root and returns them sorted by ID.
	Extract(root string) ([]schema.Package, error)
}

// StreamExtractor is an optional extension for languages that can emit packages
// incrementally. When an extractor implements it, the pipeline streams each
// package to disk and releases it, so a huge tree's peak memory is the index
// metadata plus a few in-flight packages rather than every symbol at once.
//
// emit is called once per package, in an unspecified order and possibly
// concurrently (the extractor may parse across a worker pool); the caller's emit
// is responsible for its own synchronization. A non-nil error from emit, or any
// extraction error, aborts the stream. Order-independence is fine because the
// downstream writer sorts by package id.
type StreamExtractor interface {
	Extractor
	ExtractStream(root string, emit func(schema.Package) error) error
}

// SkeletonExtractor is an optional extension for languages that can enumerate
// their packages cheaply, without parsing symbols -- typically straight from the
// file tree. `ax serve` uses it to publish a structural skeleton (every package's
// id/path/name, no symbols) the instant the server starts, so the explorer renders
// the whole package tree in ~1s while the real symbol extraction streams in
// behind it.
//
// The returned packages must carry the SAME ids the extractor's Extract/
// ExtractStream will later produce (both should derive identity from the same file
// walk), so each streamed package's symbols map back onto its skeleton entry.
// Symbols is left nil; only ID, Language, Path, Name, and Level are set.
type SkeletonExtractor interface {
	Extractor
	Skeleton(root string) ([]schema.Package, error)
}

// DemandExtractor is an optional extension for languages whose per-package parse
// is independent, so `ax serve` can drive extraction in an order it chooses --
// parsing the packages a client is actually looking at first -- instead of a
// fixed file walk. It enumerates cheaply via Skeleton, then parses one enumerated
// package at a time via ExtractOne; the serve layer owns the scheduling.
//
// pkg is a skeleton package returned by Skeleton (identity only); ExtractOne
// parses its single source unit and returns the full package. Language loaders
// with a whole-module parse (Go's type-load) do not implement this and stream in
// their fixed order instead.
type DemandExtractor interface {
	SkeletonExtractor
	ExtractOne(root string, pkg schema.Package) (schema.Package, error)
}
