// Code generated by goplus from progress.gp. DO NOT EDIT.
//goplus:v v0.16.1

package extract

import "goforge.dev/assayxport/internal/schema"

//goplus:enum PackagePhase
type PackagePhase interface{ isPackagePhase() }

//goplus:variant (PackagePhase) DiscoveredPhase
type DiscoveredPhase struct{}

func (DiscoveredPhase) isPackagePhase() {}

//goplus:variant (PackagePhase) ScheduledPhase
type ScheduledPhase struct{}

func (ScheduledPhase) isPackagePhase() {}

//goplus:variant (PackagePhase) ExtractingPhase
type ExtractingPhase struct{}

func (ExtractingPhase) isPackagePhase() {}

//goplus:variant (PackagePhase) ReadyPhase
type ReadyPhase struct{}

func (ReadyPhase) isPackagePhase() {}

//goplus:variant (PackagePhase) FailedPhase
type FailedPhase struct{}

func (FailedPhase) isPackagePhase() {}

// PackagePhaseCases selects one handler per PackagePhase variant for Fold.
type PackagePhaseCases[R any] struct {
	DiscoveredPhase func() R
	ScheduledPhase  func() R
	ExtractingPhase func() R
	ReadyPhase      func() R
	FailedPhase     func() R
}

// Fold reduces PackagePhase by one-level case analysis.
func Fold[R any](p PackagePhase, cs PackagePhaseCases[R]) R {
	switch any(p).(type) {
	case DiscoveredPhase:
		return cs.DiscoveredPhase()
	case ScheduledPhase:
		return cs.ScheduledPhase()
	case ExtractingPhase:
		return cs.ExtractingPhase()
	case ReadyPhase:
		return cs.ReadyPhase()
	case FailedPhase:
		return cs.FailedPhase()
	default:
		panic("goplus: impossible enum value in Fold")
	}
}

// PackagePhaseEqOverrides carries optional per-variant hooks for PackagePhaseEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type PackagePhaseEqOverrides struct {
	DiscoveredPhase func(x, y DiscoveredPhase) (eq, handled bool)
	ScheduledPhase  func(x, y ScheduledPhase) (eq, handled bool)
	ExtractingPhase func(x, y ExtractingPhase) (eq, handled bool)
	ReadyPhase      func(x, y ReadyPhase) (eq, handled bool)
	FailedPhase     func(x, y FailedPhase) (eq, handled bool)
}

// PackagePhaseEqualWith reports structural equality of a and b under ov.
func PackagePhaseEqualWith(a, b PackagePhase, ov PackagePhaseEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case DiscoveredPhase:
		y, ok := any(b).(DiscoveredPhase)
		if !ok {
			return false
		}
		if ov.DiscoveredPhase != nil {
			if eq, handled := ov.DiscoveredPhase(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ScheduledPhase:
		y, ok := any(b).(ScheduledPhase)
		if !ok {
			return false
		}
		if ov.ScheduledPhase != nil {
			if eq, handled := ov.ScheduledPhase(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ExtractingPhase:
		y, ok := any(b).(ExtractingPhase)
		if !ok {
			return false
		}
		if ov.ExtractingPhase != nil {
			if eq, handled := ov.ExtractingPhase(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ReadyPhase:
		y, ok := any(b).(ReadyPhase)
		if !ok {
			return false
		}
		if ov.ReadyPhase != nil {
			if eq, handled := ov.ReadyPhase(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case FailedPhase:
		y, ok := any(b).(FailedPhase)
		if !ok {
			return false
		}
		if ov.FailedPhase != nil {
			if eq, handled := ov.FailedPhase(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// PackagePhaseEqual reports structural equality of a and b.
func PackagePhaseEqual(a, b PackagePhase) bool {
	return PackagePhaseEqualWith(a, b, PackagePhaseEqOverrides{})
}

// ProgressivePackage is indexed by the only phase in which its payload is
// valid. Indices erase from generated Go but prevent invalid Go+ transitions.
//
//goplus:enum ProgressivePackage[p PackagePhase]
//goplus:derive off
type ProgressivePackage interface{ isProgressivePackage() }

//goplus:variant (ProgressivePackage) DiscoveredPackage(pkg schema.Package) ProgressivePackage[DiscoveredPhase]
type DiscoveredPackage struct {
	Pkg schema.Package
}

func (DiscoveredPackage) isProgressivePackage() {}

//goplus:variant (ProgressivePackage) ScheduledPackage(pkg schema.Package) ProgressivePackage[ScheduledPhase]
type ScheduledPackage struct {
	Pkg schema.Package
}

func (ScheduledPackage) isProgressivePackage() {}

//goplus:variant (ProgressivePackage) ExtractingPackage(pkg schema.Package) ProgressivePackage[ExtractingPhase]
type ExtractingPackage struct {
	Pkg schema.Package
}

func (ExtractingPackage) isProgressivePackage() {}

//goplus:variant (ProgressivePackage) ReadyPackage(pkg schema.Package) ProgressivePackage[ReadyPhase]
type ReadyPackage struct {
	Pkg schema.Package
}

func (ReadyPackage) isProgressivePackage() {}

//goplus:variant (ProgressivePackage) FailedPackage(pkg schema.Package, cause error) ProgressivePackage[FailedPhase]
type FailedPackage struct {
	Pkg   schema.Package
	Cause error
}

func (FailedPackage) isProgressivePackage() {}

func Discover(pkg schema.Package) ProgressivePackage { return DiscoveredPackage{Pkg: pkg} }

func Schedule(pkg ProgressivePackage) ProgressivePackage {
	switch __gp_m0 := any(pkg).(type) {
	case DiscoveredPackage:
		value := __gp_m0.Pkg
		return ScheduledPackage{Pkg: value}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func BeginExtraction(pkg ProgressivePackage) ProgressivePackage {
	switch __gp_m1 := any(pkg).(type) {
	case ScheduledPackage:
		value := __gp_m1.Pkg
		return ExtractingPackage{Pkg: value}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func FinishExtraction(_ ProgressivePackage, full schema.Package) ProgressivePackage {
	return ReadyPackage{Pkg: full}
}

func FailExtraction(pkg ProgressivePackage, cause error) ProgressivePackage {
	switch __gp_m2 := any(pkg).(type) {
	case ExtractingPackage:
		value := __gp_m2.Pkg
		return FailedPackage{Pkg: value, Cause: cause}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func ScheduledValue(pkg ProgressivePackage) schema.Package {
	switch __gp_m3 := any(pkg).(type) {
	case ScheduledPackage:
		value := __gp_m3.Pkg
		return value
	default:
		panic("goplus: impossible enum value in match")
	}
}

func ExtractingValue(pkg ProgressivePackage) schema.Package {
	switch __gp_m4 := any(pkg).(type) {
	case ExtractingPackage:
		value := __gp_m4.Pkg
		return value
	default:
		panic("goplus: impossible enum value in match")
	}
}

func ReadyValue(pkg ProgressivePackage) schema.Package {
	switch __gp_m5 := any(pkg).(type) {
	case ReadyPackage:
		value := __gp_m5.Pkg
		return value
	default:
		panic("goplus: impossible enum value in match")
	}
}
