// Code generated by goplus from semantics.gp. DO NOT EDIT.
//goplus:v v0.16.1

package extract

import (
	"errors"
	"fmt"

	"goforge.dev/assayxport/internal/schema"
)

// ExtractionFailure attributes failure to the extractor that produced it.
type ExtractionFailure struct {
	Language string
	Cause    error
}

// ExtractionOutcome makes complete, useful partial, and fatal extraction
// mutually exclusive instead of coordinating warnings with a nil error.
//
//goplus:enum ExtractionOutcome
//goplus:derive off
type ExtractionOutcome interface{ isExtractionOutcome() }

//goplus:variant (ExtractionOutcome) ExtractionComplete(packages []schema.Package, languages []string)
type ExtractionComplete struct {
	Packages  []schema.Package
	Languages []string
}

func (ExtractionComplete) isExtractionOutcome() {}

//goplus:variant (ExtractionOutcome) ExtractionPartial(packages []schema.Package, languages []string, warnings []ExtractionFailure)
type ExtractionPartial struct {
	Packages  []schema.Package
	Languages []string
	Warnings  []ExtractionFailure
}

func (ExtractionPartial) isExtractionOutcome() {}

//goplus:variant (ExtractionOutcome) ExtractionFailed(failures []ExtractionFailure)
type ExtractionFailed struct {
	Failures []ExtractionFailure
}

func (ExtractionFailed) isExtractionOutcome() {}

// Capability classes let generic pipeline code ask only for the extraction
// mode it consumes. Interface adapters below keep ordinary Go extractors valid.
//
//goplus:class StreamingCapability[E any]
type StreamingCapability[E any] struct {
	Stream func(e E, root string, emit func(schema.Package) error) error
}

//goplus:class SkeletonCapability[E any]
type SkeletonCapability[E any] struct {
	Enumerate func(e E, root string) ([]schema.Package, error)
	Identity  func(e E, p schema.Package) string
}

//goplus:law (SkeletonCapability[E]) IdentityIsStable(e E, p schema.Package)
func (m SkeletonCapability[E]) LawIdentityIsStable(e E, p schema.Package) bool {
	return m.Identity(e, p) == p.ID
}

//goplus:class DemandCapability[E any] embeds(SkeletonCapability)
type DemandCapability[E any] struct {
	Enumerate func(e E, root string) ([]schema.Package, error)
	Identity  func(e E, p schema.Package) string
	One       func(e E, root string, p schema.Package) (schema.Package, error)
}

//goplus:instance StreamExtractorCapability StreamingCapability[StreamExtractor]
var StreamExtractorCapability = func() StreamingCapability[StreamExtractor] {
	w := &StreamingCapability[StreamExtractor]{
		Stream: func(e StreamExtractor, root string, emit func(schema.Package) error) error {
			return e.ExtractStream(root, emit)
		},
	}
	return *w
}()

//goplus:instance SkeletonExtractorCapability SkeletonCapability[SkeletonExtractor]
//goplus:laws off
var SkeletonExtractorCapability = func() SkeletonCapability[SkeletonExtractor] {
	w := &SkeletonCapability[SkeletonExtractor]{
		Enumerate: func(e SkeletonExtractor, root string) ([]schema.Package, error) { return e.Skeleton(root) },
		Identity:  func(_ SkeletonExtractor, p schema.Package) string { return p.ID },
	}
	return *w
}()

//goplus:instance DemandExtractorCapability DemandCapability[DemandExtractor]
//goplus:laws off
var DemandExtractorCapability = func() DemandCapability[DemandExtractor] {
	w := &DemandCapability[DemandExtractor]{
		Enumerate: func(e DemandExtractor, root string) ([]schema.Package, error) { return e.Skeleton(root) },
		Identity:  func(_ DemandExtractor, p schema.Package) string { return p.ID },
		One: func(e DemandExtractor, root string, p schema.Package) (schema.Package, error) {
			return e.ExtractOne(root, p)
		},
	}
	return *w
}()

// IdentityWitness keeps the capability identity law executable without asking
// a property generator to manufacture interface implementations.
type IdentityWitness struct{}

//goplus:instance PackageIdentityLaw SkeletonCapability[IdentityWitness]
var PackageIdentityLaw = func() SkeletonCapability[IdentityWitness] {
	w := &SkeletonCapability[IdentityWitness]{
		Enumerate: func(_ IdentityWitness, _ string) ([]schema.Package, error) { return nil, nil },
		Identity:  func(_ IdentityWitness, p schema.Package) string { return p.ID },
	}
	return *w
}()

//goplus:fn StreamWith[E StreamingCapability]
func StreamWith[E any](streamingCapability StreamingCapability[E], e E, root string, emit func(schema.Package) error) error {
	return streamingCapability.Stream(e, root, emit)
}

//goplus:fn SkeletonWith[E SkeletonCapability]
func SkeletonWith[E any](skeletonCapability SkeletonCapability[E], e E, root string) ([]schema.Package, error) {
	return skeletonCapability.Enumerate(e, root)
}

//goplus:fn ExtractOneWith[E DemandCapability]
func ExtractOneWith[E any](demandCapability DemandCapability[E], e E, root string, p schema.Package) (schema.Package, error) {
	return demandCapability.One(e, root, p)
}

// LegacyOutcome is the one compatibility projection for callers that still
// consume parallel Go return values. The match is exhaustive in Go+.
func LegacyOutcome(outcome ExtractionOutcome) ([]schema.Package, []string, []error, error) {
	switch __gp_m0 := any(outcome).(type) {
	case ExtractionComplete:
		packages := __gp_m0.Packages
		languages := __gp_m0.Languages
		return packages, languages, nil, nil
	case ExtractionPartial:
		packages := __gp_m0.Packages
		languages := __gp_m0.Languages
		warnings := __gp_m0.Warnings
		errList := make([]error, len(warnings))
		for i, warning := range warnings {
			errList[i] = fmt.Errorf("%s: %w", warning.Language, warning.Cause)
		}
		return packages, languages, errList, nil
	case ExtractionFailed:
		failures := __gp_m0.Failures
		errList := make([]error, len(failures))
		for i, failure := range failures {
			errList[i] = fmt.Errorf("%s: %w", failure.Language, failure.Cause)
		}
		return nil, nil, nil, errors.Join(errList...)
	default:
		panic("goplus: impossible enum value in match")
	}
}

// AsSkeletonCapability views the DemandCapability witness as its SkeletonCapability part.
func (m DemandCapability[E]) AsSkeletonCapability() SkeletonCapability[E] {
	return SkeletonCapability[E]{Enumerate: m.Enumerate, Identity: m.Identity}
}
