// Code generated by goplus from semantics.gp. DO NOT EDIT.
//goplus:v v0.16.1

package extract

import (
	"testing"

	"goforge.dev/assayxport/internal/schema"
	"pgregory.net/rapid"
)

func TestPackageIdentityLawLaws(t *testing.T) {
	t.Run("SkeletonCapability.IdentityIsStable", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			e := rapid.Make[IdentityWitness]().Draw(rt, "e")
			p := rapid.Make[schema.Package]().Draw(rt, "p")
			if !PackageIdentityLaw.LawIdentityIsStable(e, p) {
				rt.Fatalf("law IdentityIsStable violated: e=%v p=%v", e, p)
			}
		})
	})
}
