// Code generated by goplus from ts.gp. DO NOT EDIT.
//goplus:v v0.15.0

// Package ts is assayxport's in-house tree-sitter layer. It exposes a small,
// stable API for parsing source code into syntax trees and walking them.
//
// The third-party tree-sitter implementation is referenced ONLY in this file,
// so downstream packages depend on this API rather than on the library. The
// backing runtime is github.com/odvcencio/gotreesitter, a pure-Go (cgo-free)
// tree-sitter runtime that ships built-in language grammars, including Python.
package ts

import (
	"fmt"
	"sync"

	gts "github.com/odvcencio/gotreesitter"
	"github.com/odvcencio/gotreesitter/grammars"
)

// Language selects a grammar.
type Language int

const (
	// Python selects the tree-sitter Python grammar.
	Python Language = iota
	// Java selects the tree-sitter Java grammar.
	Java
	// TypeScript selects the tree-sitter TypeScript grammar (.ts/.mts/.cts).
	TypeScript
	// TSX selects the tree-sitter TSX grammar (TypeScript + JSX, .tsx).
	TSX
	// JavaScript selects the tree-sitter JavaScript grammar (handles JSX, .js/.jsx/.mjs/.cjs).
	JavaScript
)

// pythonLang holds the lazily-initialized Python grammar. Loading the grammar
// (decoding the embedded grammar blob) is a one-time cost done under sync.Once.
var (
	pythonOnce sync.Once
	pythonLang *gts.Language
)

func python() *gts.Language {
	pythonOnce.Do(func() {
		pythonLang = grammars.PythonLanguage()
	})
	return pythonLang
}

// javaLang holds the lazily-initialized Java grammar, decoded once under
// sync.Once (mirrors python()).
var (
	javaOnce sync.Once
	javaLang *gts.Language
)

func java() *gts.Language {
	javaOnce.Do(func() {
		javaLang = grammars.JavaLanguage()
	})
	return javaLang
}

// The TypeScript family: three related grammars, each decoded once. .ts uses the
// plain TypeScript grammar; .tsx needs the TSX grammar (JSX changes parsing);
// .js/.jsx use the JavaScript grammar (which also accepts JSX).
var (
	tsOnce  sync.Once
	tsLang  *gts.Language
	tsxOnce sync.Once
	tsxLang *gts.Language
	jsOnce  sync.Once
	jsLang  *gts.Language
)

func typescript() *gts.Language {
	tsOnce.Do(func() { tsLang = grammars.TypescriptLanguage() })
	return tsLang
}

func tsx() *gts.Language {
	tsxOnce.Do(func() { tsxLang = grammars.TsxLanguage() })
	return tsxLang
}

func javascript() *gts.Language {
	jsOnce.Do(func() { jsLang = grammars.JavascriptLanguage() })
	return jsLang
}

// Tree is a parsed syntax tree. It keeps the source bytes and grammar alongside
// the root node so nodes can slice text and resolve field names.
type Tree struct {
	tree *gts.Tree
	lang *gts.Language
	src  []byte
}

// Node is a lightweight handle into a Tree. A zero Node (or one wrapping a nil
// underlying node) reports IsNull() == true.
type Node struct {
	n    *gts.Node
	lang *gts.Language
}

// Parse parses src under lang. It is deterministic for equal input. Parse is
// safe for sequential use; the underlying parser is created per call and not
// shared across goroutines.
func Parse(lang Language, src []byte) (*Tree, error) {
	var g *gts.Language
	switch lang {
	case Python:
		g = python()
	case Java:
		g = java()
	case TypeScript:
		g = typescript()
	case TSX:
		g = tsx()
	case JavaScript:
		g = javascript()
	default:
		return nil, fmt.Errorf("ts: unsupported language %d", int(lang))
	}
	if g == nil {
		return nil, fmt.Errorf("ts: grammar unavailable for language %d", int(lang))
	}

	p := gts.NewParser(g)
	tree, err := p.Parse(src)
	if err != nil {
		return nil, fmt.Errorf("ts: parse failed: %w", err)
	}
	if tree == nil {
		return nil, fmt.Errorf("ts: parse produced no tree")
	}
	return &Tree{tree: tree, lang: g, src: src}, nil
}

// Root returns the root node of the tree.
func (t *Tree) Root() Node {
	return Node{n: t.tree.RootNode(), lang: t.lang}
}

// IsNull reports whether the node is absent (e.g. a missing field child).
func (n Node) IsNull() bool { return n.n == nil }

// Type returns the tree-sitter node type, e.g. "function_definition".
func (n Node) Type() string {
	if n.n == nil {
		return ""
	}
	return n.n.Type(n.lang)
}

// NamedChildCount returns the number of named children.
func (n Node) NamedChildCount() int {
	if n.n == nil {
		return 0
	}
	return n.n.NamedChildCount()
}

// NamedChild returns the i-th named child. If i is out of range the returned
// Node reports IsNull() == true.
func (n Node) NamedChild(i int) Node {
	if n.n == nil {
		return Node{lang: n.lang}
	}
	return Node{n: n.n.NamedChild(i), lang: n.lang}
}

// NamedChildren returns all named children in order, materializing the child
// list in a single O(children) pass.
//
// Prefer this over a `for i := 0; i < n.NamedChildCount(); i++ { n.NamedChild(i) }`
// loop: in the backend both NamedChildCount and NamedChild(i) walk the child
// list from the start, so an index loop is O(children^2) per node and, applied
// recursively over a subtree, blows up on large source files (a ~900 KB file
// froze the whole assay). Iterating the materialized slice is linear.
func (n Node) NamedChildren() []Node {
	if n.n == nil {
		return nil
	}
	kids := n.n.Children()
	out := make([]Node, 0, len(kids))
	for _, c := range kids {
		if c != nil && c.IsNamed() {
			out = append(out, Node{n: c, lang: n.lang})
		}
	}
	return out
}

// ChildByFieldName returns the child under field f (e.g. "name", "parameters",
// "body", "return_type") and whether it was found.
func (n Node) ChildByFieldName(f string) (Node, bool) {
	if n.n == nil {
		return Node{lang: n.lang}, false
	}
	c := n.n.ChildByFieldName(f, n.lang)
	if c == nil {
		return Node{lang: n.lang}, false
	}
	return Node{n: c, lang: n.lang}, true
}

// StartLine returns the 1-based line of the node's start.
func (n Node) StartLine() int {
	if n.n == nil {
		return 0
	}
	return int(n.n.StartPoint().Row) + 1
}

// StartCol returns the 1-based column of the node's start.
func (n Node) StartCol() int {
	if n.n == nil {
		return 0
	}
	return int(n.n.StartPoint().Column) + 1
}

// EndLine returns the 1-based line of the node's end.
func (n Node) EndLine() int {
	if n.n == nil {
		return 0
	}
	return int(n.n.EndPoint().Row) + 1
}

// Content returns the exact source slice spanning this node.
func (n Node) Content(src []byte) string {
	if n.n == nil {
		return ""
	}
	start := int(n.n.StartByte())
	end := int(n.n.EndByte())
	if start < 0 || end > len(src) || start > end {
		return ""
	}
	return string(src[start:end])
}
