// Code generated by goplus from schema.gp. DO NOT EDIT.
//goplus:v v0.16.1

// Package schema defines the assayxport manifest types and their stable JSON
// encoding. Version is the schema_version string emitted in every artifact.
package schema

import (
	"sort"
	"strconv"
	"strings"
)

// Version is the schema_version value written into every index and shard.
// "2" added the per-symbol call graph (Symbol.Calls); the change is additive.
const Version = "2"

// Index is the root manifest written to assayxport.json.
type Index struct {
	SchemaVersion string         `json:"schema_version"`
	Tool          string         `json:"tool"`
	Languages     []string       `json:"languages"`
	Root          string         `json:"root"`
	Module        string         `json:"module,omitempty"`
	Packages      []PackageEntry `json:"packages"`
}

// PackageEntry is one package's summary in the index, pointing at its shard.
type PackageEntry struct {
	ID              string      `json:"id"`
	Language        string      `json:"language"`
	Path            string      `json:"path"`
	Name            string      `json:"name"`
	Doc             string      `json:"doc"`
	Level           string      `json:"level,omitempty"`
	Members         []string    `json:"members,omitempty"`
	IsEntrypoint    bool        `json:"is_entrypoint,omitempty"`
	Invocation      *Invocation `json:"invocation,omitempty"`
	SymbolCount     int         `json:"symbol_count"`
	EntrypointCount int         `json:"entrypoint_count"`
	Shard           string      `json:"shard"`
}

// Shard is one package's full symbol listing, written to .assayxport/<dir>.json.
type Shard struct {
	SchemaVersion string      `json:"schema_version"`
	Package       PackageInfo `json:"package"`
	Symbols       []Symbol    `json:"symbols"`
}

// PackageInfo identifies a package inside its shard.
type PackageInfo struct {
	ID           string      `json:"id"`
	Language     string      `json:"language"`
	Path         string      `json:"path"`
	Name         string      `json:"name"`
	Doc          string      `json:"doc"`
	Level        string      `json:"level,omitempty"`
	Members      []string    `json:"members,omitempty"`
	IsEntrypoint bool        `json:"is_entrypoint,omitempty"`
	Invocation   *Invocation `json:"invocation,omitempty"`
}

// Package is the in-memory result an Extractor returns for one package.
// It carries everything needed to build both the index entry and the shard.
type Package struct {
	ID           string
	Language     string
	Path         string
	Name         string
	Doc          string
	Level        string
	Members      []string
	IsEntrypoint bool
	Invocation   *Invocation
	Symbols      []Symbol
}

// Symbol is one named declaration. Signature is set only for func/method;
// Type is set for const/var/field; TypeKind+Underlying are set for type.
type Symbol struct {
	ID              string      `json:"id"`
	Name            string      `json:"name"`
	Kind            string      `json:"kind"`
	Visibility      string      `json:"visibility"`
	VisibilityIdiom string      `json:"visibility_idiom"`
	Location        Location    `json:"location"`
	Owner           string      `json:"owner,omitempty"`
	Doc             Doc         `json:"doc"`
	IsEntrypoint    bool        `json:"is_entrypoint"`
	Invocation      *Invocation `json:"invocation,omitempty"`
	Complexity      Complexity  `json:"complexity"`

	Signature  *Signature `json:"signature,omitempty"`
	TypeKind   string     `json:"type_kind,omitempty"`
	Underlying string     `json:"underlying,omitempty"`
	Type       string     `json:"type,omitempty"`

	InAll       *bool    `json:"in_all,omitempty"`
	Decorators  []string `json:"decorators,omitempty"`
	Annotations []string `json:"annotations,omitempty"`

	// Concerns are things that "work" but don't match up: type-soundness escape
	// hatches and off-standard constructs a symbol carries (e.g. "any",
	// "as-any", "non-null-assertion", "ts-ignore", "untyped-param",
	// "untyped-return", "loose-equality"). Surfaced by the explorer so a symbol
	// that compiles/runs but forfeits its type contract reads at a glance.
	Concerns []string `json:"concerns,omitempty"`

	Calls []Call `json:"calls,omitempty"`
}

// Signature describes a func or method.
type Signature struct {
	Params     []Param     `json:"params"`
	Returns    []Param     `json:"returns"`
	TypeParams []TypeParam `json:"type_params"`
	Receiver   *Param      `json:"receiver,omitempty"`
	Variadic   bool        `json:"variadic"`
	Modifiers  []string    `json:"modifiers,omitempty"`
}

// Param is one parameter, result, or receiver. Name may be empty.
type Param struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// TypeParam is one generic type parameter.
type TypeParam struct {
	Name       string `json:"name"`
	Constraint string `json:"constraint"`
}

// Location is a 1-based source position with a relative POSIX file path.
type Location struct {
	File    string `json:"file"`
	Line    int    `json:"line"`
	Col     int    `json:"col"`
	EndLine int    `json:"end_line"`
}

// Doc is a documentation comment plus its source idiom.
type Doc struct {
	Raw    string `json:"raw"`
	Format string `json:"format"`
}

// Invocation describes how to run an entrypoint symbol.
type Invocation struct {
	Kind string `json:"kind"`
	How  string `json:"how"`
}

// Complexity is the reserved big-O slot. SP1 always emits the deferred value.
type Complexity struct {
	Time   *string `json:"time"`
	Space  *string `json:"space"`
	Method string  `json:"method"`
}

// DeferredComplexity returns the SP1 placeholder complexity value.
func DeferredComplexity() Complexity {
	return Complexity{Time: nil, Space: nil, Method: "deferred"}
}

// Call is one edge in the call graph: one distinct callee of a function-like
// symbol, deduplicated across its call sites. Edges are sorted by Target,
// Kind, Ref, Arity, then ArgTypes, so equal inputs produce byte-identical
// output.
//
// Kind says how far resolution got, and is honest about the boundary:
//   - "internal":   the callee is a symbol in this manifest; Ref locates it.
//   - "external":   resolved to a package outside the scan (stdlib or a
//     dependency); the graph bottoms out here by construction.
//   - "builtin":    a language primitive (Go len/make/append..., Python
//     print/len/range...); the floor of the graph.
//   - "dynamic":    a call through a function value or interface/abstract
//     method; the static target is unknowable, Target names the site's
//     declared callee (e.g. the interface method) or the value expression.
//   - "unresolved": a syntactic extractor could not resolve the name
//     (imported-name gaps, receiver-typed method calls in Python/Java);
//     Target is the callee as written.
//
// Arity and ArgTypes are call-site evidence, recorded as written, for
// languages with overloading (Java). Arity is the argument count. ArgTypes
// has one entry per argument position: the type when the source states it (a
// literal, a cast, a new T(...), this, a string concatenation) and null when
// it does not (an identifier, a call result). The field is omitted when every
// position is unknown. A consumer joins them against each candidate
// overload's signature.params to draw the graph: exact when arity or
// evidence distinguishes, an honest fan-out when it does not.
type Call struct {
	Target   string    `json:"target"`              // callee as resolved, or as written
	Kind     string    `json:"kind"`                // internal|external|builtin|dynamic|unresolved
	Ref      string    `json:"ref,omitempty"`       // "<package-id>#<symbol-id>" for internal edges
	Arity    *int      `json:"arity,omitempty"`     // call-site argument count (overloading languages)
	ArgTypes []*string `json:"arg_types,omitempty"` // per-position type evidence; null = unknown
	Count    int       `json:"count"`               // number of call sites merged into this edge
}

// DedupeCalls merges edges into the canonical form documented on Call. A
// non-positive Count represents one raw site; an already aggregated positive
// Count is preserved. This makes normalization idempotent while retaining the
// historical behavior for extractor-produced raw sites. The merge key is the
// full vector - Target, Kind, Ref, Arity, ArgTypes - so two sites that carry
// different evidence stay distinct edges rather than blurring into one.
// Returns nil for no edges so the field is omitted entirely.
func DedupeCalls(raw []Call) []Call {
	if len(raw) == 0 {
		return nil
	}
	type slot struct {
		c Call
		n int
	}
	byKey := make(map[string]*slot, len(raw))
	for _, c := range raw {
		n := c.Count
		if n < 1 {
			n = 1
		}
		c.Count = 0
		k := callKey(c)
		if s, ok := byKey[k]; ok {
			s.n += n
		} else {
			byKey[k] = &slot{c: c, n: n}
		}
	}
	out := make([]Call, 0, len(byKey))
	for _, s := range byKey {
		s.c.Count = s.n
		out = append(out, s.c)
	}
	sort.Slice(out, func(i, j int) bool { return callLess(out[i], out[j]) })
	return out
}

// callKey encodes an edge's identity (everything but Count). \x00 separates
// fields; \x01 marks an unknown ArgTypes position so it cannot collide with
// the empty string.
func callKey(c Call) string {
	var b strings.Builder
	b.WriteString(c.Target)
	b.WriteByte(0)
	b.WriteString(c.Kind)
	b.WriteByte(0)
	b.WriteString(c.Ref)
	b.WriteByte(0)
	if c.Arity != nil {
		b.WriteString(strconv.Itoa(*c.Arity))
	}
	for _, t := range c.ArgTypes {
		b.WriteByte(0)
		if t == nil {
			b.WriteByte(1)
		} else {
			b.WriteString(*t)
		}
	}
	return b.String()
}

// callLess is the canonical edge order: Target, Kind, Ref, Arity (absent
// first), then ArgTypes positionally (shorter first; unknown before known).
func callLess(a, b Call) bool {
	if a.Target != b.Target {
		return a.Target < b.Target
	}
	if a.Kind != b.Kind {
		return a.Kind < b.Kind
	}
	if a.Ref != b.Ref {
		return a.Ref < b.Ref
	}
	aa, ba := -1, -1
	if a.Arity != nil {
		aa = *a.Arity
	}
	if b.Arity != nil {
		ba = *b.Arity
	}
	if aa != ba {
		return aa < ba
	}
	if len(a.ArgTypes) != len(b.ArgTypes) {
		return len(a.ArgTypes) < len(b.ArgTypes)
	}
	for i := range a.ArgTypes {
		at, bt := a.ArgTypes[i], b.ArgTypes[i]
		switch {
		case at == nil && bt == nil:
			continue
		case at == nil:
			return true
		case bt == nil:
			return false
		case *at != *bt:
			return *at < *bt
		}
	}
	return false
}
