// Code generated by goplus from semantic.gp. DO NOT EDIT.
//goplus:v v0.16.1

package schema

import (
	"testing"

	"pgregory.net/rapid"
)

func TestCallSetCanonicalLaws(t *testing.T) {
	t.Run("Canonical.Idempotent", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			value := rapid.Make[[]Call]().Draw(rt, "value")
			if !CallSetCanonical.LawIdempotent(value) {
				rt.Fatalf("law Idempotent violated: value=%v", value)
			}
		})
	})
	t.Run("Canonical.Sound", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[[]Call]().Draw(rt, "a")
			b := rapid.Make[[]Call]().Draw(rt, "b")
			if !CallSetCanonical.LawSound(a, b) {
				rt.Fatalf("law Sound violated: a=%v b=%v", a, b)
			}
		})
	})
	t.Run("Canonical.Complete", func(t *testing.T) {
		rapid.Check(t, func(rt *rapid.T) {
			a := rapid.Make[[]Call]().Draw(rt, "a")
			b := rapid.Make[[]Call]().Draw(rt, "b")
			if !CallSetCanonical.LawComplete(a, b) {
				rt.Fatalf("law Complete violated: a=%v b=%v", a, b)
			}
		})
	})
}
