// Code generated by goplus from semantic.gp. DO NOT EDIT.
//goplus:v v0.16.1

package schema

import (
	"reflect"
	"strconv"
	"strings"

	"goforge.dev/goplus/std/canonical"
	"goforge.dev/goplus/std/result"
)

// CallResolution makes the resolution boundary exhaustive. Only an internal
// edge can carry a SymbolRef.
//
//goplus:enum CallResolution
type CallResolution interface{ isCallResolution() }

//goplus:variant (CallResolution) CallInternal(ref SymbolRef)
type CallInternal struct {
	Ref SymbolRef
}

func (CallInternal) isCallResolution() {}

//goplus:variant (CallResolution) CallExternal
type CallExternal struct{}

func (CallExternal) isCallResolution() {}

//goplus:variant (CallResolution) CallBuiltin
type CallBuiltin struct{}

func (CallBuiltin) isCallResolution() {}

//goplus:variant (CallResolution) CallDynamic
type CallDynamic struct{}

func (CallDynamic) isCallResolution() {}

//goplus:variant (CallResolution) CallUnresolved
type CallUnresolved struct{}

func (CallUnresolved) isCallResolution() {}

// CallResolutionCases selects one handler per CallResolution variant for CallResolutionFold.
type CallResolutionCases[R any] struct {
	CallInternal   func(ref SymbolRef) R
	CallExternal   func() R
	CallBuiltin    func() R
	CallDynamic    func() R
	CallUnresolved func() R
}

// CallResolutionFold reduces CallResolution by one-level case analysis.
func CallResolutionFold[R any](v CallResolution, cs CallResolutionCases[R]) R {
	switch m := any(v).(type) {
	case CallInternal:
		return cs.CallInternal(m.Ref)
	case CallExternal:
		return cs.CallExternal()
	case CallBuiltin:
		return cs.CallBuiltin()
	case CallDynamic:
		return cs.CallDynamic()
	case CallUnresolved:
		return cs.CallUnresolved()
	default:
		panic("goplus: impossible enum value in CallResolutionFold")
	}
}

// CallResolutionEqOverrides carries optional per-variant hooks for CallResolutionEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type CallResolutionEqOverrides struct {
	CallInternal   func(x, y CallInternal) (eq, handled bool)
	CallExternal   func(x, y CallExternal) (eq, handled bool)
	CallBuiltin    func(x, y CallBuiltin) (eq, handled bool)
	CallDynamic    func(x, y CallDynamic) (eq, handled bool)
	CallUnresolved func(x, y CallUnresolved) (eq, handled bool)
}

// CallResolutionEqualWith reports structural equality of a and b under ov.
func CallResolutionEqualWith(a, b CallResolution, ov CallResolutionEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case CallInternal:
		y, ok := any(b).(CallInternal)
		if !ok {
			return false
		}
		if ov.CallInternal != nil {
			if eq, handled := ov.CallInternal(x, y); handled {
				return eq
			}
		}
		if x.Ref != y.Ref {
			return false
		}
		return true
	case CallExternal:
		y, ok := any(b).(CallExternal)
		if !ok {
			return false
		}
		if ov.CallExternal != nil {
			if eq, handled := ov.CallExternal(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case CallBuiltin:
		y, ok := any(b).(CallBuiltin)
		if !ok {
			return false
		}
		if ov.CallBuiltin != nil {
			if eq, handled := ov.CallBuiltin(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case CallDynamic:
		y, ok := any(b).(CallDynamic)
		if !ok {
			return false
		}
		if ov.CallDynamic != nil {
			if eq, handled := ov.CallDynamic(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case CallUnresolved:
		y, ok := any(b).(CallUnresolved)
		if !ok {
			return false
		}
		if ov.CallUnresolved != nil {
			if eq, handled := ov.CallUnresolved(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// CallResolutionEqual reports structural equality of a and b.
func CallResolutionEqual(a, b CallResolution) bool {
	return CallResolutionEqualWith(a, b, CallResolutionEqOverrides{})
}

// TypeEvidence distinguishes absent evidence from an explicitly stated type.
//
//goplus:enum TypeEvidence
type TypeEvidence interface{ isTypeEvidence() }

//goplus:variant (TypeEvidence) EvidenceUnknown
type EvidenceUnknown struct{}

func (EvidenceUnknown) isTypeEvidence() {}

//goplus:variant (TypeEvidence) EvidenceStated(typeName string)
type EvidenceStated struct {
	TypeName string
}

func (EvidenceStated) isTypeEvidence() {}

// TypeEvidenceCases selects one handler per TypeEvidence variant for TypeEvidenceFold.
type TypeEvidenceCases[R any] struct {
	EvidenceUnknown func() R
	EvidenceStated  func(typeName string) R
}

// TypeEvidenceFold reduces TypeEvidence by one-level case analysis.
func TypeEvidenceFold[R any](t TypeEvidence, cs TypeEvidenceCases[R]) R {
	switch m := any(t).(type) {
	case EvidenceUnknown:
		return cs.EvidenceUnknown()
	case EvidenceStated:
		return cs.EvidenceStated(m.TypeName)
	default:
		panic("goplus: impossible enum value in TypeEvidenceFold")
	}
}

// TypeEvidenceEqOverrides carries optional per-variant hooks for TypeEvidenceEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type TypeEvidenceEqOverrides struct {
	EvidenceUnknown func(x, y EvidenceUnknown) (eq, handled bool)
	EvidenceStated  func(x, y EvidenceStated) (eq, handled bool)
}

// TypeEvidenceEqualWith reports structural equality of a and b under ov.
func TypeEvidenceEqualWith(a, b TypeEvidence, ov TypeEvidenceEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case EvidenceUnknown:
		y, ok := any(b).(EvidenceUnknown)
		if !ok {
			return false
		}
		if ov.EvidenceUnknown != nil {
			if eq, handled := ov.EvidenceUnknown(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case EvidenceStated:
		y, ok := any(b).(EvidenceStated)
		if !ok {
			return false
		}
		if ov.EvidenceStated != nil {
			if eq, handled := ov.EvidenceStated(x, y); handled {
				return eq
			}
		}
		if x.TypeName != y.TypeName {
			return false
		}
		return true
	}
	return false
}

// TypeEvidenceEqual reports structural equality of a and b.
func TypeEvidenceEqual(a, b TypeEvidence) bool {
	return TypeEvidenceEqualWith(a, b, TypeEvidenceEqOverrides{})
}

// OverloadResolution records the three honest results of joining call-site
// evidence with declarations.
//
//goplus:enum OverloadResolution
type OverloadResolution interface{ isOverloadResolution() }

//goplus:variant (OverloadResolution) ResolutionExact(target SymbolRef)
type ResolutionExact struct {
	Target SymbolRef
}

func (ResolutionExact) isOverloadResolution() {}

//goplus:variant (OverloadResolution) ResolutionAmbiguous(candidates []SymbolRef)
type ResolutionAmbiguous struct {
	Candidates []SymbolRef
}

func (ResolutionAmbiguous) isOverloadResolution() {}

//goplus:variant (OverloadResolution) ResolutionImpossible
type ResolutionImpossible struct{}

func (ResolutionImpossible) isOverloadResolution() {}

// OverloadResolutionCases selects one handler per OverloadResolution variant for OverloadResolutionFold.
type OverloadResolutionCases[R any] struct {
	ResolutionExact      func(target SymbolRef) R
	ResolutionAmbiguous  func(candidates []SymbolRef) R
	ResolutionImpossible func() R
}

// OverloadResolutionFold reduces OverloadResolution by one-level case analysis.
func OverloadResolutionFold[R any](o OverloadResolution, cs OverloadResolutionCases[R]) R {
	switch m := any(o).(type) {
	case ResolutionExact:
		return cs.ResolutionExact(m.Target)
	case ResolutionAmbiguous:
		return cs.ResolutionAmbiguous(m.Candidates)
	case ResolutionImpossible:
		return cs.ResolutionImpossible()
	default:
		panic("goplus: impossible enum value in OverloadResolutionFold")
	}
}

// OverloadResolutionEqOverrides carries optional per-variant hooks for OverloadResolutionEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type OverloadResolutionEqOverrides struct {
	ResolutionExact      func(x, y ResolutionExact) (eq, handled bool)
	ResolutionAmbiguous  func(x, y ResolutionAmbiguous) (eq, handled bool)
	ResolutionImpossible func(x, y ResolutionImpossible) (eq, handled bool)
}

// OverloadResolutionEqualWith reports structural equality of a and b under ov.
func OverloadResolutionEqualWith(a, b OverloadResolution, ov OverloadResolutionEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ResolutionExact:
		y, ok := any(b).(ResolutionExact)
		if !ok {
			return false
		}
		if ov.ResolutionExact != nil {
			if eq, handled := ov.ResolutionExact(x, y); handled {
				return eq
			}
		}
		if x.Target != y.Target {
			return false
		}
		return true
	case ResolutionAmbiguous:
		y, ok := any(b).(ResolutionAmbiguous)
		if !ok {
			return false
		}
		if ov.ResolutionAmbiguous != nil {
			if eq, handled := ov.ResolutionAmbiguous(x, y); handled {
				return eq
			}
		}
		if len(x.Candidates) != len(y.Candidates) {
			return false
		}
		for i0 := range x.Candidates {
			if x.Candidates[i0] != y.Candidates[i0] {
				return false
			}
		}
		return true
	case ResolutionImpossible:
		y, ok := any(b).(ResolutionImpossible)
		if !ok {
			return false
		}
		if ov.ResolutionImpossible != nil {
			if eq, handled := ov.ResolutionImpossible(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// OverloadResolutionEqual reports structural equality of a and b.
func OverloadResolutionEqual(a, b OverloadResolution) bool {
	return OverloadResolutionEqualWith(a, b, OverloadResolutionEqOverrides{})
}

// Bound is the closed complexity vocabulary AssayXport currently emits.
//
//goplus:enum Bound
type Bound interface{ isBound() }

//goplus:variant (Bound) ConstantBound
type ConstantBound struct{}

func (ConstantBound) isBound() {}

//goplus:variant (Bound) LinearBound
type LinearBound struct{}

func (LinearBound) isBound() {}

//goplus:variant (Bound) PolynomialBound(degree int)
type PolynomialBound struct {
	Degree int
}

func (PolynomialBound) isBound() {}

// BoundCases selects one handler per Bound variant for BoundFold.
type BoundCases[R any] struct {
	ConstantBound   func() R
	LinearBound     func() R
	PolynomialBound func(degree int) R
}

// BoundFold reduces Bound by one-level case analysis.
func BoundFold[R any](b Bound, cs BoundCases[R]) R {
	switch m := any(b).(type) {
	case ConstantBound:
		return cs.ConstantBound()
	case LinearBound:
		return cs.LinearBound()
	case PolynomialBound:
		return cs.PolynomialBound(m.Degree)
	default:
		panic("goplus: impossible enum value in BoundFold")
	}
}

// BoundEqOverrides carries optional per-variant hooks for BoundEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type BoundEqOverrides struct {
	ConstantBound   func(x, y ConstantBound) (eq, handled bool)
	LinearBound     func(x, y LinearBound) (eq, handled bool)
	PolynomialBound func(x, y PolynomialBound) (eq, handled bool)
}

// BoundEqualWith reports structural equality of a and b under ov.
func BoundEqualWith(a, b Bound, ov BoundEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ConstantBound:
		y, ok := any(b).(ConstantBound)
		if !ok {
			return false
		}
		if ov.ConstantBound != nil {
			if eq, handled := ov.ConstantBound(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case LinearBound:
		y, ok := any(b).(LinearBound)
		if !ok {
			return false
		}
		if ov.LinearBound != nil {
			if eq, handled := ov.LinearBound(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case PolynomialBound:
		y, ok := any(b).(PolynomialBound)
		if !ok {
			return false
		}
		if ov.PolynomialBound != nil {
			if eq, handled := ov.PolynomialBound(x, y); handled {
				return eq
			}
		}
		if x.Degree != y.Degree {
			return false
		}
		return true
	}
	return false
}

// BoundEqual reports structural equality of a and b.
func BoundEqual(a, b Bound) bool {
	return BoundEqualWith(a, b, BoundEqOverrides{})
}

// ComplexityEstimate prevents a recursive/deferred estimate from carrying
// fabricated bounds.
//
//goplus:enum ComplexityEstimate
type ComplexityEstimate interface{ isComplexityEstimate() }

//goplus:variant (ComplexityEstimate) ComplexityDeferred
type ComplexityDeferred struct{}

func (ComplexityDeferred) isComplexityEstimate() {}

//goplus:variant (ComplexityEstimate) ComplexityLoopNesting(time Bound, space Bound)
type ComplexityLoopNesting struct {
	Time  Bound
	Space Bound
}

func (ComplexityLoopNesting) isComplexityEstimate() {}

//goplus:variant (ComplexityEstimate) ComplexityRecursive
type ComplexityRecursive struct{}

func (ComplexityRecursive) isComplexityEstimate() {}

// ComplexityEstimateCases selects one handler per ComplexityEstimate variant for ComplexityEstimateFold.
type ComplexityEstimateCases[R any] struct {
	ComplexityDeferred    func() R
	ComplexityLoopNesting func(time Bound, space Bound) R
	ComplexityRecursive   func() R
}

// ComplexityEstimateFold reduces ComplexityEstimate by one-level case analysis.
func ComplexityEstimateFold[R any](v ComplexityEstimate, cs ComplexityEstimateCases[R]) R {
	switch m := any(v).(type) {
	case ComplexityDeferred:
		return cs.ComplexityDeferred()
	case ComplexityLoopNesting:
		return cs.ComplexityLoopNesting(m.Time, m.Space)
	case ComplexityRecursive:
		return cs.ComplexityRecursive()
	default:
		panic("goplus: impossible enum value in ComplexityEstimateFold")
	}
}

// ComplexityEstimateEqOverrides carries optional per-variant hooks for ComplexityEstimateEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ComplexityEstimateEqOverrides struct {
	ComplexityDeferred    func(x, y ComplexityDeferred) (eq, handled bool)
	ComplexityLoopNesting func(x, y ComplexityLoopNesting) (eq, handled bool)
	ComplexityRecursive   func(x, y ComplexityRecursive) (eq, handled bool)
}

// ComplexityEstimateEqualWith reports structural equality of a and b under ov.
func ComplexityEstimateEqualWith(a, b ComplexityEstimate, ov ComplexityEstimateEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ComplexityDeferred:
		y, ok := any(b).(ComplexityDeferred)
		if !ok {
			return false
		}
		if ov.ComplexityDeferred != nil {
			if eq, handled := ov.ComplexityDeferred(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ComplexityLoopNesting:
		y, ok := any(b).(ComplexityLoopNesting)
		if !ok {
			return false
		}
		if ov.ComplexityLoopNesting != nil {
			if eq, handled := ov.ComplexityLoopNesting(x, y); handled {
				return eq
			}
		}
		if !BoundEqual(x.Time, y.Time) {
			return false
		}
		if !BoundEqual(x.Space, y.Space) {
			return false
		}
		return true
	case ComplexityRecursive:
		y, ok := any(b).(ComplexityRecursive)
		if !ok {
			return false
		}
		if ov.ComplexityRecursive != nil {
			if eq, handled := ov.ComplexityRecursive(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// ComplexityEstimateEqual reports structural equality of a and b.
func ComplexityEstimateEqual(a, b ComplexityEstimate) bool {
	return ComplexityEstimateEqualWith(a, b, ComplexityEstimateEqOverrides{})
}

//goplus:enum Language
type Language interface{ isLanguage() }

//goplus:variant (Language) GoLanguage
type GoLanguage struct{}

func (GoLanguage) isLanguage() {}

//goplus:variant (Language) PythonLanguage
type PythonLanguage struct{}

func (PythonLanguage) isLanguage() {}

//goplus:variant (Language) JavaLanguage
type JavaLanguage struct{}

func (JavaLanguage) isLanguage() {}

//goplus:variant (Language) TypeScriptLanguage
type TypeScriptLanguage struct{}

func (TypeScriptLanguage) isLanguage() {}

//goplus:variant (Language) JavaScriptLanguage
type JavaScriptLanguage struct{}

func (JavaScriptLanguage) isLanguage() {}

// LanguageCases selects one handler per Language variant for LanguageFold.
type LanguageCases[R any] struct {
	GoLanguage         func() R
	PythonLanguage     func() R
	JavaLanguage       func() R
	TypeScriptLanguage func() R
	JavaScriptLanguage func() R
}

// LanguageFold reduces Language by one-level case analysis.
func LanguageFold[R any](l Language, cs LanguageCases[R]) R {
	switch any(l).(type) {
	case GoLanguage:
		return cs.GoLanguage()
	case PythonLanguage:
		return cs.PythonLanguage()
	case JavaLanguage:
		return cs.JavaLanguage()
	case TypeScriptLanguage:
		return cs.TypeScriptLanguage()
	case JavaScriptLanguage:
		return cs.JavaScriptLanguage()
	default:
		panic("goplus: impossible enum value in LanguageFold")
	}
}

// LanguageEqOverrides carries optional per-variant hooks for LanguageEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type LanguageEqOverrides struct {
	GoLanguage         func(x, y GoLanguage) (eq, handled bool)
	PythonLanguage     func(x, y PythonLanguage) (eq, handled bool)
	JavaLanguage       func(x, y JavaLanguage) (eq, handled bool)
	TypeScriptLanguage func(x, y TypeScriptLanguage) (eq, handled bool)
	JavaScriptLanguage func(x, y JavaScriptLanguage) (eq, handled bool)
}

// LanguageEqualWith reports structural equality of a and b under ov.
func LanguageEqualWith(a, b Language, ov LanguageEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case GoLanguage:
		y, ok := any(b).(GoLanguage)
		if !ok {
			return false
		}
		if ov.GoLanguage != nil {
			if eq, handled := ov.GoLanguage(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case PythonLanguage:
		y, ok := any(b).(PythonLanguage)
		if !ok {
			return false
		}
		if ov.PythonLanguage != nil {
			if eq, handled := ov.PythonLanguage(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case JavaLanguage:
		y, ok := any(b).(JavaLanguage)
		if !ok {
			return false
		}
		if ov.JavaLanguage != nil {
			if eq, handled := ov.JavaLanguage(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case TypeScriptLanguage:
		y, ok := any(b).(TypeScriptLanguage)
		if !ok {
			return false
		}
		if ov.TypeScriptLanguage != nil {
			if eq, handled := ov.TypeScriptLanguage(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case JavaScriptLanguage:
		y, ok := any(b).(JavaScriptLanguage)
		if !ok {
			return false
		}
		if ov.JavaScriptLanguage != nil {
			if eq, handled := ov.JavaScriptLanguage(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// LanguageEqual reports structural equality of a and b.
func LanguageEqual(a, b Language) bool {
	return LanguageEqualWith(a, b, LanguageEqOverrides{})
}

//goplus:enum SymbolKind
type SymbolKind interface{ isSymbolKind() }

//goplus:variant (SymbolKind) TypeSymbol
type TypeSymbol struct{}

func (TypeSymbol) isSymbolKind() {}

//goplus:variant (SymbolKind) FunctionSymbol
type FunctionSymbol struct{}

func (FunctionSymbol) isSymbolKind() {}

//goplus:variant (SymbolKind) FuncSymbol
type FuncSymbol struct{}

func (FuncSymbol) isSymbolKind() {}

//goplus:variant (SymbolKind) MethodSymbol
type MethodSymbol struct{}

func (MethodSymbol) isSymbolKind() {}

//goplus:variant (SymbolKind) ConstructorSymbol
type ConstructorSymbol struct{}

func (ConstructorSymbol) isSymbolKind() {}

//goplus:variant (SymbolKind) FieldSymbol
type FieldSymbol struct{}

func (FieldSymbol) isSymbolKind() {}

//goplus:variant (SymbolKind) VariableSymbol
type VariableSymbol struct{}

func (VariableSymbol) isSymbolKind() {}

//goplus:variant (SymbolKind) VarSymbol
type VarSymbol struct{}

func (VarSymbol) isSymbolKind() {}

//goplus:variant (SymbolKind) ConstantSymbol
type ConstantSymbol struct{}

func (ConstantSymbol) isSymbolKind() {}

//goplus:variant (SymbolKind) PropertySymbol
type PropertySymbol struct{}

func (PropertySymbol) isSymbolKind() {}

//goplus:variant (SymbolKind) ClassSymbol
type ClassSymbol struct{}

func (ClassSymbol) isSymbolKind() {}

//goplus:variant (SymbolKind) EnumConstantSymbol
type EnumConstantSymbol struct{}

func (EnumConstantSymbol) isSymbolKind() {}

// SymbolKindCases selects one handler per SymbolKind variant for SymbolKindFold.
type SymbolKindCases[R any] struct {
	TypeSymbol         func() R
	FunctionSymbol     func() R
	FuncSymbol         func() R
	MethodSymbol       func() R
	ConstructorSymbol  func() R
	FieldSymbol        func() R
	VariableSymbol     func() R
	VarSymbol          func() R
	ConstantSymbol     func() R
	PropertySymbol     func() R
	ClassSymbol        func() R
	EnumConstantSymbol func() R
}

// SymbolKindFold reduces SymbolKind by one-level case analysis.
func SymbolKindFold[R any](s SymbolKind, cs SymbolKindCases[R]) R {
	switch any(s).(type) {
	case TypeSymbol:
		return cs.TypeSymbol()
	case FunctionSymbol:
		return cs.FunctionSymbol()
	case FuncSymbol:
		return cs.FuncSymbol()
	case MethodSymbol:
		return cs.MethodSymbol()
	case ConstructorSymbol:
		return cs.ConstructorSymbol()
	case FieldSymbol:
		return cs.FieldSymbol()
	case VariableSymbol:
		return cs.VariableSymbol()
	case VarSymbol:
		return cs.VarSymbol()
	case ConstantSymbol:
		return cs.ConstantSymbol()
	case PropertySymbol:
		return cs.PropertySymbol()
	case ClassSymbol:
		return cs.ClassSymbol()
	case EnumConstantSymbol:
		return cs.EnumConstantSymbol()
	default:
		panic("goplus: impossible enum value in SymbolKindFold")
	}
}

// SymbolKindEqOverrides carries optional per-variant hooks for SymbolKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type SymbolKindEqOverrides struct {
	TypeSymbol         func(x, y TypeSymbol) (eq, handled bool)
	FunctionSymbol     func(x, y FunctionSymbol) (eq, handled bool)
	FuncSymbol         func(x, y FuncSymbol) (eq, handled bool)
	MethodSymbol       func(x, y MethodSymbol) (eq, handled bool)
	ConstructorSymbol  func(x, y ConstructorSymbol) (eq, handled bool)
	FieldSymbol        func(x, y FieldSymbol) (eq, handled bool)
	VariableSymbol     func(x, y VariableSymbol) (eq, handled bool)
	VarSymbol          func(x, y VarSymbol) (eq, handled bool)
	ConstantSymbol     func(x, y ConstantSymbol) (eq, handled bool)
	PropertySymbol     func(x, y PropertySymbol) (eq, handled bool)
	ClassSymbol        func(x, y ClassSymbol) (eq, handled bool)
	EnumConstantSymbol func(x, y EnumConstantSymbol) (eq, handled bool)
}

// SymbolKindEqualWith reports structural equality of a and b under ov.
func SymbolKindEqualWith(a, b SymbolKind, ov SymbolKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case TypeSymbol:
		y, ok := any(b).(TypeSymbol)
		if !ok {
			return false
		}
		if ov.TypeSymbol != nil {
			if eq, handled := ov.TypeSymbol(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case FunctionSymbol:
		y, ok := any(b).(FunctionSymbol)
		if !ok {
			return false
		}
		if ov.FunctionSymbol != nil {
			if eq, handled := ov.FunctionSymbol(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case FuncSymbol:
		y, ok := any(b).(FuncSymbol)
		if !ok {
			return false
		}
		if ov.FuncSymbol != nil {
			if eq, handled := ov.FuncSymbol(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case MethodSymbol:
		y, ok := any(b).(MethodSymbol)
		if !ok {
			return false
		}
		if ov.MethodSymbol != nil {
			if eq, handled := ov.MethodSymbol(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ConstructorSymbol:
		y, ok := any(b).(ConstructorSymbol)
		if !ok {
			return false
		}
		if ov.ConstructorSymbol != nil {
			if eq, handled := ov.ConstructorSymbol(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case FieldSymbol:
		y, ok := any(b).(FieldSymbol)
		if !ok {
			return false
		}
		if ov.FieldSymbol != nil {
			if eq, handled := ov.FieldSymbol(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case VariableSymbol:
		y, ok := any(b).(VariableSymbol)
		if !ok {
			return false
		}
		if ov.VariableSymbol != nil {
			if eq, handled := ov.VariableSymbol(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case VarSymbol:
		y, ok := any(b).(VarSymbol)
		if !ok {
			return false
		}
		if ov.VarSymbol != nil {
			if eq, handled := ov.VarSymbol(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ConstantSymbol:
		y, ok := any(b).(ConstantSymbol)
		if !ok {
			return false
		}
		if ov.ConstantSymbol != nil {
			if eq, handled := ov.ConstantSymbol(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case PropertySymbol:
		y, ok := any(b).(PropertySymbol)
		if !ok {
			return false
		}
		if ov.PropertySymbol != nil {
			if eq, handled := ov.PropertySymbol(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ClassSymbol:
		y, ok := any(b).(ClassSymbol)
		if !ok {
			return false
		}
		if ov.ClassSymbol != nil {
			if eq, handled := ov.ClassSymbol(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case EnumConstantSymbol:
		y, ok := any(b).(EnumConstantSymbol)
		if !ok {
			return false
		}
		if ov.EnumConstantSymbol != nil {
			if eq, handled := ov.EnumConstantSymbol(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// SymbolKindEqual reports structural equality of a and b.
func SymbolKindEqual(a, b SymbolKind) bool {
	return SymbolKindEqualWith(a, b, SymbolKindEqOverrides{})
}

//goplus:enum Visibility
type Visibility interface{ isVisibility() }

//goplus:variant (Visibility) ExportedVisibility
type ExportedVisibility struct{}

func (ExportedVisibility) isVisibility() {}

//goplus:variant (Visibility) UnexportedVisibility
type UnexportedVisibility struct{}

func (UnexportedVisibility) isVisibility() {}

//goplus:variant (Visibility) PublicVisibility
type PublicVisibility struct{}

func (PublicVisibility) isVisibility() {}

//goplus:variant (Visibility) ProtectedVisibility
type ProtectedVisibility struct{}

func (ProtectedVisibility) isVisibility() {}

//goplus:variant (Visibility) PrivateVisibility
type PrivateVisibility struct{}

func (PrivateVisibility) isVisibility() {}

//goplus:variant (Visibility) PackageVisibility
type PackageVisibility struct{}

func (PackageVisibility) isVisibility() {}

// VisibilityCases selects one handler per Visibility variant for VisibilityFold.
type VisibilityCases[R any] struct {
	ExportedVisibility   func() R
	UnexportedVisibility func() R
	PublicVisibility     func() R
	ProtectedVisibility  func() R
	PrivateVisibility    func() R
	PackageVisibility    func() R
}

// VisibilityFold reduces Visibility by one-level case analysis.
func VisibilityFold[R any](v Visibility, cs VisibilityCases[R]) R {
	switch any(v).(type) {
	case ExportedVisibility:
		return cs.ExportedVisibility()
	case UnexportedVisibility:
		return cs.UnexportedVisibility()
	case PublicVisibility:
		return cs.PublicVisibility()
	case ProtectedVisibility:
		return cs.ProtectedVisibility()
	case PrivateVisibility:
		return cs.PrivateVisibility()
	case PackageVisibility:
		return cs.PackageVisibility()
	default:
		panic("goplus: impossible enum value in VisibilityFold")
	}
}

// VisibilityEqOverrides carries optional per-variant hooks for VisibilityEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type VisibilityEqOverrides struct {
	ExportedVisibility   func(x, y ExportedVisibility) (eq, handled bool)
	UnexportedVisibility func(x, y UnexportedVisibility) (eq, handled bool)
	PublicVisibility     func(x, y PublicVisibility) (eq, handled bool)
	ProtectedVisibility  func(x, y ProtectedVisibility) (eq, handled bool)
	PrivateVisibility    func(x, y PrivateVisibility) (eq, handled bool)
	PackageVisibility    func(x, y PackageVisibility) (eq, handled bool)
}

// VisibilityEqualWith reports structural equality of a and b under ov.
func VisibilityEqualWith(a, b Visibility, ov VisibilityEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case ExportedVisibility:
		y, ok := any(b).(ExportedVisibility)
		if !ok {
			return false
		}
		if ov.ExportedVisibility != nil {
			if eq, handled := ov.ExportedVisibility(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case UnexportedVisibility:
		y, ok := any(b).(UnexportedVisibility)
		if !ok {
			return false
		}
		if ov.UnexportedVisibility != nil {
			if eq, handled := ov.UnexportedVisibility(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case PublicVisibility:
		y, ok := any(b).(PublicVisibility)
		if !ok {
			return false
		}
		if ov.PublicVisibility != nil {
			if eq, handled := ov.PublicVisibility(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ProtectedVisibility:
		y, ok := any(b).(ProtectedVisibility)
		if !ok {
			return false
		}
		if ov.ProtectedVisibility != nil {
			if eq, handled := ov.ProtectedVisibility(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case PrivateVisibility:
		y, ok := any(b).(PrivateVisibility)
		if !ok {
			return false
		}
		if ov.PrivateVisibility != nil {
			if eq, handled := ov.PrivateVisibility(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case PackageVisibility:
		y, ok := any(b).(PackageVisibility)
		if !ok {
			return false
		}
		if ov.PackageVisibility != nil {
			if eq, handled := ov.PackageVisibility(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// VisibilityEqual reports structural equality of a and b.
func VisibilityEqual(a, b Visibility) bool {
	return VisibilityEqualWith(a, b, VisibilityEqOverrides{})
}

//goplus:enum VisibilityIdiom
type VisibilityIdiom interface{ isVisibilityIdiom() }

//goplus:variant (VisibilityIdiom) CapitalizedVisibility
type CapitalizedVisibility struct{}

func (CapitalizedVisibility) isVisibilityIdiom() {}

//goplus:variant (VisibilityIdiom) UnderscoreVisibility
type UnderscoreVisibility struct{}

func (UnderscoreVisibility) isVisibilityIdiom() {}

//goplus:variant (VisibilityIdiom) AccessModifierVisibility
type AccessModifierVisibility struct{}

func (AccessModifierVisibility) isVisibilityIdiom() {}

//goplus:variant (VisibilityIdiom) ExportVisibility
type ExportVisibility struct{}

func (ExportVisibility) isVisibilityIdiom() {}

// VisibilityIdiomCases selects one handler per VisibilityIdiom variant for VisibilityIdiomFold.
type VisibilityIdiomCases[R any] struct {
	CapitalizedVisibility    func() R
	UnderscoreVisibility     func() R
	AccessModifierVisibility func() R
	ExportVisibility         func() R
}

// VisibilityIdiomFold reduces VisibilityIdiom by one-level case analysis.
func VisibilityIdiomFold[R any](v VisibilityIdiom, cs VisibilityIdiomCases[R]) R {
	switch any(v).(type) {
	case CapitalizedVisibility:
		return cs.CapitalizedVisibility()
	case UnderscoreVisibility:
		return cs.UnderscoreVisibility()
	case AccessModifierVisibility:
		return cs.AccessModifierVisibility()
	case ExportVisibility:
		return cs.ExportVisibility()
	default:
		panic("goplus: impossible enum value in VisibilityIdiomFold")
	}
}

// VisibilityIdiomEqOverrides carries optional per-variant hooks for VisibilityIdiomEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type VisibilityIdiomEqOverrides struct {
	CapitalizedVisibility    func(x, y CapitalizedVisibility) (eq, handled bool)
	UnderscoreVisibility     func(x, y UnderscoreVisibility) (eq, handled bool)
	AccessModifierVisibility func(x, y AccessModifierVisibility) (eq, handled bool)
	ExportVisibility         func(x, y ExportVisibility) (eq, handled bool)
}

// VisibilityIdiomEqualWith reports structural equality of a and b under ov.
func VisibilityIdiomEqualWith(a, b VisibilityIdiom, ov VisibilityIdiomEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case CapitalizedVisibility:
		y, ok := any(b).(CapitalizedVisibility)
		if !ok {
			return false
		}
		if ov.CapitalizedVisibility != nil {
			if eq, handled := ov.CapitalizedVisibility(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case UnderscoreVisibility:
		y, ok := any(b).(UnderscoreVisibility)
		if !ok {
			return false
		}
		if ov.UnderscoreVisibility != nil {
			if eq, handled := ov.UnderscoreVisibility(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case AccessModifierVisibility:
		y, ok := any(b).(AccessModifierVisibility)
		if !ok {
			return false
		}
		if ov.AccessModifierVisibility != nil {
			if eq, handled := ov.AccessModifierVisibility(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ExportVisibility:
		y, ok := any(b).(ExportVisibility)
		if !ok {
			return false
		}
		if ov.ExportVisibility != nil {
			if eq, handled := ov.ExportVisibility(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// VisibilityIdiomEqual reports structural equality of a and b.
func VisibilityIdiomEqual(a, b VisibilityIdiom) bool {
	return VisibilityIdiomEqualWith(a, b, VisibilityIdiomEqOverrides{})
}

//goplus:enum DocumentationFormat
type DocumentationFormat interface{ isDocumentationFormat() }

//goplus:variant (DocumentationFormat) NoDocumentation
type NoDocumentation struct{}

func (NoDocumentation) isDocumentationFormat() {}

//goplus:variant (DocumentationFormat) GoDoc
type GoDoc struct{}

func (GoDoc) isDocumentationFormat() {}

//goplus:variant (DocumentationFormat) Docstring
type Docstring struct{}

func (Docstring) isDocumentationFormat() {}

//goplus:variant (DocumentationFormat) JavaDoc
type JavaDoc struct{}

func (JavaDoc) isDocumentationFormat() {}

//goplus:variant (DocumentationFormat) TSDoc
type TSDoc struct{}

func (TSDoc) isDocumentationFormat() {}

// DocumentationFormatCases selects one handler per DocumentationFormat variant for DocumentationFormatFold.
type DocumentationFormatCases[R any] struct {
	NoDocumentation func() R
	GoDoc           func() R
	Docstring       func() R
	JavaDoc         func() R
	TSDoc           func() R
}

// DocumentationFormatFold reduces DocumentationFormat by one-level case analysis.
func DocumentationFormatFold[R any](d DocumentationFormat, cs DocumentationFormatCases[R]) R {
	switch any(d).(type) {
	case NoDocumentation:
		return cs.NoDocumentation()
	case GoDoc:
		return cs.GoDoc()
	case Docstring:
		return cs.Docstring()
	case JavaDoc:
		return cs.JavaDoc()
	case TSDoc:
		return cs.TSDoc()
	default:
		panic("goplus: impossible enum value in DocumentationFormatFold")
	}
}

// DocumentationFormatEqOverrides carries optional per-variant hooks for DocumentationFormatEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type DocumentationFormatEqOverrides struct {
	NoDocumentation func(x, y NoDocumentation) (eq, handled bool)
	GoDoc           func(x, y GoDoc) (eq, handled bool)
	Docstring       func(x, y Docstring) (eq, handled bool)
	JavaDoc         func(x, y JavaDoc) (eq, handled bool)
	TSDoc           func(x, y TSDoc) (eq, handled bool)
}

// DocumentationFormatEqualWith reports structural equality of a and b under ov.
func DocumentationFormatEqualWith(a, b DocumentationFormat, ov DocumentationFormatEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case NoDocumentation:
		y, ok := any(b).(NoDocumentation)
		if !ok {
			return false
		}
		if ov.NoDocumentation != nil {
			if eq, handled := ov.NoDocumentation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case GoDoc:
		y, ok := any(b).(GoDoc)
		if !ok {
			return false
		}
		if ov.GoDoc != nil {
			if eq, handled := ov.GoDoc(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Docstring:
		y, ok := any(b).(Docstring)
		if !ok {
			return false
		}
		if ov.Docstring != nil {
			if eq, handled := ov.Docstring(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case JavaDoc:
		y, ok := any(b).(JavaDoc)
		if !ok {
			return false
		}
		if ov.JavaDoc != nil {
			if eq, handled := ov.JavaDoc(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case TSDoc:
		y, ok := any(b).(TSDoc)
		if !ok {
			return false
		}
		if ov.TSDoc != nil {
			if eq, handled := ov.TSDoc(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// DocumentationFormatEqual reports structural equality of a and b.
func DocumentationFormatEqual(a, b DocumentationFormat) bool {
	return DocumentationFormatEqualWith(a, b, DocumentationFormatEqOverrides{})
}

//goplus:enum InvocationKind
type InvocationKind interface{ isInvocationKind() }

//goplus:variant (InvocationKind) BinaryInvocation
type BinaryInvocation struct{}

func (BinaryInvocation) isInvocationKind() {}

//goplus:variant (InvocationKind) ModuleInvocation
type ModuleInvocation struct{}

func (ModuleInvocation) isInvocationKind() {}

//goplus:variant (InvocationKind) ClassInvocation
type ClassInvocation struct{}

func (ClassInvocation) isInvocationKind() {}

// InvocationKindCases selects one handler per InvocationKind variant for InvocationKindFold.
type InvocationKindCases[R any] struct {
	BinaryInvocation func() R
	ModuleInvocation func() R
	ClassInvocation  func() R
}

// InvocationKindFold reduces InvocationKind by one-level case analysis.
func InvocationKindFold[R any](i InvocationKind, cs InvocationKindCases[R]) R {
	switch any(i).(type) {
	case BinaryInvocation:
		return cs.BinaryInvocation()
	case ModuleInvocation:
		return cs.ModuleInvocation()
	case ClassInvocation:
		return cs.ClassInvocation()
	default:
		panic("goplus: impossible enum value in InvocationKindFold")
	}
}

// InvocationKindEqOverrides carries optional per-variant hooks for InvocationKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type InvocationKindEqOverrides struct {
	BinaryInvocation func(x, y BinaryInvocation) (eq, handled bool)
	ModuleInvocation func(x, y ModuleInvocation) (eq, handled bool)
	ClassInvocation  func(x, y ClassInvocation) (eq, handled bool)
}

// InvocationKindEqualWith reports structural equality of a and b under ov.
func InvocationKindEqualWith(a, b InvocationKind, ov InvocationKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case BinaryInvocation:
		y, ok := any(b).(BinaryInvocation)
		if !ok {
			return false
		}
		if ov.BinaryInvocation != nil {
			if eq, handled := ov.BinaryInvocation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ModuleInvocation:
		y, ok := any(b).(ModuleInvocation)
		if !ok {
			return false
		}
		if ov.ModuleInvocation != nil {
			if eq, handled := ov.ModuleInvocation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ClassInvocation:
		y, ok := any(b).(ClassInvocation)
		if !ok {
			return false
		}
		if ov.ClassInvocation != nil {
			if eq, handled := ov.ClassInvocation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// InvocationKindEqual reports structural equality of a and b.
func InvocationKindEqual(a, b InvocationKind) bool {
	return InvocationKindEqualWith(a, b, InvocationKindEqOverrides{})
}

//goplus:enum HierarchyNodeKind
type HierarchyNodeKind interface{ isHierarchyNodeKind() }

//goplus:variant (HierarchyNodeKind) GroupNode
type GroupNode struct{}

func (GroupNode) isHierarchyNodeKind() {}

//goplus:variant (HierarchyNodeKind) PackageNode
type PackageNode struct{}

func (PackageNode) isHierarchyNodeKind() {}

// HierarchyNodeKindCases selects one handler per HierarchyNodeKind variant for HierarchyNodeKindFold.
type HierarchyNodeKindCases[R any] struct {
	GroupNode   func() R
	PackageNode func() R
}

// HierarchyNodeKindFold reduces HierarchyNodeKind by one-level case analysis.
func HierarchyNodeKindFold[R any](h HierarchyNodeKind, cs HierarchyNodeKindCases[R]) R {
	switch any(h).(type) {
	case GroupNode:
		return cs.GroupNode()
	case PackageNode:
		return cs.PackageNode()
	default:
		panic("goplus: impossible enum value in HierarchyNodeKindFold")
	}
}

// HierarchyNodeKindEqOverrides carries optional per-variant hooks for HierarchyNodeKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type HierarchyNodeKindEqOverrides struct {
	GroupNode   func(x, y GroupNode) (eq, handled bool)
	PackageNode func(x, y PackageNode) (eq, handled bool)
}

// HierarchyNodeKindEqualWith reports structural equality of a and b under ov.
func HierarchyNodeKindEqualWith(a, b HierarchyNodeKind, ov HierarchyNodeKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case GroupNode:
		y, ok := any(b).(GroupNode)
		if !ok {
			return false
		}
		if ov.GroupNode != nil {
			if eq, handled := ov.GroupNode(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case PackageNode:
		y, ok := any(b).(PackageNode)
		if !ok {
			return false
		}
		if ov.PackageNode != nil {
			if eq, handled := ov.PackageNode(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// HierarchyNodeKindEqual reports structural equality of a and b.
func HierarchyNodeKindEqual(a, b HierarchyNodeKind) bool {
	return HierarchyNodeKindEqualWith(a, b, HierarchyNodeKindEqOverrides{})
}

//goplus:enum ConcernKind
type ConcernKind interface{ isConcernKind() }

//goplus:variant (ConcernKind) AnyConcern
type AnyConcern struct{}

func (AnyConcern) isConcernKind() {}

//goplus:variant (ConcernKind) AsAnyConcern
type AsAnyConcern struct{}

func (AsAnyConcern) isConcernKind() {}

//goplus:variant (ConcernKind) NonNullAssertionConcern
type NonNullAssertionConcern struct{}

func (NonNullAssertionConcern) isConcernKind() {}

//goplus:variant (ConcernKind) TSIgnoreConcern
type TSIgnoreConcern struct{}

func (TSIgnoreConcern) isConcernKind() {}

//goplus:variant (ConcernKind) UntypedParamConcern
type UntypedParamConcern struct{}

func (UntypedParamConcern) isConcernKind() {}

//goplus:variant (ConcernKind) UntypedReturnConcern
type UntypedReturnConcern struct{}

func (UntypedReturnConcern) isConcernKind() {}

//goplus:variant (ConcernKind) LooseEqualityConcern
type LooseEqualityConcern struct{}

func (LooseEqualityConcern) isConcernKind() {}

// ConcernKindCases selects one handler per ConcernKind variant for ConcernKindFold.
type ConcernKindCases[R any] struct {
	AnyConcern              func() R
	AsAnyConcern            func() R
	NonNullAssertionConcern func() R
	TSIgnoreConcern         func() R
	UntypedParamConcern     func() R
	UntypedReturnConcern    func() R
	LooseEqualityConcern    func() R
}

// ConcernKindFold reduces ConcernKind by one-level case analysis.
func ConcernKindFold[R any](v ConcernKind, cs ConcernKindCases[R]) R {
	switch any(v).(type) {
	case AnyConcern:
		return cs.AnyConcern()
	case AsAnyConcern:
		return cs.AsAnyConcern()
	case NonNullAssertionConcern:
		return cs.NonNullAssertionConcern()
	case TSIgnoreConcern:
		return cs.TSIgnoreConcern()
	case UntypedParamConcern:
		return cs.UntypedParamConcern()
	case UntypedReturnConcern:
		return cs.UntypedReturnConcern()
	case LooseEqualityConcern:
		return cs.LooseEqualityConcern()
	default:
		panic("goplus: impossible enum value in ConcernKindFold")
	}
}

// ConcernKindEqOverrides carries optional per-variant hooks for ConcernKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ConcernKindEqOverrides struct {
	AnyConcern              func(x, y AnyConcern) (eq, handled bool)
	AsAnyConcern            func(x, y AsAnyConcern) (eq, handled bool)
	NonNullAssertionConcern func(x, y NonNullAssertionConcern) (eq, handled bool)
	TSIgnoreConcern         func(x, y TSIgnoreConcern) (eq, handled bool)
	UntypedParamConcern     func(x, y UntypedParamConcern) (eq, handled bool)
	UntypedReturnConcern    func(x, y UntypedReturnConcern) (eq, handled bool)
	LooseEqualityConcern    func(x, y LooseEqualityConcern) (eq, handled bool)
}

// ConcernKindEqualWith reports structural equality of a and b under ov.
func ConcernKindEqualWith(a, b ConcernKind, ov ConcernKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case AnyConcern:
		y, ok := any(b).(AnyConcern)
		if !ok {
			return false
		}
		if ov.AnyConcern != nil {
			if eq, handled := ov.AnyConcern(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case AsAnyConcern:
		y, ok := any(b).(AsAnyConcern)
		if !ok {
			return false
		}
		if ov.AsAnyConcern != nil {
			if eq, handled := ov.AsAnyConcern(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case NonNullAssertionConcern:
		y, ok := any(b).(NonNullAssertionConcern)
		if !ok {
			return false
		}
		if ov.NonNullAssertionConcern != nil {
			if eq, handled := ov.NonNullAssertionConcern(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case TSIgnoreConcern:
		y, ok := any(b).(TSIgnoreConcern)
		if !ok {
			return false
		}
		if ov.TSIgnoreConcern != nil {
			if eq, handled := ov.TSIgnoreConcern(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case UntypedParamConcern:
		y, ok := any(b).(UntypedParamConcern)
		if !ok {
			return false
		}
		if ov.UntypedParamConcern != nil {
			if eq, handled := ov.UntypedParamConcern(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case UntypedReturnConcern:
		y, ok := any(b).(UntypedReturnConcern)
		if !ok {
			return false
		}
		if ov.UntypedReturnConcern != nil {
			if eq, handled := ov.UntypedReturnConcern(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case LooseEqualityConcern:
		y, ok := any(b).(LooseEqualityConcern)
		if !ok {
			return false
		}
		if ov.LooseEqualityConcern != nil {
			if eq, handled := ov.LooseEqualityConcern(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// ConcernKindEqual reports structural equality of a and b.
func ConcernKindEqual(a, b ConcernKind) bool {
	return ConcernKindEqualWith(a, b, ConcernKindEqOverrides{})
}

//goplus:enum InvocationMeaning
type InvocationMeaning interface{ isInvocationMeaning() }

//goplus:variant (InvocationMeaning) NotInvokable
type NotInvokable struct{}

func (NotInvokable) isInvocationMeaning() {}

//goplus:variant (InvocationMeaning) Invokable(kind InvocationKind, how string)
type Invokable struct {
	Kind InvocationKind
	How  string
}

func (Invokable) isInvocationMeaning() {}

// InvocationMeaningCases selects one handler per InvocationMeaning variant for InvocationMeaningFold.
type InvocationMeaningCases[R any] struct {
	NotInvokable func() R
	Invokable    func(kind InvocationKind, how string) R
}

// InvocationMeaningFold reduces InvocationMeaning by one-level case analysis.
func InvocationMeaningFold[R any](i InvocationMeaning, cs InvocationMeaningCases[R]) R {
	switch m := any(i).(type) {
	case NotInvokable:
		return cs.NotInvokable()
	case Invokable:
		return cs.Invokable(m.Kind, m.How)
	default:
		panic("goplus: impossible enum value in InvocationMeaningFold")
	}
}

// InvocationMeaningEqOverrides carries optional per-variant hooks for InvocationMeaningEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type InvocationMeaningEqOverrides struct {
	NotInvokable func(x, y NotInvokable) (eq, handled bool)
	Invokable    func(x, y Invokable) (eq, handled bool)
}

// InvocationMeaningEqualWith reports structural equality of a and b under ov.
func InvocationMeaningEqualWith(a, b InvocationMeaning, ov InvocationMeaningEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case NotInvokable:
		y, ok := any(b).(NotInvokable)
		if !ok {
			return false
		}
		if ov.NotInvokable != nil {
			if eq, handled := ov.NotInvokable(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case Invokable:
		y, ok := any(b).(Invokable)
		if !ok {
			return false
		}
		if ov.Invokable != nil {
			if eq, handled := ov.Invokable(x, y); handled {
				return eq
			}
		}
		if !InvocationKindEqual(x.Kind, y.Kind) {
			return false
		}
		if x.How != y.How {
			return false
		}
		return true
	}
	return false
}

// InvocationMeaningEqual reports structural equality of a and b.
func InvocationMeaningEqual(a, b InvocationMeaning) bool {
	return InvocationMeaningEqualWith(a, b, InvocationMeaningEqOverrides{})
}

type SemanticCall struct {
	Target     string
	Resolution CallResolution
	Arity      *Arity
	Evidence   []TypeEvidence
	Count      CallCount
}

type SemanticSymbol struct {
	ID              SymbolID
	Kind            SymbolKind
	Visibility      Visibility
	VisibilityIdiom VisibilityIdiom
	File            RelativeSourcePath
	Line            SourceLine
	Column          SourceColumn
	Documentation   DocumentationFormat
	Invocation      InvocationMeaning
	Complexity      ComplexityEstimate
	Concerns        []ConcernKind
	Calls           []SemanticCall
}

type SemanticPackage struct {
	ID       PackageID
	Language Language
	Symbols  []SemanticSymbol
}

//goplus:enum SemanticFailure
type SemanticFailure interface{ isSemanticFailure() }

//goplus:variant (SemanticFailure) InvalidSemantic(field string, value string)
type InvalidSemantic struct {
	Field string
	Value string
}

func (InvalidSemantic) isSemanticFailure() {}

// SemanticFailureCases selects one handler per SemanticFailure variant for SemanticFailureFold.
type SemanticFailureCases[R any] struct {
	InvalidSemantic func(field string, value string) R
}

// SemanticFailureFold reduces SemanticFailure by one-level case analysis.
func SemanticFailureFold[R any](s SemanticFailure, cs SemanticFailureCases[R]) R {
	switch m := any(s).(type) {
	case InvalidSemantic:
		return cs.InvalidSemantic(m.Field, m.Value)
	default:
		panic("goplus: impossible enum value in SemanticFailureFold")
	}
}

// SemanticFailureEqOverrides carries optional per-variant hooks for SemanticFailureEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type SemanticFailureEqOverrides struct {
	InvalidSemantic func(x, y InvalidSemantic) (eq, handled bool)
}

// SemanticFailureEqualWith reports structural equality of a and b under ov.
func SemanticFailureEqualWith(a, b SemanticFailure, ov SemanticFailureEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case InvalidSemantic:
		y, ok := any(b).(InvalidSemantic)
		if !ok {
			return false
		}
		if ov.InvalidSemantic != nil {
			if eq, handled := ov.InvalidSemantic(x, y); handled {
				return eq
			}
		}
		if x.Field != y.Field {
			return false
		}
		if x.Value != y.Value {
			return false
		}
		return true
	}
	return false
}

// SemanticFailureEqual reports structural equality of a and b.
func SemanticFailureEqual(a, b SemanticFailure) bool {
	return SemanticFailureEqualWith(a, b, SemanticFailureEqOverrides{})
}

func CallResolutionOf(c Call) result.Result[CallResolution, SemanticFailure] {
	switch c.Kind {
	case "internal":
		ref := ParseSymbolRef(c.Ref)
		return result.Map(result.MapError(ref, func(_ IdentityFailure) SemanticFailure { return InvalidSemantic{Field: "call ref", Value: c.Ref} }), func(r SymbolRef) CallResolution { return CallInternal{Ref: r} })
	case "external":
		if c.Ref != "" {
			return result.Err[CallResolution, SemanticFailure]{Err: InvalidSemantic{Field: "external call ref", Value: c.Ref}}
		}
		return result.Ok[CallResolution, SemanticFailure]{Value: CallExternal{}}
	case "builtin":
		if c.Ref != "" {
			return result.Err[CallResolution, SemanticFailure]{Err: InvalidSemantic{Field: "builtin call ref", Value: c.Ref}}
		}
		return result.Ok[CallResolution, SemanticFailure]{Value: CallBuiltin{}}
	case "dynamic":
		if c.Ref != "" {
			return result.Err[CallResolution, SemanticFailure]{Err: InvalidSemantic{Field: "dynamic call ref", Value: c.Ref}}
		}
		return result.Ok[CallResolution, SemanticFailure]{Value: CallDynamic{}}
	case "unresolved":
		if c.Ref != "" {
			return result.Err[CallResolution, SemanticFailure]{Err: InvalidSemantic{Field: "unresolved call ref", Value: c.Ref}}
		}
		return result.Ok[CallResolution, SemanticFailure]{Value: CallUnresolved{}}
	default:
		return result.Err[CallResolution, SemanticFailure]{Err: InvalidSemantic{Field: "call kind", Value: c.Kind}}
	}
}

// InternalCallRef is the exhaustive projection used by graph consumers.
func InternalCallRef(c Call) (string, bool) {
	resolution, failure := result.Unpack(CallResolutionOf(c))
	if failure != nil {
		return "", false
	}
	switch __gp_m0 := any(resolution).(type) {
	case CallInternal:
		ref := __gp_m0.Ref
		return SymbolRefString(ref), true
	case CallExternal, CallBuiltin, CallDynamic, CallUnresolved:
		return "", false
	default:
		panic("goplus: impossible enum value in match")
	}
}

func EvidenceOf(raw []*string) []TypeEvidence {
	out := make([]TypeEvidence, len(raw))
	for i, value := range raw {
		if value == nil {
			out[i] = EvidenceUnknown{}
		} else {
			out[i] = EvidenceStated{TypeName: *value}
		}
	}
	return out
}

// CallSetCanonical makes deterministic call normalization a law-tested
// standard-library Canonical instance rather than a sorting convention.
//
//goplus:instance CallSetCanonical "goforge.dev/goplus/std/canonical".Canonical[[]Call]
var CallSetCanonical = func() canonical.Canonical[[]Call] {
	w := &canonical.Canonical[[]Call]{
		Normalize:  func(value []Call) []Call { return DedupeCalls(value) },
		Equivalent: func(a, b []Call) bool { return reflect.DeepEqual(DedupeCalls(a), DedupeCalls(b)) },
	}
	return *w
}()

type OverloadCandidate struct {
	Target   SymbolRef
	Params   []string
	Variadic bool
}

func ResolveOverload(candidates []OverloadCandidate, arity Arity, evidence []TypeEvidence) OverloadResolution {
	var matches []SymbolRef
	for _, candidate := range candidates {
		n := int(arity)
		if (!candidate.Variadic && len(candidate.Params) != n) || (candidate.Variadic && n < len(candidate.Params)-1) {
			continue
		}
		compatible := true
		for i, ev := range evidence {
			paramIndex := i
			if paramIndex >= len(candidate.Params) {
				if candidate.Variadic && len(candidate.Params) > 0 {
					paramIndex = len(candidate.Params) - 1
				} else {
					compatible = false
					break
				}
			}
			switch __gp_m1 := any(ev).(type) {
			case EvidenceUnknown:
			case EvidenceStated:
				stated := __gp_m1.TypeName
				if stated != candidate.Params[paramIndex] {
					compatible = false
				}
			default:
				panic("goplus: impossible enum value in match")
			}
			if !compatible {
				break
			}
		}
		if compatible {
			matches = append(matches, candidate.Target)
		}
	}
	if len(matches) == 0 {
		return ResolutionImpossible{}
	}
	if len(matches) == 1 {
		return ResolutionExact{Target: matches[0]}
	}
	return ResolutionAmbiguous{Candidates: matches}
}

func LanguageOf(value string) result.Result[Language, SemanticFailure] {
	switch value {
	case "go":
		return result.Ok[Language, SemanticFailure]{Value: GoLanguage{}}
	case "python":
		return result.Ok[Language, SemanticFailure]{Value: PythonLanguage{}}
	case "java":
		return result.Ok[Language, SemanticFailure]{Value: JavaLanguage{}}
	case "typescript":
		return result.Ok[Language, SemanticFailure]{Value: TypeScriptLanguage{}}
	case "javascript":
		return result.Ok[Language, SemanticFailure]{Value: JavaScriptLanguage{}}
	default:
		return result.Err[Language, SemanticFailure]{Err: InvalidSemantic{Field: "language", Value: value}}
	}
}

func SymbolKindOf(value string) result.Result[SymbolKind, SemanticFailure] {
	switch value {
	case "type":
		return result.Ok[SymbolKind, SemanticFailure]{Value: TypeSymbol{}}
	case "function":
		return result.Ok[SymbolKind, SemanticFailure]{Value: FunctionSymbol{}}
	case "func":
		return result.Ok[SymbolKind, SemanticFailure]{Value: FuncSymbol{}}
	case "method":
		return result.Ok[SymbolKind, SemanticFailure]{Value: MethodSymbol{}}
	case "constructor":
		return result.Ok[SymbolKind, SemanticFailure]{Value: ConstructorSymbol{}}
	case "field":
		return result.Ok[SymbolKind, SemanticFailure]{Value: FieldSymbol{}}
	case "variable":
		return result.Ok[SymbolKind, SemanticFailure]{Value: VariableSymbol{}}
	case "var":
		return result.Ok[SymbolKind, SemanticFailure]{Value: VarSymbol{}}
	case "const":
		return result.Ok[SymbolKind, SemanticFailure]{Value: ConstantSymbol{}}
	case "property":
		return result.Ok[SymbolKind, SemanticFailure]{Value: PropertySymbol{}}
	case "class":
		return result.Ok[SymbolKind, SemanticFailure]{Value: ClassSymbol{}}
	case "enum-constant":
		return result.Ok[SymbolKind, SemanticFailure]{Value: EnumConstantSymbol{}}
	default:
		return result.Err[SymbolKind, SemanticFailure]{Err: InvalidSemantic{Field: "symbol kind", Value: value}}
	}
}

func VisibilityOf(value string) result.Result[Visibility, SemanticFailure] {
	switch value {
	case "exported":
		return result.Ok[Visibility, SemanticFailure]{Value: ExportedVisibility{}}
	case "unexported":
		return result.Ok[Visibility, SemanticFailure]{Value: UnexportedVisibility{}}
	case "public":
		return result.Ok[Visibility, SemanticFailure]{Value: PublicVisibility{}}
	case "protected":
		return result.Ok[Visibility, SemanticFailure]{Value: ProtectedVisibility{}}
	case "private":
		return result.Ok[Visibility, SemanticFailure]{Value: PrivateVisibility{}}
	case "package-private":
		return result.Ok[Visibility, SemanticFailure]{Value: PackageVisibility{}}
	default:
		return result.Err[Visibility, SemanticFailure]{Err: InvalidSemantic{Field: "visibility", Value: value}}
	}
}

func VisibilityIdiomOf(value string) result.Result[VisibilityIdiom, SemanticFailure] {
	switch value {
	case "capitalized":
		return result.Ok[VisibilityIdiom, SemanticFailure]{Value: CapitalizedVisibility{}}
	case "underscore":
		return result.Ok[VisibilityIdiom, SemanticFailure]{Value: UnderscoreVisibility{}}
	case "access-modifier":
		return result.Ok[VisibilityIdiom, SemanticFailure]{Value: AccessModifierVisibility{}}
	case "export":
		return result.Ok[VisibilityIdiom, SemanticFailure]{Value: ExportVisibility{}}
	default:
		return result.Err[VisibilityIdiom, SemanticFailure]{Err: InvalidSemantic{Field: "visibility idiom", Value: value}}
	}
}

func DocumentationFormatOf(value string) result.Result[DocumentationFormat, SemanticFailure] {
	switch value {
	case "":
		return result.Ok[DocumentationFormat, SemanticFailure]{Value: NoDocumentation{}}
	case "godoc":
		return result.Ok[DocumentationFormat, SemanticFailure]{Value: GoDoc{}}
	case "docstring":
		return result.Ok[DocumentationFormat, SemanticFailure]{Value: Docstring{}}
	case "javadoc":
		return result.Ok[DocumentationFormat, SemanticFailure]{Value: JavaDoc{}}
	case "tsdoc":
		return result.Ok[DocumentationFormat, SemanticFailure]{Value: TSDoc{}}
	default:
		return result.Err[DocumentationFormat, SemanticFailure]{Err: InvalidSemantic{Field: "documentation format", Value: value}}
	}
}

func InvocationKindOf(value string) result.Result[InvocationKind, SemanticFailure] {
	switch value {
	case "binary":
		return result.Ok[InvocationKind, SemanticFailure]{Value: BinaryInvocation{}}
	case "module":
		return result.Ok[InvocationKind, SemanticFailure]{Value: ModuleInvocation{}}
	case "class":
		return result.Ok[InvocationKind, SemanticFailure]{Value: ClassInvocation{}}
	default:
		return result.Err[InvocationKind, SemanticFailure]{Err: InvalidSemantic{Field: "invocation kind", Value: value}}
	}
}

func HierarchyNodeKindOf(value string) result.Result[HierarchyNodeKind, SemanticFailure] {
	switch value {
	case "group":
		return result.Ok[HierarchyNodeKind, SemanticFailure]{Value: GroupNode{}}
	case "package":
		return result.Ok[HierarchyNodeKind, SemanticFailure]{Value: PackageNode{}}
	default:
		return result.Err[HierarchyNodeKind, SemanticFailure]{Err: InvalidSemantic{Field: "hierarchy node kind", Value: value}}
	}
}

func ConcernKindOf(value string) result.Result[ConcernKind, SemanticFailure] {
	switch value {
	case "any":
		return result.Ok[ConcernKind, SemanticFailure]{Value: AnyConcern{}}
	case "as-any":
		return result.Ok[ConcernKind, SemanticFailure]{Value: AsAnyConcern{}}
	case "non-null-assertion":
		return result.Ok[ConcernKind, SemanticFailure]{Value: NonNullAssertionConcern{}}
	case "ts-ignore":
		return result.Ok[ConcernKind, SemanticFailure]{Value: TSIgnoreConcern{}}
	case "untyped-param":
		return result.Ok[ConcernKind, SemanticFailure]{Value: UntypedParamConcern{}}
	case "untyped-return":
		return result.Ok[ConcernKind, SemanticFailure]{Value: UntypedReturnConcern{}}
	case "loose-equality":
		return result.Ok[ConcernKind, SemanticFailure]{Value: LooseEqualityConcern{}}
	default:
		return result.Err[ConcernKind, SemanticFailure]{Err: InvalidSemantic{Field: "concern", Value: value}}
	}
}

func BoundOf(value string) result.Result[Bound, SemanticFailure] {
	if value == "O(1)" {
		return result.Ok[Bound, SemanticFailure]{Value: ConstantBound{}}
	}
	if value == "O(n)" {
		return result.Ok[Bound, SemanticFailure]{Value: LinearBound{}}
	}
	if strings.HasPrefix(value, "O(n^") && strings.HasSuffix(value, ")") {
		degree, err := strconv.Atoi(value[4 : len(value)-1])
		if err == nil && degree > 1 {
			return result.Ok[Bound, SemanticFailure]{Value: PolynomialBound{Degree: degree}}
		}
	}
	return result.Err[Bound, SemanticFailure]{Err: InvalidSemantic{Field: "complexity bound", Value: value}}
}

func ComplexityMeaning(c Complexity) result.Result[ComplexityEstimate, SemanticFailure] {
	switch c.Method {
	case "deferred":
		return result.Ok[ComplexityEstimate, SemanticFailure]{Value: ComplexityDeferred{}}
	case "recursive":
		return result.Ok[ComplexityEstimate, SemanticFailure]{Value: ComplexityRecursive{}}
	case "loop-nesting":
		if c.Time == nil || c.Space == nil {
			return result.Err[ComplexityEstimate, SemanticFailure]{Err: InvalidSemantic{Field: "complexity", Value: "missing bound"}}
		}
		time, tf := result.Unpack(BoundOf(*c.Time))
		if tf != nil {
			return result.Err[ComplexityEstimate, SemanticFailure]{Err: tf}
		}
		space, sf := result.Unpack(BoundOf(*c.Space))
		if sf != nil {
			return result.Err[ComplexityEstimate, SemanticFailure]{Err: sf}
		}
		return result.Ok[ComplexityEstimate, SemanticFailure]{Value: ComplexityLoopNesting{Time: time, Space: space}}
	default:
		return result.Err[ComplexityEstimate, SemanticFailure]{Err: InvalidSemantic{Field: "complexity method", Value: c.Method}}
	}
}

func SemanticSymbolOf(symbol Symbol) result.Result[SemanticSymbol, SemanticFailure] {
	id, idFailure := result.Unpack(NewSymbolID(symbol.ID))
	if idFailure != nil {
		return result.Err[SemanticSymbol, SemanticFailure]{Err: InvalidSemantic{Field: "symbol id", Value: symbol.ID}}
	}
	kind, kindFailure := result.Unpack(SymbolKindOf(symbol.Kind))
	if kindFailure != nil {
		return result.Err[SemanticSymbol, SemanticFailure]{Err: kindFailure}
	}
	visibility, visibilityFailure := result.Unpack(VisibilityOf(symbol.Visibility))
	if visibilityFailure != nil {
		return result.Err[SemanticSymbol, SemanticFailure]{Err: visibilityFailure}
	}
	idiom, idiomFailure := result.Unpack(VisibilityIdiomOf(symbol.VisibilityIdiom))
	if idiomFailure != nil {
		return result.Err[SemanticSymbol, SemanticFailure]{Err: idiomFailure}
	}
	file, fileFailure := result.Unpack(NewRelativeSourcePath(symbol.Location.File))
	if fileFailure != nil {
		return result.Err[SemanticSymbol, SemanticFailure]{Err: InvalidSemantic{Field: "source path", Value: symbol.Location.File}}
	}
	line, lineFailure := result.Unpack(PositiveSourceLine(symbol.Location.Line))
	if lineFailure != nil {
		return result.Err[SemanticSymbol, SemanticFailure]{Err: InvalidSemantic{Field: "source line", Value: strconv.Itoa(symbol.Location.Line)}}
	}
	column, columnFailure := result.Unpack(PositiveSourceColumn(symbol.Location.Col))
	if columnFailure != nil {
		return result.Err[SemanticSymbol, SemanticFailure]{Err: InvalidSemantic{Field: "source column", Value: strconv.Itoa(symbol.Location.Col)}}
	}
	documentation, docFailure := result.Unpack(DocumentationFormatOf(symbol.Doc.Format))
	if docFailure != nil {
		return result.Err[SemanticSymbol, SemanticFailure]{Err: docFailure}
	}
	complexity, complexityFailure := result.Unpack(ComplexityMeaning(symbol.Complexity))
	if complexityFailure != nil {
		return result.Err[SemanticSymbol, SemanticFailure]{Err: complexityFailure}
	}
	var invocation InvocationMeaning = NotInvokable{}
	if symbol.Invocation != nil {
		invocationKind, invocationFailure := result.Unpack(InvocationKindOf(symbol.Invocation.Kind))
		if invocationFailure != nil {
			return result.Err[SemanticSymbol, SemanticFailure]{Err: invocationFailure}
		}
		invocation = Invokable{Kind: invocationKind, How: symbol.Invocation.How}
	}
	concerns := make([]ConcernKind, len(symbol.Concerns))
	for i, raw := range symbol.Concerns {
		concern, failure := result.Unpack(ConcernKindOf(raw))
		if failure != nil {
			return result.Err[SemanticSymbol, SemanticFailure]{Err: failure}
		}
		concerns[i] = concern
	}
	calls := make([]SemanticCall, len(symbol.Calls))
	for i, raw := range symbol.Calls {
		resolution, failure := result.Unpack(CallResolutionOf(raw))
		if failure != nil {
			return result.Err[SemanticSymbol, SemanticFailure]{Err: failure}
		}
		count, countFailure := result.Unpack(PositiveCallCount(raw.Count))
		if countFailure != nil {
			return result.Err[SemanticSymbol, SemanticFailure]{Err: InvalidSemantic{Field: "call count", Value: strconv.Itoa(raw.Count)}}
		}
		var arity *Arity
		if raw.Arity != nil {
			value, arityFailure := result.Unpack(NonnegativeArity(*raw.Arity))
			if arityFailure != nil {
				return result.Err[SemanticSymbol, SemanticFailure]{Err: InvalidSemantic{Field: "arity", Value: strconv.Itoa(*raw.Arity)}}
			}
			arity = &value
		}
		calls[i] = SemanticCall{Target: raw.Target, Resolution: resolution, Arity: arity, Evidence: EvidenceOf(raw.ArgTypes), Count: count}
	}
	return result.Ok[SemanticSymbol, SemanticFailure]{Value: SemanticSymbol{
		ID: id, Kind: kind, Visibility: visibility, VisibilityIdiom: idiom,
		File: file, Line: line, Column: column, Documentation: documentation,
		Invocation: invocation, Complexity: complexity, Concerns: concerns, Calls: calls,
	}}
}

func SemanticPackageOf(pkg Package) result.Result[SemanticPackage, SemanticFailure] {
	id, idFailure := result.Unpack(NewPackageID(pkg.ID))
	if idFailure != nil {
		return result.Err[SemanticPackage, SemanticFailure]{Err: InvalidSemantic{Field: "package id", Value: pkg.ID}}
	}
	language, languageFailure := result.Unpack(LanguageOf(pkg.Language))
	if languageFailure != nil {
		return result.Err[SemanticPackage, SemanticFailure]{Err: languageFailure}
	}
	symbols := make([]SemanticSymbol, len(pkg.Symbols))
	for i, raw := range pkg.Symbols {
		symbol, failure := result.Unpack(SemanticSymbolOf(raw))
		if failure != nil {
			return result.Err[SemanticPackage, SemanticFailure]{Err: failure}
		}
		symbols[i] = symbol
	}
	return result.Ok[SemanticPackage, SemanticFailure]{Value: SemanticPackage{ID: id, Language: language, Symbols: symbols}}
}
