// Code generated by goplus from trace.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package schema keeps trace identity separate from source location. A move
// changes Location but does not change Artifact.ID.
package schema

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/url"
	"sort"
	"strings"

	"goforge.dev/goplus/std/option"
	"goforge.dev/goplus/std/result"
)

const TraceSchema = "assayxport.trace/v3"
const UnitDirective = "assayxport:unit "

//goplus:enum ArtifactKind
type ArtifactKind interface{ isArtifactKind() }

//goplus:variant (ArtifactKind) SpecificationArtifact()
type SpecificationArtifact struct{}

func (SpecificationArtifact) isArtifactKind() {}

//goplus:variant (ArtifactKind) TutorialArtifact()
type TutorialArtifact struct{}

func (TutorialArtifact) isArtifactKind() {}

//goplus:variant (ArtifactKind) HowToArtifact()
type HowToArtifact struct{}

func (HowToArtifact) isArtifactKind() {}

//goplus:variant (ArtifactKind) ReferenceArtifact()
type ReferenceArtifact struct{}

func (ReferenceArtifact) isArtifactKind() {}

//goplus:variant (ArtifactKind) ExplanationArtifact()
type ExplanationArtifact struct{}

func (ExplanationArtifact) isArtifactKind() {}

//goplus:variant (ArtifactKind) ReleaseNoteArtifact()
type ReleaseNoteArtifact struct{}

func (ReleaseNoteArtifact) isArtifactKind() {}

//goplus:variant (ArtifactKind) DecisionArtifact()
type DecisionArtifact struct{}

func (DecisionArtifact) isArtifactKind() {}

//goplus:variant (ArtifactKind) CodeArtifact()
type CodeArtifact struct{}

func (CodeArtifact) isArtifactKind() {}

//goplus:variant (ArtifactKind) GeneratedArtifact()
type GeneratedArtifact struct{}

func (GeneratedArtifact) isArtifactKind() {}

//goplus:variant (ArtifactKind) ExampleArtifact()
type ExampleArtifact struct{}

func (ExampleArtifact) isArtifactKind() {}

//goplus:variant (ArtifactKind) LawArtifact()
type LawArtifact struct{}

func (LawArtifact) isArtifactKind() {}

//goplus:variant (ArtifactKind) DifferentialArtifact()
type DifferentialArtifact struct{}

func (DifferentialArtifact) isArtifactKind() {}

//goplus:variant (ArtifactKind) FuzzArtifact()
type FuzzArtifact struct{}

func (FuzzArtifact) isArtifactKind() {}

//goplus:variant (ArtifactKind) BenchmarkArtifact()
type BenchmarkArtifact struct{}

func (BenchmarkArtifact) isArtifactKind() {}

//goplus:variant (ArtifactKind) ExternalArtifact()
type ExternalArtifact struct{}

func (ExternalArtifact) isArtifactKind() {}

// ArtifactKindCases selects one handler per ArtifactKind variant for ArtifactKindFold.
type ArtifactKindCases[R any] struct {
	SpecificationArtifact func() R
	TutorialArtifact      func() R
	HowToArtifact         func() R
	ReferenceArtifact     func() R
	ExplanationArtifact   func() R
	ReleaseNoteArtifact   func() R
	DecisionArtifact      func() R
	CodeArtifact          func() R
	GeneratedArtifact     func() R
	ExampleArtifact       func() R
	LawArtifact           func() R
	DifferentialArtifact  func() R
	FuzzArtifact          func() R
	BenchmarkArtifact     func() R
	ExternalArtifact      func() R
}

// ArtifactKindFold reduces ArtifactKind by one-level case analysis.
func ArtifactKindFold[R any](a ArtifactKind, cs ArtifactKindCases[R]) R {
	switch any(a).(type) {
	case SpecificationArtifact:
		return cs.SpecificationArtifact()
	case TutorialArtifact:
		return cs.TutorialArtifact()
	case HowToArtifact:
		return cs.HowToArtifact()
	case ReferenceArtifact:
		return cs.ReferenceArtifact()
	case ExplanationArtifact:
		return cs.ExplanationArtifact()
	case ReleaseNoteArtifact:
		return cs.ReleaseNoteArtifact()
	case DecisionArtifact:
		return cs.DecisionArtifact()
	case CodeArtifact:
		return cs.CodeArtifact()
	case GeneratedArtifact:
		return cs.GeneratedArtifact()
	case ExampleArtifact:
		return cs.ExampleArtifact()
	case LawArtifact:
		return cs.LawArtifact()
	case DifferentialArtifact:
		return cs.DifferentialArtifact()
	case FuzzArtifact:
		return cs.FuzzArtifact()
	case BenchmarkArtifact:
		return cs.BenchmarkArtifact()
	case ExternalArtifact:
		return cs.ExternalArtifact()
	default:
		panic("goplus: impossible enum value in ArtifactKindFold")
	}
}

// ArtifactKindEqOverrides carries optional per-variant hooks for ArtifactKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type ArtifactKindEqOverrides struct {
	SpecificationArtifact func(x, y SpecificationArtifact) (eq, handled bool)
	TutorialArtifact      func(x, y TutorialArtifact) (eq, handled bool)
	HowToArtifact         func(x, y HowToArtifact) (eq, handled bool)
	ReferenceArtifact     func(x, y ReferenceArtifact) (eq, handled bool)
	ExplanationArtifact   func(x, y ExplanationArtifact) (eq, handled bool)
	ReleaseNoteArtifact   func(x, y ReleaseNoteArtifact) (eq, handled bool)
	DecisionArtifact      func(x, y DecisionArtifact) (eq, handled bool)
	CodeArtifact          func(x, y CodeArtifact) (eq, handled bool)
	GeneratedArtifact     func(x, y GeneratedArtifact) (eq, handled bool)
	ExampleArtifact       func(x, y ExampleArtifact) (eq, handled bool)
	LawArtifact           func(x, y LawArtifact) (eq, handled bool)
	DifferentialArtifact  func(x, y DifferentialArtifact) (eq, handled bool)
	FuzzArtifact          func(x, y FuzzArtifact) (eq, handled bool)
	BenchmarkArtifact     func(x, y BenchmarkArtifact) (eq, handled bool)
	ExternalArtifact      func(x, y ExternalArtifact) (eq, handled bool)
}

// ArtifactKindEqualWith reports structural equality of a and b under ov.
func ArtifactKindEqualWith(a, b ArtifactKind, ov ArtifactKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case SpecificationArtifact:
		y, ok := any(b).(SpecificationArtifact)
		if !ok {
			return false
		}
		if ov.SpecificationArtifact != nil {
			if eq, handled := ov.SpecificationArtifact(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case TutorialArtifact:
		y, ok := any(b).(TutorialArtifact)
		if !ok {
			return false
		}
		if ov.TutorialArtifact != nil {
			if eq, handled := ov.TutorialArtifact(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case HowToArtifact:
		y, ok := any(b).(HowToArtifact)
		if !ok {
			return false
		}
		if ov.HowToArtifact != nil {
			if eq, handled := ov.HowToArtifact(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ReferenceArtifact:
		y, ok := any(b).(ReferenceArtifact)
		if !ok {
			return false
		}
		if ov.ReferenceArtifact != nil {
			if eq, handled := ov.ReferenceArtifact(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ExplanationArtifact:
		y, ok := any(b).(ExplanationArtifact)
		if !ok {
			return false
		}
		if ov.ExplanationArtifact != nil {
			if eq, handled := ov.ExplanationArtifact(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ReleaseNoteArtifact:
		y, ok := any(b).(ReleaseNoteArtifact)
		if !ok {
			return false
		}
		if ov.ReleaseNoteArtifact != nil {
			if eq, handled := ov.ReleaseNoteArtifact(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case DecisionArtifact:
		y, ok := any(b).(DecisionArtifact)
		if !ok {
			return false
		}
		if ov.DecisionArtifact != nil {
			if eq, handled := ov.DecisionArtifact(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case CodeArtifact:
		y, ok := any(b).(CodeArtifact)
		if !ok {
			return false
		}
		if ov.CodeArtifact != nil {
			if eq, handled := ov.CodeArtifact(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case GeneratedArtifact:
		y, ok := any(b).(GeneratedArtifact)
		if !ok {
			return false
		}
		if ov.GeneratedArtifact != nil {
			if eq, handled := ov.GeneratedArtifact(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ExampleArtifact:
		y, ok := any(b).(ExampleArtifact)
		if !ok {
			return false
		}
		if ov.ExampleArtifact != nil {
			if eq, handled := ov.ExampleArtifact(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case LawArtifact:
		y, ok := any(b).(LawArtifact)
		if !ok {
			return false
		}
		if ov.LawArtifact != nil {
			if eq, handled := ov.LawArtifact(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case DifferentialArtifact:
		y, ok := any(b).(DifferentialArtifact)
		if !ok {
			return false
		}
		if ov.DifferentialArtifact != nil {
			if eq, handled := ov.DifferentialArtifact(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case FuzzArtifact:
		y, ok := any(b).(FuzzArtifact)
		if !ok {
			return false
		}
		if ov.FuzzArtifact != nil {
			if eq, handled := ov.FuzzArtifact(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case BenchmarkArtifact:
		y, ok := any(b).(BenchmarkArtifact)
		if !ok {
			return false
		}
		if ov.BenchmarkArtifact != nil {
			if eq, handled := ov.BenchmarkArtifact(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ExternalArtifact:
		y, ok := any(b).(ExternalArtifact)
		if !ok {
			return false
		}
		if ov.ExternalArtifact != nil {
			if eq, handled := ov.ExternalArtifact(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// ArtifactKindEqual reports structural equality of a and b.
func ArtifactKindEqual(a, b ArtifactKind) bool {
	return ArtifactKindEqualWith(a, b, ArtifactKindEqOverrides{})
}

//goplus:enum RelationKind
type RelationKind interface{ isRelationKind() }

//goplus:variant (RelationKind) SpecifiesRelation()
type SpecifiesRelation struct{}

func (SpecifiesRelation) isRelationKind() {}

//goplus:variant (RelationKind) DocumentsRelation()
type DocumentsRelation struct{}

func (DocumentsRelation) isRelationKind() {}

//goplus:variant (RelationKind) AnnouncesRelation()
type AnnouncesRelation struct{}

func (AnnouncesRelation) isRelationKind() {}

//goplus:variant (RelationKind) DecidesRelation()
type DecidesRelation struct{}

func (DecidesRelation) isRelationKind() {}

//goplus:variant (RelationKind) ImplementsRelation()
type ImplementsRelation struct{}

func (ImplementsRelation) isRelationKind() {}

//goplus:variant (RelationKind) TestsRelation()
type TestsRelation struct{}

func (TestsRelation) isRelationKind() {}

//goplus:variant (RelationKind) ExamplesRelation()
type ExamplesRelation struct{}

func (ExamplesRelation) isRelationKind() {}

//goplus:variant (RelationKind) GeneratesRelation()
type GeneratesRelation struct{}

func (GeneratesRelation) isRelationKind() {}

//goplus:variant (RelationKind) SupersedesRelation()
type SupersedesRelation struct{}

func (SupersedesRelation) isRelationKind() {}

//goplus:variant (RelationKind) DerivedFromRelation()
type DerivedFromRelation struct{}

func (DerivedFromRelation) isRelationKind() {}

// RelationKindCases selects one handler per RelationKind variant for RelationKindFold.
type RelationKindCases[R any] struct {
	SpecifiesRelation   func() R
	DocumentsRelation   func() R
	AnnouncesRelation   func() R
	DecidesRelation     func() R
	ImplementsRelation  func() R
	TestsRelation       func() R
	ExamplesRelation    func() R
	GeneratesRelation   func() R
	SupersedesRelation  func() R
	DerivedFromRelation func() R
}

// RelationKindFold reduces RelationKind by one-level case analysis.
func RelationKindFold[R any](v RelationKind, cs RelationKindCases[R]) R {
	switch any(v).(type) {
	case SpecifiesRelation:
		return cs.SpecifiesRelation()
	case DocumentsRelation:
		return cs.DocumentsRelation()
	case AnnouncesRelation:
		return cs.AnnouncesRelation()
	case DecidesRelation:
		return cs.DecidesRelation()
	case ImplementsRelation:
		return cs.ImplementsRelation()
	case TestsRelation:
		return cs.TestsRelation()
	case ExamplesRelation:
		return cs.ExamplesRelation()
	case GeneratesRelation:
		return cs.GeneratesRelation()
	case SupersedesRelation:
		return cs.SupersedesRelation()
	case DerivedFromRelation:
		return cs.DerivedFromRelation()
	default:
		panic("goplus: impossible enum value in RelationKindFold")
	}
}

// RelationKindEqOverrides carries optional per-variant hooks for RelationKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type RelationKindEqOverrides struct {
	SpecifiesRelation   func(x, y SpecifiesRelation) (eq, handled bool)
	DocumentsRelation   func(x, y DocumentsRelation) (eq, handled bool)
	AnnouncesRelation   func(x, y AnnouncesRelation) (eq, handled bool)
	DecidesRelation     func(x, y DecidesRelation) (eq, handled bool)
	ImplementsRelation  func(x, y ImplementsRelation) (eq, handled bool)
	TestsRelation       func(x, y TestsRelation) (eq, handled bool)
	ExamplesRelation    func(x, y ExamplesRelation) (eq, handled bool)
	GeneratesRelation   func(x, y GeneratesRelation) (eq, handled bool)
	SupersedesRelation  func(x, y SupersedesRelation) (eq, handled bool)
	DerivedFromRelation func(x, y DerivedFromRelation) (eq, handled bool)
}

// RelationKindEqualWith reports structural equality of a and b under ov.
func RelationKindEqualWith(a, b RelationKind, ov RelationKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case SpecifiesRelation:
		y, ok := any(b).(SpecifiesRelation)
		if !ok {
			return false
		}
		if ov.SpecifiesRelation != nil {
			if eq, handled := ov.SpecifiesRelation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case DocumentsRelation:
		y, ok := any(b).(DocumentsRelation)
		if !ok {
			return false
		}
		if ov.DocumentsRelation != nil {
			if eq, handled := ov.DocumentsRelation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case AnnouncesRelation:
		y, ok := any(b).(AnnouncesRelation)
		if !ok {
			return false
		}
		if ov.AnnouncesRelation != nil {
			if eq, handled := ov.AnnouncesRelation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case DecidesRelation:
		y, ok := any(b).(DecidesRelation)
		if !ok {
			return false
		}
		if ov.DecidesRelation != nil {
			if eq, handled := ov.DecidesRelation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ImplementsRelation:
		y, ok := any(b).(ImplementsRelation)
		if !ok {
			return false
		}
		if ov.ImplementsRelation != nil {
			if eq, handled := ov.ImplementsRelation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case TestsRelation:
		y, ok := any(b).(TestsRelation)
		if !ok {
			return false
		}
		if ov.TestsRelation != nil {
			if eq, handled := ov.TestsRelation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ExamplesRelation:
		y, ok := any(b).(ExamplesRelation)
		if !ok {
			return false
		}
		if ov.ExamplesRelation != nil {
			if eq, handled := ov.ExamplesRelation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case GeneratesRelation:
		y, ok := any(b).(GeneratesRelation)
		if !ok {
			return false
		}
		if ov.GeneratesRelation != nil {
			if eq, handled := ov.GeneratesRelation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case SupersedesRelation:
		y, ok := any(b).(SupersedesRelation)
		if !ok {
			return false
		}
		if ov.SupersedesRelation != nil {
			if eq, handled := ov.SupersedesRelation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case DerivedFromRelation:
		y, ok := any(b).(DerivedFromRelation)
		if !ok {
			return false
		}
		if ov.DerivedFromRelation != nil {
			if eq, handled := ov.DerivedFromRelation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// RelationKindEqual reports structural equality of a and b.
func RelationKindEqual(a, b RelationKind) bool {
	return RelationKindEqualWith(a, b, RelationKindEqOverrides{})
}

type ArtifactID struct{ value string }

type TraceArtifact struct {
	ID             string    `json:"id"`
	Kind           string    `json:"kind"`
	Module         string    `json:"module"`
	Version        string    `json:"version,omitempty"`
	Location       *Location `json:"location,omitempty"`
	SemanticDigest string    `json:"semantic_digest,omitempty"`
	ContentDigest  string    `json:"content_digest"`
	PublicAPI      string    `json:"public_api,omitempty"`
	Deployable     bool      `json:"deployable,omitempty"`
	Generated      bool      `json:"generated,omitempty"`
	Provenance     []string  `json:"provenance,omitempty"`
	Generator      string    `json:"generator,omitempty"`
}

type TraceRelation struct {
	From string `json:"from"`
	Kind string `json:"kind"`
	To   string `json:"to"`
}

type TraceBundle struct {
	SchemaVersion string          `json:"schema_version"`
	Module        string          `json:"module"`
	Version       string          `json:"version,omitempty"`
	Artifacts     []TraceArtifact `json:"artifacts"`
	Relations     []TraceRelation `json:"relations"`
}

//goplus:enum TraceValidation
type TraceValidation interface{ isTraceValidation() }

//goplus:variant (TraceValidation) TraceValid()
type TraceValid struct{}

func (TraceValid) isTraceValidation() {}

// TraceValidationCases selects one handler per TraceValidation variant for TraceValidationFold.
type TraceValidationCases[R any] struct {
	TraceValid func() R
}

// TraceValidationFold reduces TraceValidation by one-level case analysis.
func TraceValidationFold[R any](t TraceValidation, cs TraceValidationCases[R]) R {
	switch any(t).(type) {
	case TraceValid:
		return cs.TraceValid()
	default:
		panic("goplus: impossible enum value in TraceValidationFold")
	}
}

// TraceValidationEqOverrides carries optional per-variant hooks for TraceValidationEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type TraceValidationEqOverrides struct {
	TraceValid func(x, y TraceValid) (eq, handled bool)
}

// TraceValidationEqualWith reports structural equality of a and b under ov.
func TraceValidationEqualWith(a, b TraceValidation, ov TraceValidationEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case TraceValid:
		y, ok := any(b).(TraceValid)
		if !ok {
			return false
		}
		if ov.TraceValid != nil {
			if eq, handled := ov.TraceValid(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// TraceValidationEqual reports structural equality of a and b.
func TraceValidationEqual(a, b TraceValidation) bool {
	return TraceValidationEqualWith(a, b, TraceValidationEqOverrides{})
}

type TraceReport struct {
	Changed []string `json:"changed"`
	Missing []string `json:"missing"`
}

//goplus:enum TraceFailure
type TraceFailure interface{ isTraceFailure() }

//goplus:variant (TraceFailure) UnsupportedTraceSchema(Found string)
type UnsupportedTraceSchema struct {
	Found string
}

func (UnsupportedTraceSchema) isTraceFailure() {}

//goplus:variant (TraceFailure) InvalidArtifactIdentity(Value string)
type InvalidArtifactIdentity struct {
	Value string
}

func (InvalidArtifactIdentity) isTraceFailure() {}

//goplus:variant (TraceFailure) DuplicateArtifactIdentity(Value string)
type DuplicateArtifactIdentity struct {
	Value string
}

func (DuplicateArtifactIdentity) isTraceFailure() {}

//goplus:variant (TraceFailure) UnknownArtifactKind(Value string)
type UnknownArtifactKind struct {
	Value string
}

func (UnknownArtifactKind) isTraceFailure() {}

//goplus:variant (TraceFailure) UnknownRelationKind(Value string)
type UnknownRelationKind struct {
	Value string
}

func (UnknownRelationKind) isTraceFailure() {}

//goplus:variant (TraceFailure) InvalidTraceDigest(Artifact string, Field string)
type InvalidTraceDigest struct {
	Artifact string
	Field    string
}

func (InvalidTraceDigest) isTraceFailure() {}

//goplus:variant (TraceFailure) InvalidDeployableKind(Artifact string)
type InvalidDeployableKind struct {
	Artifact string
}

func (InvalidDeployableKind) isTraceFailure() {}

//goplus:variant (TraceFailure) MissingArtifactEndpoint(Relation string, Endpoint string)
type MissingArtifactEndpoint struct {
	Relation string
	Endpoint string
}

func (MissingArtifactEndpoint) isTraceFailure() {}

//goplus:variant (TraceFailure) InvalidDecisionSource(Artifact string)
type InvalidDecisionSource struct {
	Artifact string
}

func (InvalidDecisionSource) isTraceFailure() {}

//goplus:variant (TraceFailure) UndecidedCode(Artifact string)
type UndecidedCode struct {
	Artifact string
}

func (UndecidedCode) isTraceFailure() {}

//goplus:variant (TraceFailure) UnderivedGeneratedCode(Artifact string)
type UnderivedGeneratedCode struct {
	Artifact string
}

func (UnderivedGeneratedCode) isTraceFailure() {}

//goplus:variant (TraceFailure) MissingReleaseNote(Artifact string)
type MissingReleaseNote struct {
	Artifact string
}

func (MissingReleaseNote) isTraceFailure() {}

//goplus:variant (TraceFailure) UnreasonedChange(Artifact string)
type UnreasonedChange struct {
	Artifact string
}

func (UnreasonedChange) isTraceFailure() {}

//goplus:variant (TraceFailure) InvalidTraceJSON(Cause error)
type InvalidTraceJSON struct {
	Cause error
}

func (InvalidTraceJSON) isTraceFailure() {}

// TraceFailureCases selects one handler per TraceFailure variant for TraceFailureFold.
type TraceFailureCases[R any] struct {
	UnsupportedTraceSchema    func(Found string) R
	InvalidArtifactIdentity   func(Value string) R
	DuplicateArtifactIdentity func(Value string) R
	UnknownArtifactKind       func(Value string) R
	UnknownRelationKind       func(Value string) R
	InvalidTraceDigest        func(Artifact string, Field string) R
	InvalidDeployableKind     func(Artifact string) R
	MissingArtifactEndpoint   func(Relation string, Endpoint string) R
	InvalidDecisionSource     func(Artifact string) R
	UndecidedCode             func(Artifact string) R
	UnderivedGeneratedCode    func(Artifact string) R
	MissingReleaseNote        func(Artifact string) R
	UnreasonedChange          func(Artifact string) R
	InvalidTraceJSON          func(Cause error) R
}

// TraceFailureFold reduces TraceFailure by one-level case analysis.
func TraceFailureFold[R any](t TraceFailure, cs TraceFailureCases[R]) R {
	switch m := any(t).(type) {
	case UnsupportedTraceSchema:
		return cs.UnsupportedTraceSchema(m.Found)
	case InvalidArtifactIdentity:
		return cs.InvalidArtifactIdentity(m.Value)
	case DuplicateArtifactIdentity:
		return cs.DuplicateArtifactIdentity(m.Value)
	case UnknownArtifactKind:
		return cs.UnknownArtifactKind(m.Value)
	case UnknownRelationKind:
		return cs.UnknownRelationKind(m.Value)
	case InvalidTraceDigest:
		return cs.InvalidTraceDigest(m.Artifact, m.Field)
	case InvalidDeployableKind:
		return cs.InvalidDeployableKind(m.Artifact)
	case MissingArtifactEndpoint:
		return cs.MissingArtifactEndpoint(m.Relation, m.Endpoint)
	case InvalidDecisionSource:
		return cs.InvalidDecisionSource(m.Artifact)
	case UndecidedCode:
		return cs.UndecidedCode(m.Artifact)
	case UnderivedGeneratedCode:
		return cs.UnderivedGeneratedCode(m.Artifact)
	case MissingReleaseNote:
		return cs.MissingReleaseNote(m.Artifact)
	case UnreasonedChange:
		return cs.UnreasonedChange(m.Artifact)
	case InvalidTraceJSON:
		return cs.InvalidTraceJSON(m.Cause)
	default:
		panic("goplus: impossible enum value in TraceFailureFold")
	}
}

// TraceFailureEqOverrides carries optional per-variant hooks for TraceFailureEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type TraceFailureEqOverrides struct {
	UnsupportedTraceSchema    func(x, y UnsupportedTraceSchema) (eq, handled bool)
	InvalidArtifactIdentity   func(x, y InvalidArtifactIdentity) (eq, handled bool)
	DuplicateArtifactIdentity func(x, y DuplicateArtifactIdentity) (eq, handled bool)
	UnknownArtifactKind       func(x, y UnknownArtifactKind) (eq, handled bool)
	UnknownRelationKind       func(x, y UnknownRelationKind) (eq, handled bool)
	InvalidTraceDigest        func(x, y InvalidTraceDigest) (eq, handled bool)
	InvalidDeployableKind     func(x, y InvalidDeployableKind) (eq, handled bool)
	MissingArtifactEndpoint   func(x, y MissingArtifactEndpoint) (eq, handled bool)
	InvalidDecisionSource     func(x, y InvalidDecisionSource) (eq, handled bool)
	UndecidedCode             func(x, y UndecidedCode) (eq, handled bool)
	UnderivedGeneratedCode    func(x, y UnderivedGeneratedCode) (eq, handled bool)
	MissingReleaseNote        func(x, y MissingReleaseNote) (eq, handled bool)
	UnreasonedChange          func(x, y UnreasonedChange) (eq, handled bool)
	InvalidTraceJSON          func(x, y InvalidTraceJSON) (eq, handled bool)
}

// TraceFailureEqualWith reports structural equality of a and b under ov.
func TraceFailureEqualWith(a, b TraceFailure, ov TraceFailureEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case UnsupportedTraceSchema:
		y, ok := any(b).(UnsupportedTraceSchema)
		if !ok {
			return false
		}
		if ov.UnsupportedTraceSchema != nil {
			if eq, handled := ov.UnsupportedTraceSchema(x, y); handled {
				return eq
			}
		}
		if x.Found != y.Found {
			return false
		}
		return true
	case InvalidArtifactIdentity:
		y, ok := any(b).(InvalidArtifactIdentity)
		if !ok {
			return false
		}
		if ov.InvalidArtifactIdentity != nil {
			if eq, handled := ov.InvalidArtifactIdentity(x, y); handled {
				return eq
			}
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case DuplicateArtifactIdentity:
		y, ok := any(b).(DuplicateArtifactIdentity)
		if !ok {
			return false
		}
		if ov.DuplicateArtifactIdentity != nil {
			if eq, handled := ov.DuplicateArtifactIdentity(x, y); handled {
				return eq
			}
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case UnknownArtifactKind:
		y, ok := any(b).(UnknownArtifactKind)
		if !ok {
			return false
		}
		if ov.UnknownArtifactKind != nil {
			if eq, handled := ov.UnknownArtifactKind(x, y); handled {
				return eq
			}
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case UnknownRelationKind:
		y, ok := any(b).(UnknownRelationKind)
		if !ok {
			return false
		}
		if ov.UnknownRelationKind != nil {
			if eq, handled := ov.UnknownRelationKind(x, y); handled {
				return eq
			}
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case InvalidTraceDigest:
		y, ok := any(b).(InvalidTraceDigest)
		if !ok {
			return false
		}
		if ov.InvalidTraceDigest != nil {
			if eq, handled := ov.InvalidTraceDigest(x, y); handled {
				return eq
			}
		}
		if x.Artifact != y.Artifact {
			return false
		}
		if x.Field != y.Field {
			return false
		}
		return true
	case InvalidDeployableKind:
		y, ok := any(b).(InvalidDeployableKind)
		if !ok {
			return false
		}
		if ov.InvalidDeployableKind != nil {
			if eq, handled := ov.InvalidDeployableKind(x, y); handled {
				return eq
			}
		}
		if x.Artifact != y.Artifact {
			return false
		}
		return true
	case MissingArtifactEndpoint:
		y, ok := any(b).(MissingArtifactEndpoint)
		if !ok {
			return false
		}
		if ov.MissingArtifactEndpoint != nil {
			if eq, handled := ov.MissingArtifactEndpoint(x, y); handled {
				return eq
			}
		}
		if x.Relation != y.Relation {
			return false
		}
		if x.Endpoint != y.Endpoint {
			return false
		}
		return true
	case InvalidDecisionSource:
		y, ok := any(b).(InvalidDecisionSource)
		if !ok {
			return false
		}
		if ov.InvalidDecisionSource != nil {
			if eq, handled := ov.InvalidDecisionSource(x, y); handled {
				return eq
			}
		}
		if x.Artifact != y.Artifact {
			return false
		}
		return true
	case UndecidedCode:
		y, ok := any(b).(UndecidedCode)
		if !ok {
			return false
		}
		if ov.UndecidedCode != nil {
			if eq, handled := ov.UndecidedCode(x, y); handled {
				return eq
			}
		}
		if x.Artifact != y.Artifact {
			return false
		}
		return true
	case UnderivedGeneratedCode:
		y, ok := any(b).(UnderivedGeneratedCode)
		if !ok {
			return false
		}
		if ov.UnderivedGeneratedCode != nil {
			if eq, handled := ov.UnderivedGeneratedCode(x, y); handled {
				return eq
			}
		}
		if x.Artifact != y.Artifact {
			return false
		}
		return true
	case MissingReleaseNote:
		y, ok := any(b).(MissingReleaseNote)
		if !ok {
			return false
		}
		if ov.MissingReleaseNote != nil {
			if eq, handled := ov.MissingReleaseNote(x, y); handled {
				return eq
			}
		}
		if x.Artifact != y.Artifact {
			return false
		}
		return true
	case UnreasonedChange:
		y, ok := any(b).(UnreasonedChange)
		if !ok {
			return false
		}
		if ov.UnreasonedChange != nil {
			if eq, handled := ov.UnreasonedChange(x, y); handled {
				return eq
			}
		}
		if x.Artifact != y.Artifact {
			return false
		}
		return true
	case InvalidTraceJSON:
		y, ok := any(b).(InvalidTraceJSON)
		if !ok {
			return false
		}
		if ov.InvalidTraceJSON != nil {
			if eq, handled := ov.InvalidTraceJSON(x, y); handled {
				return eq
			}
		}
		if (x.Cause == nil) != (y.Cause == nil) {
			return false
		}
		if x.Cause != nil && x.Cause.Error() != y.Cause.Error() {
			return false
		}
		return true
	}
	return false
}

// TraceFailureEqual reports structural equality of a and b.
func TraceFailureEqual(a, b TraceFailure) bool {
	return TraceFailureEqualWith(a, b, TraceFailureEqOverrides{})
}

//goplus:method (TraceFailure) Error
func Error(failure TraceFailure) string {
	switch __gp_m0 := any(failure).(type) {
	case UnsupportedTraceSchema:
		found := __gp_m0.Found

		return fmt.Sprintf("trace: unsupported schema %q", found)
	case InvalidArtifactIdentity:
		value := __gp_m0.Value

		return fmt.Sprintf("trace: invalid artifact id %q", value)
	case DuplicateArtifactIdentity:
		value := __gp_m0.Value

		return fmt.Sprintf("trace: duplicate artifact id %q", value)
	case UnknownArtifactKind:
		value := __gp_m0.Value

		return fmt.Sprintf("trace: unknown artifact kind %q", value)
	case UnknownRelationKind:
		value := __gp_m0.Value

		return fmt.Sprintf("trace: unknown relation kind %q", value)
	case InvalidTraceDigest:
		artifact := __gp_m0.Artifact
		field := __gp_m0.Field

		return fmt.Sprintf("trace: artifact %s has an invalid %s digest", artifact, field)
	case InvalidDeployableKind:
		artifact := __gp_m0.Artifact

		return fmt.Sprintf("trace: deployable artifact %s is not code", artifact)
	case MissingArtifactEndpoint:
		relation := __gp_m0.Relation
		endpoint := __gp_m0.Endpoint

		return fmt.Sprintf("trace: relation %s references missing %s", relation, endpoint)
	case InvalidDecisionSource:
		artifact := __gp_m0.Artifact

		return fmt.Sprintf("trace: decides source %s is not an ADR", artifact)
	case UndecidedCode:
		artifact := __gp_m0.Artifact

		return fmt.Sprintf("trace: deployable code %s has no governing ADR", artifact)
	case UnderivedGeneratedCode:
		artifact := __gp_m0.Artifact

		return fmt.Sprintf("trace: generated code %s has no generator relation", artifact)
	case MissingReleaseNote:
		artifact := __gp_m0.Artifact

		return fmt.Sprintf("trace: release note %s is missing or has the wrong kind", artifact)
	case UnreasonedChange:
		artifact := __gp_m0.Artifact

		return fmt.Sprintf("trace: changed deployable unit %s has no release-note to ADR closure", artifact)
	case InvalidTraceJSON:
		cause := __gp_m0.Cause

		return fmt.Sprintf("trace: invalid JSON: %v", cause)
	default:
		panic("goplus: impossible enum value in match")
	}
}

// assayxport:unit schema.trace.artifact-id
func NewArtifactID(value string) result.Result[ArtifactID, TraceFailure] {
	if value == "" {
		return result.Err[ArtifactID, TraceFailure]{Err: InvalidArtifactIdentity{Value: value}}
	}
	for _, character := range value {
		switch {
		case character >= 'a' && character <= 'z':
		case character >= 'A' && character <= 'Z':
		case character >= '0' && character <= '9':
		case character == '.', character == '-', character == '_', character == ':':
		default:
			return result.Err[ArtifactID, TraceFailure]{Err: InvalidArtifactIdentity{Value: value}}
		}
	}
	return result.Ok[ArtifactID, TraceFailure]{Value: ArtifactID{value: value}}
}

func ArtifactIDString(id ArtifactID) string { return id.value }

func ArtifactKindString(kind ArtifactKind) string {
	switch any(kind).(type) {
	case SpecificationArtifact:
		return "specification"
	case TutorialArtifact:
		return "tutorial"
	case HowToArtifact:
		return "how-to"
	case ReferenceArtifact:
		return "reference"
	case ExplanationArtifact:
		return "explanation"
	case ReleaseNoteArtifact:
		return "release-note"
	case DecisionArtifact:
		return "adr"
	case CodeArtifact:
		return "code"
	case GeneratedArtifact:
		return "generated"
	case ExampleArtifact:
		return "example"
	case LawArtifact:
		return "law"
	case DifferentialArtifact:
		return "differential"
	case FuzzArtifact:
		return "fuzz"
	case BenchmarkArtifact:
		return "benchmark"
	case ExternalArtifact:
		return "external"
	default:
		panic("goplus: impossible enum value in match")
	}
}

func ParseArtifactKind(value string) option.Option[ArtifactKind] {
	switch value {
	case "specification":
		return option.Some[ArtifactKind]{Value: SpecificationArtifact{}}
	case "tutorial":
		return option.Some[ArtifactKind]{Value: TutorialArtifact{}}
	case "how-to":
		return option.Some[ArtifactKind]{Value: HowToArtifact{}}
	case "reference":
		return option.Some[ArtifactKind]{Value: ReferenceArtifact{}}
	case "explanation":
		return option.Some[ArtifactKind]{Value: ExplanationArtifact{}}
	case "release-note":
		return option.Some[ArtifactKind]{Value: ReleaseNoteArtifact{}}
	case "adr":
		return option.Some[ArtifactKind]{Value: DecisionArtifact{}}
	case "code":
		return option.Some[ArtifactKind]{Value: CodeArtifact{}}
	case "generated":
		return option.Some[ArtifactKind]{Value: GeneratedArtifact{}}
	case "example":
		return option.Some[ArtifactKind]{Value: ExampleArtifact{}}
	case "law":
		return option.Some[ArtifactKind]{Value: LawArtifact{}}
	case "differential":
		return option.Some[ArtifactKind]{Value: DifferentialArtifact{}}
	case "fuzz":
		return option.Some[ArtifactKind]{Value: FuzzArtifact{}}
	case "benchmark":
		return option.Some[ArtifactKind]{Value: BenchmarkArtifact{}}
	case "external":
		return option.Some[ArtifactKind]{Value: ExternalArtifact{}}
	default:
		return option.None[ArtifactKind]{}
	}
}

func RelationKindString(kind RelationKind) string {
	switch any(kind).(type) {
	case SpecifiesRelation:
		return "specifies"
	case DocumentsRelation:
		return "documents"
	case AnnouncesRelation:
		return "announces"
	case DecidesRelation:
		return "decides"
	case ImplementsRelation:
		return "implements"
	case TestsRelation:
		return "tests"
	case ExamplesRelation:
		return "examples"
	case GeneratesRelation:
		return "generates"
	case SupersedesRelation:
		return "supersedes"
	case DerivedFromRelation:
		return "derived-from"
	default:
		panic("goplus: impossible enum value in match")
	}
}

func ParseRelationKind(value string) option.Option[RelationKind] {
	switch value {
	case "specifies":
		return option.Some[RelationKind]{Value: SpecifiesRelation{}}
	case "documents":
		return option.Some[RelationKind]{Value: DocumentsRelation{}}
	case "announces":
		return option.Some[RelationKind]{Value: AnnouncesRelation{}}
	case "decides":
		return option.Some[RelationKind]{Value: DecidesRelation{}}
	case "implements":
		return option.Some[RelationKind]{Value: ImplementsRelation{}}
	case "tests":
		return option.Some[RelationKind]{Value: TestsRelation{}}
	case "examples":
		return option.Some[RelationKind]{Value: ExamplesRelation{}}
	case "generates":
		return option.Some[RelationKind]{Value: GeneratesRelation{}}
	case "supersedes":
		return option.Some[RelationKind]{Value: SupersedesRelation{}}
	case "derived-from":
		return option.Some[RelationKind]{Value: DerivedFromRelation{}}
	default:
		return option.None[RelationKind]{}
	}
}

// assayxport:unit schema.trace.validate
func ValidateTrace(bundle TraceBundle) result.Result[TraceValidation, []TraceFailure] {
	failures := []TraceFailure{}
	if bundle.SchemaVersion != TraceSchema {
		failures = append(failures, UnsupportedTraceSchema{Found: bundle.SchemaVersion})
	}
	kinds := map[string]ArtifactKind{}
	for _, artifact := range bundle.Artifacts {
		switch __gp_m3 := any(NewArtifactID(artifact.ID)).(type) {
		case result.Err[ArtifactID, TraceFailure]:
			failure := __gp_m3.Err

			failures = append(failures, failure)
		case result.Ok[ArtifactID, TraceFailure]:

		default:
			panic("goplus: impossible enum value in match")
		}
		if _, exists := kinds[artifact.ID]; exists {
			failures = append(failures, DuplicateArtifactIdentity{Value: artifact.ID})
			continue
		}
		switch __gp_m4 := any(ParseArtifactKind(artifact.Kind)).(type) {
		case option.None[ArtifactKind]:

			failures = append(failures, UnknownArtifactKind{Value: artifact.Kind})
		case option.Some[ArtifactKind]:
			kind := __gp_m4.Value

			kinds[artifact.ID] = kind
			if artifact.Deployable {
				switch any(kind).(type) {
				case CodeArtifact, GeneratedArtifact:

				default:

					failures = append(failures, InvalidDeployableKind{Artifact: artifact.ID})
				}
			}
		default:
			panic("goplus: impossible enum value in match")
		}
		if !validDigest(artifact.ContentDigest) {
			failures = append(failures, InvalidTraceDigest{Artifact: artifact.ID, Field: "content"})
		}
		if artifact.Deployable && !validDigest(artifact.SemanticDigest) {
			failures = append(failures, InvalidTraceDigest{Artifact: artifact.ID, Field: "semantic"})
		}
	}

	decided := map[string]bool{}
	derived := map[string]bool{}
	for _, relation := range bundle.Relations {
		switch any(ParseRelationKind(relation.Kind)).(type) {
		case option.None[RelationKind]:

			failures = append(failures, UnknownRelationKind{Value: relation.Kind})
			continue
		case option.Some[RelationKind]:

		default:
			panic("goplus: impossible enum value in match")
		}
		if _, exists := kinds[relation.From]; !exists {
			failures = append(failures, MissingArtifactEndpoint{Relation: relationKey(relation), Endpoint: relation.From})
			continue
		}
		if _, exists := kinds[relation.To]; !exists {
			failures = append(failures, MissingArtifactEndpoint{Relation: relationKey(relation), Endpoint: relation.To})
			continue
		}
		switch relation.Kind {
		case "decides":
			switch any(kinds[relation.From]).(type) {
			case DecisionArtifact:

				decided[relation.To] = true
			default:

				failures = append(failures, InvalidDecisionSource{Artifact: relation.From})
			}
		case "generates":
			derived[relation.To] = true
		}
	}
	for _, artifact := range bundle.Artifacts {
		if artifact.Deployable && !artifact.Generated && !decided[artifact.ID] {
			failures = append(failures, UndecidedCode{Artifact: artifact.ID})
		}
		if artifact.Generated && !derived[artifact.ID] {
			failures = append(failures, UnderivedGeneratedCode{Artifact: artifact.ID})
		}
	}
	if len(failures) > 0 {
		return result.Err[TraceValidation, []TraceFailure]{Err: failures}
	}
	return result.Ok[TraceValidation, []TraceFailure]{Value: TraceValid{}}
}

// assayxport:unit schema.trace.verify-release
func VerifyRelease(
	baseline TraceBundle,
	current TraceBundle,
	releaseID string,
) result.Result[TraceReport, []TraceFailure] {
	switch __gp_m8 := any(ValidateTrace(current)).(type) {
	case result.Err[TraceValidation, []TraceFailure]:
		failures := __gp_m8.Err

		return result.Err[TraceReport, []TraceFailure]{Err: failures}
	case result.Ok[TraceValidation, []TraceFailure]:

	default:
		panic("goplus: impossible enum value in match")
	}
	currentKinds := artifactKinds(current)
	switch any(currentKinds[releaseID]).(type) {
	case ReleaseNoteArtifact:

	default:

		return result.Err[TraceReport, []TraceFailure]{Err: []TraceFailure{MissingReleaseNote{Artifact: releaseID}}}
	}
	announced := map[string]bool{}
	for _, relation := range current.Relations {
		if relation.From == releaseID && relation.Kind == "announces" {
			announced[relation.To] = true
		}
	}
	decisions := map[string][]string{}
	allRelations := append([]TraceRelation{}, baseline.Relations...)
	allRelations = append(allRelations, current.Relations...)
	for _, relation := range allRelations {
		if relation.Kind == "decides" {
			decisions[relation.To] = append(decisions[relation.To], relation.From)
		}
	}
	changed := ChangedDeployable(baseline, current)
	missing := []string{}
	for _, artifact := range changed {
		closed := false
		for _, decision := range decisions[artifact] {
			if announced[decision] {
				closed = true
				break
			}
		}
		if !closed {
			missing = append(missing, artifact)
		}
	}
	if len(missing) > 0 {
		failures := make([]TraceFailure, len(missing))
		for index, artifact := range missing {
			failures[index] = UnreasonedChange{Artifact: artifact}
		}
		return result.Err[TraceReport, []TraceFailure]{Err: failures}
	}
	return result.Ok[TraceReport, []TraceFailure]{Value: TraceReport{Changed: changed, Missing: missing}}
}

func ChangedDeployable(baseline TraceBundle, current TraceBundle) []string {
	before := map[string]TraceArtifact{}
	after := map[string]TraceArtifact{}
	for _, artifact := range baseline.Artifacts {
		if artifact.Deployable {
			before[artifact.ID] = artifact
		}
	}
	for _, artifact := range current.Artifacts {
		if artifact.Deployable {
			after[artifact.ID] = artifact
		}
	}
	changed := []string{}
	for id, artifact := range after {
		previous, exists := before[id]
		if !exists ||
			previous.SemanticDigest != artifact.SemanticDigest ||
			previous.PublicAPI != artifact.PublicAPI {
			changed = append(changed, id)
		}
	}
	for id := range before {
		if _, exists := after[id]; !exists {
			changed = append(changed, id)
		}
	}
	sort.Strings(changed)
	return changed
}

func CanonicalTrace(bundle TraceBundle) TraceBundle {
	out := bundle
	out.Artifacts = append([]TraceArtifact{}, bundle.Artifacts...)
	out.Relations = append([]TraceRelation{}, bundle.Relations...)
	sort.Slice(out.Artifacts, func(i, j int) bool {
		if out.Artifacts[i].ID != out.Artifacts[j].ID {
			return out.Artifacts[i].ID < out.Artifacts[j].ID
		}
		return out.Artifacts[i].Kind < out.Artifacts[j].Kind
	})
	sort.Slice(out.Relations, func(i, j int) bool {
		left, right := out.Relations[i], out.Relations[j]
		if left.From != right.From {
			return left.From < right.From
		}
		if left.Kind != right.Kind {
			return left.Kind < right.Kind
		}
		return left.To < right.To
	})
	return out
}

func BundleDigest(bundle TraceBundle) result.Result[string, error] {
	encoded, encodeError := json.Marshal(CanonicalTrace(bundle))
	switch __gp_m10 := any(result.Of(encoded, encodeError)).(type) {
	case result.Err[[]byte, error]:
		cause := __gp_m10.Err

		return result.Err[string, error]{Err: cause}
	case result.Ok[[]byte, error]:
		content := __gp_m10.Value

		return result.Ok[string, error]{Value: DigestBytes(content)}
	default:
		panic("goplus: impossible enum value in match")
	}
}

func DigestText(content string) string { return DigestBytes([]byte(content)) }

func DigestBytes(content []byte) string {
	digest := sha256.Sum256(content)
	return hex.EncodeToString(digest[:])
}

func ArtifactURL(module string, version string, kind ArtifactKind, id string) string {
	name := strings.TrimPrefix(module, "goforge.dev/")
	return "https://goforge.dev/" +
		url.PathEscape(name) + "/" +
		url.PathEscape(version) + "/artifacts/" +
		url.PathEscape(ArtifactKindString(kind)) + "/" +
		url.PathEscape(id)
}

func ParseUnitDirective(comment string) result.Result[ArtifactID, TraceFailure] {
	text := strings.TrimSpace(comment)
	text = strings.TrimLeft(text, "/#*% \t")
	index := strings.Index(text, UnitDirective)
	if index < 0 {
		return result.Err[ArtifactID, TraceFailure]{Err: InvalidArtifactIdentity{Value: comment}}
	}
	fields := strings.Fields(text[index+len(UnitDirective):])
	if len(fields) == 0 {
		return result.Err[ArtifactID, TraceFailure]{Err: InvalidArtifactIdentity{Value: comment}}
	}
	return NewArtifactID(fields[0])
}

func artifactKinds(bundle TraceBundle) map[string]ArtifactKind {
	out := map[string]ArtifactKind{}
	for _, artifact := range bundle.Artifacts {
		switch __gp_m11 := any(ParseArtifactKind(artifact.Kind)).(type) {
		case option.Some[ArtifactKind]:
			kind := __gp_m11.Value
			out[artifact.ID] = kind
		case option.None[ArtifactKind]:

		default:
			panic("goplus: impossible enum value in match")
		}
	}
	return out
}

func validDigest(value string) bool {
	if len(value) != 64 {
		return false
	}
	for _, character := range value {
		switch {
		case character >= '0' && character <= '9':
		case character >= 'a' && character <= 'f':
		default:
			return false
		}
	}
	return true
}

func relationKey(relation TraceRelation) string {
	return relation.From + " " + relation.Kind + " " + relation.To
}
