// Code generated by goplus from units.gp. DO NOT EDIT.
//goplus:v v0.16.1

package schema

import "goforge.dev/goplus/std/result"

type SourceLine int
type SourceColumn int
type CallCount int
type Arity int
type ByteSize int64
type ByteBudget int64
type TreeVersion uint64
type Priority int
type WorkerCount int

//goplus:enum UnitFailure
type UnitFailure interface{ isUnitFailure() }

//goplus:variant (UnitFailure) OutOfRange(unit string, value int64)
type OutOfRange struct {
	Unit  string
	Value int64
}

func (OutOfRange) isUnitFailure() {}

// UnitFailureCases selects one handler per UnitFailure variant for UnitFailureFold.
type UnitFailureCases[R any] struct {
	OutOfRange func(unit string, value int64) R
}

// UnitFailureFold reduces UnitFailure by one-level case analysis.
func UnitFailureFold[R any](u UnitFailure, cs UnitFailureCases[R]) R {
	switch m := any(u).(type) {
	case OutOfRange:
		return cs.OutOfRange(m.Unit, m.Value)
	default:
		panic("goplus: impossible enum value in UnitFailureFold")
	}
}

// UnitFailureEqOverrides carries optional per-variant hooks for UnitFailureEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type UnitFailureEqOverrides struct {
	OutOfRange func(x, y OutOfRange) (eq, handled bool)
}

// UnitFailureEqualWith reports structural equality of a and b under ov.
func UnitFailureEqualWith(a, b UnitFailure, ov UnitFailureEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case OutOfRange:
		y, ok := any(b).(OutOfRange)
		if !ok {
			return false
		}
		if ov.OutOfRange != nil {
			if eq, handled := ov.OutOfRange(x, y); handled {
				return eq
			}
		}
		if x.Unit != y.Unit {
			return false
		}
		if x.Value != y.Value {
			return false
		}
		return true
	}
	return false
}

// UnitFailureEqual reports structural equality of a and b.
func UnitFailureEqual(a, b UnitFailure) bool {
	return UnitFailureEqualWith(a, b, UnitFailureEqOverrides{})
}

func PositiveSourceLine(v int) result.Result[SourceLine, UnitFailure] {
	if v < 1 {
		return result.Err[SourceLine, UnitFailure]{Err: OutOfRange{Unit: "source line", Value: int64(v)}}
	}
	return result.Ok[SourceLine, UnitFailure]{Value: SourceLine(v)}
}
func PositiveSourceColumn(v int) result.Result[SourceColumn, UnitFailure] {
	if v < 1 {
		return result.Err[SourceColumn, UnitFailure]{Err: OutOfRange{Unit: "source column", Value: int64(v)}}
	}
	return result.Ok[SourceColumn, UnitFailure]{Value: SourceColumn(v)}
}
func PositiveCallCount(v int) result.Result[CallCount, UnitFailure] {
	if v < 1 {
		return result.Err[CallCount, UnitFailure]{Err: OutOfRange{Unit: "call count", Value: int64(v)}}
	}
	return result.Ok[CallCount, UnitFailure]{Value: CallCount(v)}
}
func NonnegativeArity(v int) result.Result[Arity, UnitFailure] {
	if v < 0 {
		return result.Err[Arity, UnitFailure]{Err: OutOfRange{Unit: "arity", Value: int64(v)}}
	}
	return result.Ok[Arity, UnitFailure]{Value: Arity(v)}
}
func PositiveWorkerCount(v int) result.Result[WorkerCount, UnitFailure] {
	if v < 1 {
		return result.Err[WorkerCount, UnitFailure]{Err: OutOfRange{Unit: "worker count", Value: int64(v)}}
	}
	return result.Ok[WorkerCount, UnitFailure]{Value: WorkerCount(v)}
}
