// Code generated by goplus from java.gp. DO NOT EDIT.
//goplus:v v0.15.0

// Package java implements the assayxport Extractor for Java source trees. It
// produces one schema.Package per .java compilation unit (level "module") and
// one per Java package declaration (level "package"). Packages are keyed by the
// `package` declaration, not by directory, so ids never embed host paths.
package java

import (
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"sync"

	"goforge.dev/assayxport/internal/schema"
)

// Extractor implements extract.Extractor for Java.
type Extractor struct{}

// New returns a new Java Extractor.
func New() *Extractor { return &Extractor{} }

// Language returns "java".
func (*Extractor) Language() string { return "java" }

// Extract discovers all .java files under root and returns one module unit per
// file and one package unit per package declaration, sorted by ID. It buffers
// ExtractStream's output; callers that can consume packages incrementally
// (large trees) should use ExtractStream directly to keep memory bounded.
func (e *Extractor) Extract(root string) ([]schema.Package, error) {
	var out []schema.Package
	var mu sync.Mutex
	if err := e.ExtractStream(root, func(p schema.Package) error {
		mu.Lock()
		out = append(out, p)
		mu.Unlock()
		return nil
	}); err != nil {
		return nil, err
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].ID != out[j].ID {
			return out[i].ID < out[j].ID
		}
		return out[i].Path < out[j].Path // stable total order when two files share an FQCN
	})
	return out, nil
}

// modRec is the lightweight per-file record ExtractStream keeps after a file's
// module shard has been emitted and its symbols released -- just enough to build
// the package units and member lists without holding any symbols.
type modRec struct {
	packageName string
	dir         string
	moduleID    string // "" for package-info.java (no module unit)
	isPkgInfo   bool
	pkgDoc      string
}

// ExtractStream parses every .java file under root across a worker pool and
// emits each file's module unit as soon as it is parsed, so the caller can write
// the shard and release its symbols immediately; only lightweight per-file
// records are retained, from which the (symbol-free) package units and member
// lists are built and emitted at the end. Output is the same set of packages as
// Extract; the writer sorts by id, so emission order does not matter.
func (*Extractor) ExtractStream(root string, emit func(schema.Package) error) error {
	files, err := discover(root)
	if err != nil {
		return err
	}

	recs := make([]modRec, len(files)) // indexed by file (sorted) order
	perr := make([]error, len(files))
	var mu sync.Mutex
	var emitErr error

	// Leave one core unused so a caller sharing this process -- notably
	// `ax serve`, which parses in a background goroutine while its HTTP server
	// answers "analyzing" on the main one -- stays responsive during the parse.
	workers := runtime.NumCPU() - 1
	if workers < 1 {
		workers = 1
	}
	var wg sync.WaitGroup
	jobs := make(chan int)
	for w := 0; w < workers; w++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for i := range jobs {
				src, rerr := os.ReadFile(files[i].Abs)
				if rerr != nil {
					perr[i] = rerr
					continue
				}
				res, cerr := compilationUnit(files[i].Rel, src)
				if cerr != nil {
					perr[i] = cerr
					continue
				}
				stem := strings.TrimSuffix(filepath.Base(files[i].Rel), ".java")
				dir := filepath.ToSlash(filepath.Dir(files[i].Rel))
				if dir == "." {
					dir = ""
				}
				rec := modRec{packageName: res.PackageName, dir: dir}
				if res.IsPackageInfo {
					// package-info.java carries no module symbols; it supplies the
					// package doc and a preferred package Path.
					rec.isPkgInfo = true
					rec.pkgDoc = res.PackageDoc
					recs[i] = rec
					continue
				}
				moduleID := stem
				if res.PackageName != "" {
					moduleID = res.PackageName + "." + stem
				}
				rec.moduleID = moduleID
				recs[i] = rec
				mod := schema.Package{
					ID:       moduleID,
					Language: "java",
					Path:     files[i].Rel,
					Name:     stem,
					Level:    "module",
					Symbols:  res.Syms,
				}
				if res.HasMain {
					fqcn := res.MainType
					if res.PackageName != "" {
						fqcn = res.PackageName + "." + res.MainType
					}
					how := "java " + fqcn
					mod.IsEntrypoint = true
					// The module unit and the stamped main symbol each get their
					// own Invocation value (same fields) to avoid sharing a pointer.
					mod.Invocation = &schema.Invocation{Kind: "class", How: how}
					for k := range mod.Symbols {
						s := &mod.Symbols[k]
						if s.Kind == "method" && s.Name == "main" && s.Owner == res.MainType {
							s.IsEntrypoint = true
							s.Invocation = &schema.Invocation{Kind: "class", How: how}
						}
					}
				}
				mu.Lock()
				stop := emitErr != nil
				mu.Unlock()
				if stop {
					continue
				}
				if e := emit(mod); e != nil {
					mu.Lock()
					if emitErr == nil {
						emitErr = e
					}
					mu.Unlock()
				}
			}
		}()
	}
	for i := range files {
		jobs <- i
	}
	close(jobs)
	wg.Wait()

	for _, e := range perr {
		if e != nil {
			return e
		}
	}
	if emitErr != nil {
		return emitErr
	}

	// Build package units from the lightweight records, in sorted file order so
	// the package Path ("first file wins") is deterministic. package-info.java's
	// doc and dir win over a plain compilation unit's.
	packageUnits := make(map[string]schema.Package)
	pkgDir := make(map[string]string)
	pkgHasInfo := make(map[string]bool)
	for _, rec := range recs {
		if rec.packageName == "" {
			continue
		}
		if rec.isPkgInfo {
			pkg := packageUnits[rec.packageName]
			pkg.ID = rec.packageName
			pkg.Language = "java"
			pkg.Level = "package"
			pkg.Name = simpleName(rec.packageName)
			pkg.Doc = rec.pkgDoc
			packageUnits[rec.packageName] = pkg
			pkgDir[rec.packageName] = rec.dir
			pkgHasInfo[rec.packageName] = true
			continue
		}
		if _, ok := packageUnits[rec.packageName]; !ok {
			packageUnits[rec.packageName] = schema.Package{
				ID:       rec.packageName,
				Language: "java",
				Level:    "package",
				Name:     simpleName(rec.packageName),
			}
		}
		if !pkgHasInfo[rec.packageName] {
			if _, ok := pkgDir[rec.packageName]; !ok {
				pkgDir[rec.packageName] = rec.dir
			}
		}
	}

	// Assign package Members. A unit's direct parent is its id minus the last
	// dotted segment, so bucketing every module and package unit under its parent
	// is one O(M+P) pass -- versus scanning all units for every package
	// (O(P*(M+P))), which on a large tree is tens of millions of prefix compares.
	memberLists := make(map[string][]string, len(packageUnits))
	addMember := func(childID string) {
		parent := parentID(childID)
		if _, ok := packageUnits[parent]; ok {
			memberLists[parent] = append(memberLists[parent], childID)
		}
	}
	for _, rec := range recs {
		if rec.moduleID != "" {
			addMember(rec.moduleID)
		}
	}
	for subID := range packageUnits {
		addMember(subID)
	}

	// Emit the package units (member lists + doc; no symbols).
	for pkgID := range packageUnits {
		pkg := packageUnits[pkgID]
		members := memberLists[pkgID]
		sort.Strings(members)
		pkg.Members = members
		pkg.Path = pkgDir[pkgID]
		if err := emit(pkg); err != nil {
			return err
		}
	}
	return nil
}
