// Code generated by goplus from complexity.gp. DO NOT EDIT.
//goplus:v v0.16.1

// Package complexity is assayxport's best-effort, intraprocedural, syntactic
// big-O estimator. It maps a language-agnostic control-flow Summary (produced by
// each language extractor) to a schema.Complexity. The estimate is a coarse
// triage signal, not a proof: it counts loop nesting, declines to bound
// recursion, and never propagates callee cost.
package complexity

import "goforge.dev/assayxport/internal/schema"

// Summary is a normalized control-flow summary of one function body.
type Summary struct {
	MaxLoopDepth int  // deepest nesting of loops (0 = no loops)
	Recursive    bool // the body calls the function's own name (direct recursion)
	AllocInLoop  bool // an allocation occurs inside at least one loop
	AllocDepth   int  // loop-nesting depth at the deepest in-loop allocation
}

// Estimate maps a Summary to a big-O complexity. Pure and deterministic.
func Estimate(s Summary) schema.Complexity {
	if s.Recursive {
		// Loop nesting cannot bound a recursive function; refuse to guess.
		return schema.Complexity{Time: nil, Space: nil, Method: "recursive"}
	}
	t := bigO(s.MaxLoopDepth)
	space := "O(1)"
	if s.AllocInLoop {
		space = bigO(s.AllocDepth)
	}
	return schema.Complexity{Time: &t, Space: &space, Method: "loop-nesting"}
}

// bigO renders a polynomial degree as a big-O string.
func bigO(degree int) string {
	switch {
	case degree <= 0:
		return "O(1)"
	case degree == 1:
		return "O(n)"
	default:
		return "O(n^" + itoa(degree) + ")"
	}
}

// itoa avoids a strconv import for small non-negative integers.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var b []byte
	for n > 0 {
		b = append([]byte{byte('0' + n%10)}, b...)
		n /= 10
	}
	return string(b)
}
